\copy stats_modified.allstarfull TO 'Documents/Personal/ootp_stuff/databaseConverter/stats_modified/AllstarFull.csv' DELIMITER ',' NULL AS '' CSV HEADER encoding 'UTF-8';
\copy stats_modified.awardsmanagers TO 'Documents/Personal/ootp_stuff/databaseConverter/stats_modified/awardsmanagers.csv' DELIMITER ',' NULL AS '' CSV HEADER encoding 'UTF-8';
\copy stats_modified.awardsplayers TO 'Documents/Personal/ootp_stuff/databaseConverter/stats_modified/awardsplayers.csv' DELIMITER ',' NULL AS '' CSV HEADER encoding 'UTF-8';
\copy stats_modified.batting TO 'Documents/Personal/ootp_stuff/databaseConverter/stats_modified/batting.csv' DELIMITER ',' NULL AS '' CSV HEADER encoding 'UTF-8';
\copy stats_modified.batting2 TO 'Documents/Personal/ootp_stuff/databaseConverter/stats_modified/batting2.csv' DELIMITER ',' NULL AS '' CSV HEADER encoding 'UTF-8';
\copy stats_modified.battingpost TO 'Documents/Personal/ootp_stuff/databaseConverter/stats_modified/battingpost.csv' DELIMITER ',' NULL AS '' CSV HEADER encoding 'UTF-8';
\copy stats_modified.battingsplits TO 'Documents/Personal/ootp_stuff/databaseConverter/stats_modified/battingsplits.csv' DELIMITER ',' NULL AS '' CSV HEADER encoding 'UTF-8';
\copy stats_modified.eosrosters TO 'Documents/Personal/ootp_stuff/databaseConverter/stats_modified/eosrosters.csv' DELIMITER ',' NULL AS '' CSV encoding 'UTF-8';
\copy stats_modified.fielding TO 'Documents/Personal/ootp_stuff/databaseConverter/stats_modified/fielding.csv' DELIMITER ',' NULL AS '' CSV HEADER encoding 'UTF-8';
\copy stats_modified.fieldingof TO 'Documents/Personal/ootp_stuff/databaseConverter/stats_modified/fieldingof.csv' DELIMITER ',' NULL AS '' CSV HEADER encoding 'UTF-8';
\copy stats_modified.fieldingpost TO 'Documents/Personal/ootp_stuff/databaseConverter/stats_modified/fieldingpost.csv' DELIMITER ',' NULL AS '' CSV HEADER encoding 'UTF-8';
\copy stats_modified.fieldingratings TO 'Documents/Personal/ootp_stuff/databaseConverter/stats_modified/fieldingratings.csv' DELIMITER ',' NULL AS '' CSV HEADER encoding 'UTF-8';
\copy stats_modified.halloffame TO 'Documents/Personal/ootp_stuff/databaseConverter/stats_modified/halloffame.csv' DELIMITER ',' NULL AS '' CSV HEADER encoding 'UTF-8';
\copy stats_modified.lineups TO 'Documents/Personal/ootp_stuff/databaseConverter/stats_modified/lineups.csv' DELIMITER ',' NULL AS '' CSV encoding 'UTF-8';
\copy stats_modified.managers TO 'Documents/Personal/ootp_stuff/databaseConverter/stats_modified/managers.csv' DELIMITER ',' NULL AS '' CSV HEADER encoding 'UTF-8';
\copy stats_modified.master TO 'Documents/Personal/ootp_stuff/databaseConverter/stats_modified/master.csv' DELIMITER ',' NULL AS '' CSV HEADER encoding 'UTF-8';
\copy stats_modified.milbbatting TO 'Documents/Personal/ootp_stuff/databaseConverter/stats_modified/milbbatting.csv' DELIMITER ',' NULL AS '' CSV HEADER encoding 'UTF-8';
\copy stats_modified.milbfielding TO 'Documents/Personal/ootp_stuff/databaseConverter/stats_modified/milbfielding.csv' DELIMITER ',' NULL AS '' CSV HEADER encoding 'UTF-8';
\copy stats_modified.milbleagues TO 'Documents/Personal/ootp_stuff/databaseConverter/stats_modified/milbleagues.csv' DELIMITER ',' NULL AS '' CSV HEADER encoding 'UTF-8';
\copy stats_modified.milbmaster TO 'Documents/Personal/ootp_stuff/databaseConverter/stats_modified/milbmaster.csv' DELIMITER ',' NULL AS '' CSV HEADER encoding 'UTF-8';
\copy stats_modified.milbpitching TO 'Documents/Personal/ootp_stuff/databaseConverter/stats_modified/milbpitching.csv' DELIMITER ',' NULL AS '' CSV HEADER encoding 'UTF-8';
\copy stats_modified.milbteams TO 'Documents/Personal/ootp_stuff/databaseConverter/stats_modified/milbteams.csv' DELIMITER ',' NULL AS '' CSV HEADER encoding 'UTF-8';
\copy stats_modified.negroleaguebatting TO 'Documents/Personal/ootp_stuff/databaseConverter/stats_modified/negroleaguebatting.csv' DELIMITER ',' NULL AS '' CSV HEADER encoding 'UTF-8';
\copy stats_modified.negroleaguefielding TO 'Documents/Personal/ootp_stuff/databaseConverter/stats_modified/negroleaguefielding.csv' DELIMITER ',' NULL AS '' CSV HEADER encoding 'UTF-8';
\copy stats_modified.negroleaguepitching TO 'Documents/Personal/ootp_stuff/databaseConverter/stats_modified/negroleaguepitching.csv' DELIMITER ',' NULL AS '' CSV HEADER encoding 'UTF-8';
\copy stats_modified.odrosters TO 'Documents/Personal/ootp_stuff/databaseConverter/stats_modified/odrosters.csv' DELIMITER ',' NULL AS '' CSV encoding 'UTF-8';
\copy stats_modified.pitching TO 'Documents/Personal/ootp_stuff/databaseConverter/stats_modified/pitching.csv' DELIMITER ',' NULL AS '' CSV HEADER encoding 'UTF-8';
\copy stats_modified.pitching2 TO 'Documents/Personal/ootp_stuff/databaseConverter/stats_modified/pitching2.csv' DELIMITER ',' NULL AS '' CSV HEADER encoding 'UTF-8';
\copy stats_modified.pitchingpost TO 'Documents/Personal/ootp_stuff/databaseConverter/stats_modified/pitchingpost.csv' DELIMITER ',' NULL AS '' CSV HEADER encoding 'UTF-8';
\copy stats_modified.pitchingratings TO 'Documents/Personal/ootp_stuff/databaseConverter/stats_modified/pitchingratings.csv' DELIMITER ',' NULL AS '' CSV HEADER encoding 'UTF-8';
\copy stats_modified.pitchingsplits TO 'Documents/Personal/ootp_stuff/databaseConverter/stats_modified/pitchingsplits.csv' DELIMITER ',' NULL AS '' CSV HEADER encoding 'UTF-8';
\copy stats_modified.seriespost TO 'Documents/Personal/ootp_stuff/databaseConverter/stats_modified/seriespost.csv' DELIMITER ',' NULL AS '' CSV HEADER encoding 'UTF-8';
\copy stats_modified.recordssinglegame TO 'Documents/Personal/ootp_stuff/databaseConverter/stats_modified/recordssinglegame.csv' DELIMITER ',' NULL AS '' CSV HEADER encoding 'UTF-8';
\copy stats_modified.teamfranchises TO 'Documents/Personal/ootp_stuff/databaseConverter/stats_modified/teamfranchises.csv' DELIMITER ',' NULL AS '' CSV HEADER encoding 'UTF-8';
\copy stats_modified.teams TO 'Documents/Personal/ootp_stuff/databaseConverter/stats_modified/teams.csv' DELIMITER ',' NULL AS '' CSV HEADER encoding 'UTF-8';
\copy stats_modified.transactions TO 'Documents/Personal/ootp_stuff/databaseConverter/stats_modified/transactions.csv' DELIMITER ',' NULL AS '' CSV encoding 'UTF-8';
\copy stats_modified.uninumbers TO 'Documents/Personal/ootp_stuff/databaseConverter/stats_modified/uninumbers.csv' DELIMITER ',' NULL AS '' CSV HEADER encoding 'UTF-8';
