create temporary table leagues
(
    league_id                              integer,
    name                                   text,
    abbr                                   text,
    nation_id                              integer,
    language_id                            integer,
    gender                                 integer,
    historical_league                      integer,
    logo_file_name                         text,
    players_path                           text,
    start_date                             text,
    preferred_start_date                   text,
    pitcher_award_name                     text,
    mvp_award_name                         text,
    rookie_award_name                      text,
    defense_award_name                     text,
    fictional_players                      integer,
    start_fantasy_draft                    integer,
    trading_deadline                       integer,
    winter_meetings                        integer,
    arbitration_offering                   integer,
    show_draft_pool                        integer,
    rosters_expanded                       integer,
    draft_date                             text,
    rule_5_draft_date                      text,
    international_fa_date                  text,
    roster_expand_date                     text,
    trade_deadline_date                    text,
    allstar_date                           text,
    days_until_deadline                    integer,
    next_draft_type                        integer,
    parent_league_id                       integer,
    league_state                           integer,
    season_year                            integer,
    historical_year                        integer,
    league_level                           integer,
    stats_detail                           integer,
    historical_import_path                 text,
    foreigner_percentage                   integer,
    was_ootp6                              integer,
    was_65                                 integer,
    allstar_game                           integer,
    auto_schedule_allstar                  integer,
    allstar_team_id0                       integer,
    allstar_team_id1                       integer,
    schedule_file_1                        text,
    schedule_file_2                        text,
    rules_rule_5                           integer,
    rules_minor_league_options             integer,
    rules_trading                          integer,
    rules_trading_deadline_events          integer,
    rules_draft_pick_trading               integer,
    rules_financials                       integer,
    rules_amateur_draft                    integer,
    rules_fa_compensation                  integer,
    rules_schedule_balanced                integer,
    rules_schedule_inter_league            integer,
    rules_schedule_force_start_day         integer,
    rules_trades_other_leagues             integer,
    rules_free_agents_from_other_leagues   integer,
    rules_free_agents_leave_other_leagues  integer,
    rules_allstar_game                     integer,
    rules_spring_training                  integer,
    rules_active_roster_limit              integer,
    rules_secondary_roster_limit           integer,
    rules_expanded_roster_limit            integer,
    rules_min_service_days                 integer,
    rules_waiver_period_length             integer,
    rules_dfa_period_length                integer,
    rules_fa_minimum_years                 integer,
    rules_salary_arbitration_minimum_years integer,
    rules_minor_league_fa_minimum_years    integer,
    rules_foreigner_limit                  integer,
    rules_foreigner_pitcher_limit          integer,
    rules_foreigner_hitter_limit           integer,
    rules_schedule_games_per_team          integer,
    rules_schedule_typical_series          integer,
    rules_schedule_game_times              integer,
    rules_schedule_preferred_start_day     integer,
    rules_amateur_draft_rounds             integer,
    rules_minimum_salary                   integer,
    rules_salary_cap                       integer,
    rules_player_salary0                   integer,
    rules_player_salary1                   integer,
    rules_player_salary2                   integer,
    rules_player_salary3                   integer,
    rules_player_salary4                   integer,
    rules_player_salary5                   integer,
    rules_player_salary6                   integer,
    rules_player_salary7                   integer,
    rules_average_coach_salary             integer,
    rules_average_attendance               integer,
    rules_average_national_media_contract  integer,
    rules_cash_maximum                     integer,
    rules_average_ticket_price             double precision,
    rules_luxury_sharing                   integer,
    rules_revenue_sharing                  integer,
    rules_revenue_sharing_tax              integer,
    rules_luxury_sharing_cap               integer,
    rules_luxury_tax                       integer,
    rules_national_media_contract_fixed    integer,
    rules_owner_decides_budget             integer,
    rules_schedule_auto_adjust_dates       integer,
    rules_historical_import_rookies        integer,
    avg_rating_contact                     integer,
    avg_rating_gap                         integer,
    avg_rating_power                       integer,
    avg_rating_eye                         integer,
    avg_rating_strikeouts                  integer,
    avg_rating_stuff                       integer,
    avg_rating_movement                    integer,
    avg_rating_control                     integer,
    avg_rating_fielding0                   integer,
    avg_rating_fielding1                   integer,
    avg_rating_fielding2                   integer,
    avg_rating_fielding3                   integer,
    avg_rating_fielding4                   integer,
    avg_rating_fielding5                   integer,
    avg_rating_fielding6                   integer,
    avg_rating_fielding7                   integer,
    avg_rating_fielding8                   integer,
    avg_rating_fielding9                   integer,
    avg_rating_overall                     integer,
    avg_rating_age                         double precision,
    league_totals_ab                       integer,
    league_totals_h                        integer,
    league_totals_d                        integer,
    league_totals_t                        integer,
    league_totals_hr                       integer,
    league_totals_bb                       integer,
    league_totals_hp                       integer,
    league_totals_k                        integer,
    league_totals_pa                       integer,
    league_totals_babip                    double precision,
    league_totals_mod_h                    double precision,
    league_totals_mod_d                    double precision,
    league_totals_mod_t                    double precision,
    league_totals_mod_hr                   double precision,
    league_totals_mod_bb                   double precision,
    league_totals_mod_hp                   double precision,
    league_totals_mod_k                    double precision,
    league_totals_mod_babip                double precision,
    ml_equivalencies_avg                   double precision,
    ml_equivalencies_hr                    double precision,
    ml_equivalencies_eb                    double precision,
    ml_equivalencies_bb                    double precision,
    ml_equivalencies_k                     double precision,
    ml_equivalencies_hp                    double precision,
    player_creation_modifier_contact       double precision,
    player_creation_modifier_gap           double precision,
    player_creation_modifier_power         double precision,
    player_creation_modifier_eye           double precision,
    player_creation_modifier_strikeouts    double precision,
    player_creation_modifier_stuff         double precision,
    player_creation_modifier_movement      double precision,
    player_creation_modifier_control       double precision,
    player_creation_modifier_speed         double precision,
    player_creation_modifier_fielding      double precision,
    financial_coefficient                  double precision,
    world_start_year                       integer,
    "current_date"                         text,
    background_color_id                    text,
    text_color_id                          text,
    scouting_coach_id                      integer
);

\copy leagues FROM '/Users/brianmcneil/Library/Containers/com.ootpdevelopments.ootp26macqlm/Data/Application Support/Out of the Park Developments/OOTP Baseball 26/saved_games/WPOBL-test.lg/import_export/csv/leagues.csv' DELIMITER ',' NULL AS 'NULL' CSV HEADER encoding 'UTF-8';

create temporary table teams
(
    team_id                     integer,
    name                        text,
    abbr                        text,
    nickname                    text,
    logo_file_name              text,
    city_id                     integer,
    park_id                     integer,
    league_id                   integer,
    sub_league_id               integer,
    division_id                 integer,
    nation_id                   integer,
    parent_team_id              integer,
    level                       integer,
    prevent_any_moves           integer,
    human_team                  integer,
    human_id                    integer,
    gender                      integer,
    background_color_id         text,
    text_color_id               text,
    ballcaps_main_color_id      text,
    ballcaps_visor_color_id     text,
    jersey_main_color_id        text,
    jersey_away_color_id        text,
    jersey_secondary_color_id   text,
    jersey_pin_stripes_color_id text,
    allstar_team                integer,
    historical_id               text
);

\copy teams FROM '/Users/brianmcneil/Library/Containers/com.ootpdevelopments.ootp26macqlm/Data/Application Support/Out of the Park Developments/OOTP Baseball 26/saved_games/WPOBL-test.lg/import_export/csv/teams.csv' DELIMITER ',' NULL AS 'NULL' CSV HEADER encoding 'UTF-8';

create temporary table players
(
    player_id                   integer,
    team_id                     integer,
    league_id                   integer,
    position                    integer,
    role                        integer,
    first_name                  text,
    last_name                   text,
    nick_name                   text,
    age                         integer,
    date_of_birth               text,
    city_of_birth_id            integer,
    nation_id                   integer,
    second_nation_id            integer,
    weight                      integer,
    height                      integer,
    retired                     integer,
    free_agent                  integer,
    last_league_id              integer,
    last_team_id                integer,
    organization_id             integer,
    last_organization_id        integer,
    language_ids0               integer,
    language_ids1               integer,
    uniform_number              integer,
    experience                  integer,
    person_type                 integer,
    bats                        integer,
    throws                      integer,
    personality_greed           integer,
    personality_loyalty         integer,
    personality_play_for_winner integer,
    personality_work_ethic      integer,
    personality_intelligence    integer,
    personality_leader          integer,
    historical_id               text,
    historical_team_id          text,
    best_contract_offer_id      integer,
    injury_is_injured           integer,
    injury_dtd_injury           integer,
    injury_career_ending        integer,
    injury_dl_left              integer,
    injury_dl_playoff_round     integer,
    injury_left                 integer,
    dtd_injury_effect           integer,
    dtd_injury_effect_hit       integer,
    dtd_injury_effect_throw     integer,
    dtd_injury_effect_run       integer,
    injury_id                   integer,
    injury_id2                  integer,
    injury_dtd_injury2          integer,
    injury_left2                integer,
    dtd_injury_effect2          integer,
    dtd_injury_effect_hit2      integer,
    dtd_injury_effect_throw2    integer,
    dtd_injury_effect_run2      integer,
    prone_overall               integer,
    prone_leg                   integer,
    prone_back                  integer,
    prone_arm                   integer,
    fatigue_pitches0            integer,
    fatigue_pitches1            integer,
    fatigue_pitches2            integer,
    fatigue_pitches3            integer,
    fatigue_pitches4            integer,
    fatigue_pitches5            integer,
    fatigue_points              integer,
    fatigue_played_today        integer,
    college                     integer,
    acquired                    integer,
    acquired_date               text,
    draft_year                  integer,
    draft_round                 integer,
    draft_supplemental          integer,
    draft_pick                  integer,
    draft_overall_pick          integer,
    draft_eligible              integer,
    hsc_status                  integer,
    redshirt                    integer,
    picked_in_draft             integer,
    school                      integer,
    commit_school               integer,
    hidden                      integer,
    draft_league_id             integer,
    draft_team_id               integer,
    turned_coach                integer,
    hall_of_fame                integer,
    rust                        integer,
    inducted                    integer,
    strategy_override_team      integer,
    strategy_stealing           integer,
    strategy_running            integer,
    strategy_bunt_for_hit       integer,
    strategy_sac_bunt           integer,
    strategy_hit_run            integer,
    strategy_hook_start         integer,
    strategy_hook_relief        integer,
    strategy_pitch_count        integer,
    strategy_pitch_around       integer,
    strategy_never_pinch_hit    integer,
    strategy_defensive_sub      integer,
    strategy_dtd_sit_min        integer,
    strategy_dtd_allow_ph       integer,
    local_pop                   integer,
    national_pop                integer,
    draft_protected             integer,
    morale                      integer,
    morale_mod                  integer,
    morale_player_performance   integer,
    morale_team_performance     integer,
    morale_team_transactions    integer,
    morale_team_chemistry       integer,
    morale_player_role          integer,
    expectation                 integer,
    on_loan                     integer,
    loan_league_id              integer,
    loan_team_id                integer
);

\copy players FROM '/Users/brianmcneil/Library/Containers/com.ootpdevelopments.ootp26macqlm/Data/Application Support/Out of the Park Developments/OOTP Baseball 26/saved_games/WPOBL-test.lg/import_export/csv/players.csv' DELIMITER ',' NULL AS 'NULL' CSV HEADER encoding 'UTF-8';

insert into player.coach (coach_id, first_name, last_name)
values (-1, 'OSA','Scout')
ON CONFLICT (coach_id) DO NOTHING;

create temporary table players_batting
(
    player_id                           integer,
    team_id                             integer,
    league_id                           integer,
    position                            integer,
    role                                integer,
    bats                                integer,
    batting_ratings_overall_contact     integer,
    batting_ratings_overall_gap         integer,
    batting_ratings_overall_eye         integer,
    batting_ratings_overall_strikeouts  integer,
    batting_ratings_overall_hp          integer,
    batting_ratings_overall_power       integer,
    batting_ratings_overall_babip       integer,
    batting_ratings_vsr_contact         integer,
    batting_ratings_vsr_gap             integer,
    batting_ratings_vsr_eye             integer,
    batting_ratings_vsr_strikeouts      integer,
    batting_ratings_vsr_hp              integer,
    batting_ratings_vsr_power           integer,
    batting_ratings_vsr_babip           integer,
    batting_ratings_vsl_contact         integer,
    batting_ratings_vsl_gap             integer,
    batting_ratings_vsl_eye             integer,
    batting_ratings_vsl_strikeouts      integer,
    batting_ratings_vsl_hp              integer,
    batting_ratings_vsl_power           integer,
    batting_ratings_vsl_babip           integer,
    batting_ratings_talent_contact      integer,
    batting_ratings_talent_gap          integer,
    batting_ratings_talent_eye          integer,
    batting_ratings_talent_strikeouts   integer,
    batting_ratings_talent_hp           integer,
    batting_ratings_talent_power        integer,
    batting_ratings_talent_babip        integer,
    batting_ratings_misc_bunt           integer,
    batting_ratings_misc_bunt_for_hit   integer,
    batting_ratings_misc_gb_hitter_type integer,
    batting_ratings_misc_fb_hitter_type integer,
    running_ratings_speed               integer,
    running_ratings_stealing_rate       integer,
    running_ratings_stealing            integer,
    running_ratings_baserunning         integer
);

\copy players_batting FROM '/Users/brianmcneil/Library/Containers/com.ootpdevelopments.ootp26macqlm/Data/Application Support/Out of the Park Developments/OOTP Baseball 26/saved_games/WPOBL-test.lg/import_export/csv/players_batting.csv' DELIMITER ',' NULL AS 'NULL' CSV HEADER encoding 'UTF-8';

DELETE FROM player.player_batting WHERE player_id NOT IN (SELECT player_id FROM players_batting);

INSERT INTO player.player_batting(player_id, team_id, league_id, position_id, role_id, br_overall_contact, br_overall_gap, br_overall_eye, br_overall_strikeouts, br_overall_hp, br_overall_power, br_overall_babip, br_vsr_contact, br_vsr_gap, br_vsr_eye, br_vsr_strikeouts, br_vsr_hp, br_vsr_power, br_vsr_babip, br_vsl_contact, br_vsl_gap, br_vsl_eye, br_vsl_strikeouts, br_vsl_hp, br_vsl_power, br_vsl_babip, br_talent_contact, br_talent_gap, br_talent_eye, br_talent_strikeouts, br_talent_hp, br_talent_power, br_talent_babip, br_misc_bunt, br_misc_bunt_for_hit, gb_hitter_type_id, fb_hitter_type_id,rr_stealing_rate,rr_stealing,rr_base_running,rr_speed)
SELECT
    player_id,
    CASE WHEN team_id > 0 THEN team_id END,
    CASE WHEN league_id > 0 THEN league_id END,
    position,
    CASE WHEN role > 0 THEN role END,
    batting_ratings_overall_contact,
    batting_ratings_overall_gap,
    batting_ratings_overall_eye,
    batting_ratings_overall_strikeouts,
    batting_ratings_overall_hp,
    batting_ratings_overall_power,
    batting_ratings_overall_babip,
    batting_ratings_vsr_contact,
    batting_ratings_vsr_gap,
    batting_ratings_vsr_eye,
    batting_ratings_vsr_strikeouts,
    batting_ratings_vsr_hp,
    batting_ratings_vsr_power,
    batting_ratings_vsr_babip,
    batting_ratings_vsl_contact,
    batting_ratings_vsl_gap,
    batting_ratings_vsl_eye,
    batting_ratings_vsl_strikeouts,
    batting_ratings_vsl_hp,
    batting_ratings_vsl_power,
    batting_ratings_vsl_babip,
    batting_ratings_talent_contact,
    batting_ratings_talent_gap,
    batting_ratings_talent_eye,
    batting_ratings_talent_strikeouts,
    batting_ratings_talent_hp,
    batting_ratings_talent_power,
    batting_ratings_talent_babip,
    batting_ratings_misc_bunt,
    batting_ratings_misc_bunt_for_hit,
    batting_ratings_misc_gb_hitter_type,
    batting_ratings_misc_fb_hitter_type,
    running_ratings_stealing_rate,
    running_ratings_stealing,
    running_ratings_baserunning,
    running_ratings_speed
FROM players_batting b
WHERE b.player_id IN (SELECT player_id FROM player.player)
EXCEPT SELECT player_id, team_id, league_id, position_id, role_id, br_overall_contact, br_overall_gap, br_overall_eye, br_overall_strikeouts, br_overall_hp, br_overall_power, br_overall_babip, br_vsr_contact, br_vsr_gap, br_vsr_eye, br_vsr_strikeouts, br_vsr_hp, br_vsr_power, br_vsr_babip, br_vsl_contact, br_vsl_gap, br_vsl_eye, br_vsl_strikeouts, br_vsl_hp, br_vsl_power, br_vsl_babip, br_talent_contact, br_talent_gap, br_talent_eye, br_talent_strikeouts, br_talent_hp, br_talent_power, br_talent_babip, br_misc_bunt, br_misc_bunt_for_hit, gb_hitter_type_id, fb_hitter_type_id,rr_stealing_rate,rr_stealing,rr_base_running,rr_speed
FROM player.player_batting
ON CONFLICT (player_id) DO UPDATE
    SET
        team_id = EXCLUDED.team_id ,
        league_id = EXCLUDED.league_id ,
        position_id = EXCLUDED.position_id ,
        role_id = EXCLUDED.role_id ,
        br_overall_contact = EXCLUDED.br_overall_contact ,
        br_overall_gap = EXCLUDED.br_overall_gap ,
        br_overall_eye = EXCLUDED.br_overall_eye ,
        br_overall_strikeouts = EXCLUDED.br_overall_strikeouts ,
        br_overall_hp = EXCLUDED.br_overall_hp ,
        br_overall_power = EXCLUDED.br_overall_power ,
        br_overall_babip = EXCLUDED.br_overall_babip ,
        br_vsr_contact = EXCLUDED.br_vsr_contact ,
        br_vsr_gap = EXCLUDED.br_vsr_gap ,
        br_vsr_eye = EXCLUDED.br_vsr_eye ,
        br_vsr_strikeouts = EXCLUDED.br_vsr_strikeouts ,
        br_vsr_hp = EXCLUDED.br_vsr_hp ,
        br_vsr_power = EXCLUDED.br_vsr_power ,
        br_vsr_babip = EXCLUDED.br_vsr_babip ,
        br_vsl_contact = EXCLUDED.br_vsl_contact ,
        br_vsl_gap = EXCLUDED.br_vsl_gap ,
        br_vsl_eye = EXCLUDED.br_vsl_eye ,
        br_vsl_strikeouts = EXCLUDED.br_vsl_strikeouts ,
        br_vsl_hp = EXCLUDED.br_vsl_hp ,
        br_vsl_power = EXCLUDED.br_vsl_power ,
        br_vsl_babip = EXCLUDED.br_vsl_babip ,
        br_talent_contact = EXCLUDED.br_talent_contact ,
        br_talent_gap = EXCLUDED.br_talent_gap ,
        br_talent_eye = EXCLUDED.br_talent_eye ,
        br_talent_strikeouts = EXCLUDED.br_talent_strikeouts ,
        br_talent_hp = EXCLUDED.br_talent_hp ,
        br_talent_power = EXCLUDED.br_talent_power ,
        br_talent_babip = EXCLUDED.br_talent_babip ,
        br_misc_bunt = EXCLUDED.br_misc_bunt ,
        br_misc_bunt_for_hit = EXCLUDED.br_misc_bunt_for_hit ,
        gb_hitter_type_id = EXCLUDED.gb_hitter_type_id ,
        fb_hitter_type_id = EXCLUDED.fb_hitter_type_id ,
        rr_stealing_rate = excluded.rr_stealing_rate,
        rr_stealing = excluded.rr_stealing,
        rr_base_running = excluded.rr_base_running,
        rr_speed = excluded.rr_speed,
        modified_by = CURRENT_USER,
        modified_ts = now()
    ;

create temporary table players_fielding
(
    player_id                        integer,
    team_id                          integer,
    league_id                        integer,
    position                         integer,
    role                             integer,
    fielding_ratings_infield_range   integer,
    fielding_ratings_infield_arm     integer,
    fielding_ratings_turn_doubleplay integer,
    fielding_ratings_outfield_range  integer,
    fielding_ratings_outfield_arm    integer,
    fielding_ratings_catcher_arm     integer,
    fielding_ratings_catcher_ability integer,
    fielding_ratings_catcher_framing integer,
    fielding_ratings_infield_error   integer,
    fielding_ratings_outfield_error  integer,
    fielding_experience0             integer,
    fielding_experience1             integer,
    fielding_experience2             integer,
    fielding_experience3             integer,
    fielding_experience4             integer,
    fielding_experience5             integer,
    fielding_experience6             integer,
    fielding_experience7             integer,
    fielding_experience8             integer,
    fielding_experience9             integer,
    fielding_rating_pos1             integer,
    fielding_rating_pos2             integer,
    fielding_rating_pos3             integer,
    fielding_rating_pos4             integer,
    fielding_rating_pos5             integer,
    fielding_rating_pos6             integer,
    fielding_rating_pos7             integer,
    fielding_rating_pos8             integer,
    fielding_rating_pos9             integer,
    fielding_rating_pos1_pot         integer,
    fielding_rating_pos2_pot         integer,
    fielding_rating_pos3_pot         integer,
    fielding_rating_pos4_pot         integer,
    fielding_rating_pos5_pot         integer,
    fielding_rating_pos6_pot         integer,
    fielding_rating_pos7_pot         integer,
    fielding_rating_pos8_pot         integer,
    fielding_rating_pos9_pot         integer
);

\copy players_fielding FROM '/Users/brianmcneil/Library/Containers/com.ootpdevelopments.ootp26macqlm/Data/Application Support/Out of the Park Developments/OOTP Baseball 26/saved_games/WPOBL-test.lg/import_export/csv/players_fielding.csv' DELIMITER ',' NULL AS 'NULL' CSV HEADER encoding 'UTF-8';

DELETE FROM player.player_fielding WHERE player_id NOT IN (SELECT player_id FROM players_fielding);

INSERT INTO player.player_fielding (player_id, team_id, league_id, position_id, role_id, fr_infield_range, fr_infield_arm, fr_turn_double_play, fr_outfield_range, fr_outfield_arm, fr_catcher_arm, fr_catcher_ability, fr_infield_error, fr_outfield_error, fr_fielding_experience, fr_fielding_rating, fr_catcher_framing, fr_fielding_potential)
SELECT
    player_id,
    CASE WHEN team_id > 0 THEN team_id END,
    CASE WHEN league_id > 0 THEN league_id END,
    position,
    CASE WHEN role > 0 THEN role END,
    fielding_ratings_infield_range,
    fielding_ratings_infield_arm,
    fielding_ratings_turn_doubleplay,
    fielding_ratings_outfield_range,
    fielding_ratings_outfield_arm,
    fielding_ratings_catcher_arm,
    fielding_ratings_catcher_ability,
    fielding_ratings_infield_error,
    fielding_ratings_outfield_error,
    ARRAY[fielding_experience1,
        fielding_experience2,
        fielding_experience3,
        fielding_experience4,
        fielding_experience5,
        fielding_experience6,
        fielding_experience7,
        fielding_experience8,
        fielding_experience9],
    ARRAY[fielding_rating_pos1,
        fielding_rating_pos2,
        fielding_rating_pos3,
        fielding_rating_pos4,
        fielding_rating_pos5,
        fielding_rating_pos6,
        fielding_rating_pos7,
        fielding_rating_pos8,
        fielding_rating_pos9],
    fielding_ratings_catcher_framing,
    ARRAY[fielding_rating_pos1_pot,
        fielding_rating_pos2_pot,
        fielding_rating_pos3_pot,
        fielding_rating_pos4_pot,
        fielding_rating_pos5_pot,
        fielding_rating_pos6_pot,
        fielding_rating_pos7_pot,
        fielding_rating_pos8_pot,
        fielding_rating_pos9_pot]

FROM players_fielding f
WHERE f.player_id IN (SELECT player_id FROM player.player)
EXCEPT SELECT player_id, team_id, league_id, position_id, role_id, fr_infield_range, fr_infield_arm, fr_turn_double_play, fr_outfield_range, fr_outfield_arm, fr_catcher_arm, fr_catcher_ability, fr_infield_error, fr_outfield_error, fr_fielding_experience, fr_fielding_rating, fr_catcher_framing, fr_fielding_potential
FROM player.player_fielding
ON CONFLICT (player_id) DO UPDATE
    SET
        team_id = EXCLUDED.team_id ,
        league_id = EXCLUDED.league_id ,
        position_id = EXCLUDED.position_id ,
        role_id = EXCLUDED.role_id ,
        fr_infield_range = EXCLUDED.fr_infield_range ,
        fr_infield_arm = EXCLUDED.fr_infield_arm ,
        fr_turn_double_play = EXCLUDED.fr_turn_double_play ,
        fr_outfield_range = EXCLUDED.fr_outfield_range ,
        fr_outfield_arm = EXCLUDED.fr_outfield_arm ,
        fr_catcher_arm = EXCLUDED.fr_catcher_arm ,
        fr_catcher_ability = EXCLUDED.fr_catcher_ability ,
        fr_infield_error = EXCLUDED.fr_infield_error ,
        fr_outfield_error = EXCLUDED.fr_outfield_error ,
        fr_fielding_experience = EXCLUDED.fr_fielding_experience ,
        fr_fielding_rating = excluded.fr_fielding_rating,
        fr_catcher_framing = excluded.fr_catcher_framing,
        fr_fielding_potential = excluded.fr_fielding_potential,
        modified_by = CURRENT_USER,
        modified_ts = now()
    ;

create temporary table players_value
(
    player_id              integer,
    team_id                integer,
    league_id              integer,
    position               integer,
    role                   integer,
    offensive_value        integer,
    offensive_value_talent integer,
    offensive_value_vsl    integer,
    offensive_value_vsr    integer,
    pitching_value         integer,
    pitching_value_talent  integer,
    pitching_value_vsl     integer,
    pitching_value_vsr     integer,
    overall_value          integer,
    talent_value           integer,
    career_value           integer,
    leadoff_value_vsl      integer,
    leadoff_value_vsr      integer,
    running_value          integer,
    stealing_value         integer,
    season_performance     double precision,
    stats_value_0          integer,
    stats_value_1          integer,
    stats_value_2          integer,
    stats_mod_0            integer,
    stats_mod_1            integer,
    stats_mod_2            integer,
    ratings_value          integer,
    overall_sp             integer,
    overall_rp             integer,
    overall_c              integer,
    overall_1b             integer,
    overall_2b             integer,
    overall_3b             integer,
    overall_ss             integer,
    overall_lf             integer,
    overall_cf             integer,
    overall_rf             integer,
    award_bat              double precision,
    award_pit              double precision,
    award_field            double precision,
    oa                     integer,
    pot                    integer,
    oa_rating              integer,
    pot_rating             integer
);

\copy players_value FROM '/Users/brianmcneil/Library/Containers/com.ootpdevelopments.ootp26macqlm/Data/Application Support/Out of the Park Developments/OOTP Baseball 26/saved_games/WPOBL-test.lg/import_export/csv/players_value.csv' DELIMITER ',' NULL AS 'NULL' CSV HEADER encoding 'UTF-8';

DELETE FROM player.player_value WHERE player_id NOT IN (SELECT player_id FROM players_value);

INSERT INTO player.player_value (player_id, team_id, league_id, position_id, role_id, v_offensive_value, v_offensive_value_talent, v_offensive_value_vsl, v_offensive_value_vsr, v_pitching_value, v_pitching_value_talent, v_pitching_value_vsl, v_pitching_value_vsr, v_overall_value, v_talent_value, v_career_value, v_lead_off_value_vsl, v_lead_off_value_vsr, v_running_value, v_stealing_value, v_season_performance, v_stats_value, v_stats_mod, v_ratings_value, v_overall_sp, v_overall_rp, v_overall_c, v_overall_1b, v_overall_2b, v_overall_3b, v_overall_ss, v_overall_lf, v_overall_cf, v_overall_rf, v_award_bat, v_award_pitch, v_award_field, v_overall, v_potential, v_overall_rating, v_potential_rating)
SELECT
    player_id,
    CASE WHEN team_id > 0 THEN team_id END,
    CASE WHEN league_id > 0 THEN league_id END,
    CASE WHEN position > 0 THEN position END,
    CASE WHEN role > 0 THEN role END,
    offensive_value,
    offensive_value_talent,
    offensive_value_vsl,
    offensive_value_vsr,
    pitching_value,
    pitching_value_talent,
    pitching_value_vsl,
    pitching_value_vsr,
    overall_value,
    talent_value,
    career_value,
    leadoff_value_vsl,
    leadoff_value_vsr,
    running_value,
    stealing_value,
    season_performance,
    ARRAY[stats_value_0,
        stats_value_1,
        stats_value_2],
    ARRAY[stats_mod_0,
        stats_mod_1,
        stats_mod_2],
    ratings_value,
    overall_sp,
    overall_rp,
    overall_c,
    overall_1b,
    overall_2b,
    overall_3b,
    overall_ss,
    overall_lf,
    overall_cf,
    overall_rf,
    award_bat,
    award_pit,
    award_field,
    oa,
    pot,
    pv.oa_rating,
    pv.pot_rating
FROM players_value pv
WHERE pv.player_id IN (SELECT player_id FROM player.player)
EXCEPT SELECT player_id, team_id, league_id, position_id, role_id, v_offensive_value, v_offensive_value_talent, v_offensive_value_vsl, v_offensive_value_vsr, v_pitching_value, v_pitching_value_talent, v_pitching_value_vsl, v_pitching_value_vsr, v_overall_value, v_talent_value, v_career_value, v_lead_off_value_vsl, v_lead_off_value_vsr, v_running_value, v_stealing_value, v_season_performance, v_stats_value, v_stats_mod, v_ratings_value, v_overall_sp, v_overall_rp, v_overall_c, v_overall_1b, v_overall_2b, v_overall_3b, v_overall_ss, v_overall_lf, v_overall_cf, v_overall_rf, v_award_bat, v_award_pitch, v_award_field, v_overall, v_potential, v_overall_rating, v_potential_rating
FROM player.player_value
ON CONFLICT (player_id) DO UPDATE
    SET
        team_id = EXCLUDED.team_id ,
        league_id = EXCLUDED.league_id ,
        position_id = EXCLUDED.position_id ,
        role_id = EXCLUDED.role_id ,
        v_offensive_value = EXCLUDED.v_offensive_value ,
        v_offensive_value_talent = EXCLUDED.v_offensive_value_talent ,
        v_offensive_value_vsl = EXCLUDED.v_offensive_value_vsl ,
        v_offensive_value_vsr = EXCLUDED.v_offensive_value_vsr ,
        v_pitching_value = EXCLUDED.v_pitching_value ,
        v_pitching_value_talent = EXCLUDED.v_pitching_value_talent ,
        v_pitching_value_vsl = EXCLUDED.v_pitching_value_vsl ,
        v_pitching_value_vsr = EXCLUDED.v_pitching_value_vsr ,
        v_overall_value = EXCLUDED.v_overall_value ,
        v_talent_value = EXCLUDED.v_talent_value ,
        v_career_value = EXCLUDED.v_career_value ,
        v_lead_off_value_vsl = EXCLUDED.v_lead_off_value_vsl ,
        v_lead_off_value_vsr = EXCLUDED.v_lead_off_value_vsr ,
        v_running_value = EXCLUDED.v_running_value ,
        v_stealing_value = EXCLUDED.v_stealing_value ,
        v_season_performance = EXCLUDED.v_season_performance ,
        v_stats_value = EXCLUDED.v_stats_value ,
        v_stats_mod = EXCLUDED.v_stats_mod ,
        v_ratings_value = EXCLUDED.v_ratings_value ,
        v_overall_sp = EXCLUDED.v_overall_sp ,
        v_overall_rp = EXCLUDED.v_overall_rp ,
        v_overall_c = EXCLUDED.v_overall_c ,
        v_overall_1b = EXCLUDED.v_overall_1b ,
        v_overall_2b = EXCLUDED.v_overall_2b ,
        v_overall_3b = EXCLUDED.v_overall_3b ,
        v_overall_ss = EXCLUDED.v_overall_ss ,
        v_overall_lf = EXCLUDED.v_overall_lf ,
        v_overall_cf = EXCLUDED.v_overall_cf ,
        v_overall_rf = EXCLUDED.v_overall_rf ,
        v_award_bat = EXCLUDED.v_award_bat ,
        v_award_pitch = EXCLUDED.v_award_pitch ,
        v_award_field = EXCLUDED.v_award_field ,
        v_overall = EXCLUDED.v_overall ,
        v_potential = EXCLUDED.v_potential,
        modified_by = CURRENT_USER,
        modified_ts = now(),
        v_overall_rating = EXCLUDED.v_overall_rating,
        v_potential_rating = excluded.v_potential_rating
    ;

create temporary table players_pitching
(
    player_id                                    integer,
    team_id                                      integer,
    league_id                                    integer,
    position                                     integer,
    role                                         integer,
    pitching_ratings_overall_stuff               integer,
    pitching_ratings_overall_movement            integer,
    pitching_ratings_overall_hra                 integer,
    pitching_ratings_overall_pbabip              integer,
    pitching_ratings_overall_control             integer,
    pitching_ratings_overall_balk                integer,
    pitching_ratings_overall_hp                  integer,
    pitching_ratings_overall_wild_pitch          integer,
    pitching_ratings_vsr_stuff                   integer,
    pitching_ratings_vsr_movement                integer,
    pitching_ratings_vsr_hra                     integer,
    pitching_ratings_vsr_pbabip                  integer,
    pitching_ratings_vsr_control                 integer,
    pitching_ratings_vsr_balk                    integer,
    pitching_ratings_vsr_hp                      integer,
    pitching_ratings_vsr_wild_pitch              integer,
    pitching_ratings_vsl_stuff                   integer,
    pitching_ratings_vsl_movement                integer,
    pitching_ratings_vsl_hra                     integer,
    pitching_ratings_vsl_pbabip                  integer,
    pitching_ratings_vsl_control                 integer,
    pitching_ratings_vsl_balk                    integer,
    pitching_ratings_vsl_hp                      integer,
    pitching_ratings_vsl_wild_pitch              integer,
    pitching_ratings_talent_stuff                integer,
    pitching_ratings_talent_movement             integer,
    pitching_ratings_talent_hra                  integer,
    pitching_ratings_talent_pbabip               integer,
    pitching_ratings_talent_control              integer,
    pitching_ratings_talent_balk                 integer,
    pitching_ratings_talent_hp                   integer,
    pitching_ratings_talent_wild_pitch           integer,
    pitching_ratings_pitches_fastball            integer,
    pitching_ratings_pitches_slider              integer,
    pitching_ratings_pitches_curveball           integer,
    pitching_ratings_pitches_screwball           integer,
    pitching_ratings_pitches_forkball            integer,
    pitching_ratings_pitches_changeup            integer,
    pitching_ratings_pitches_sinker              integer,
    pitching_ratings_pitches_splitter            integer,
    pitching_ratings_pitches_knuckleball         integer,
    pitching_ratings_pitches_cutter              integer,
    pitching_ratings_pitches_circlechange        integer,
    pitching_ratings_pitches_knucklecurve        integer,
    pitching_ratings_pitches_talent_fastball     integer,
    pitching_ratings_pitches_talent_slider       integer,
    pitching_ratings_pitches_talent_curveball    integer,
    pitching_ratings_pitches_talent_screwball    integer,
    pitching_ratings_pitches_talent_forkball     integer,
    pitching_ratings_pitches_talent_changeup     integer,
    pitching_ratings_pitches_talent_sinker       integer,
    pitching_ratings_pitches_talent_splitter     integer,
    pitching_ratings_pitches_talent_knuckleball  integer,
    pitching_ratings_pitches_talent_cutter       integer,
    pitching_ratings_pitches_talent_circlechange integer,
    pitching_ratings_pitches_talent_knucklecurve integer,
    pitching_ratings_misc_velocity               integer,
    pitching_ratings_misc_velocity_target        integer,
    pitching_ratings_misc_arm_slot               integer,
    pitching_ratings_misc_stamina                integer,
    pitching_ratings_misc_ground_fly             integer,
    pitching_ratings_misc_hold                   integer
);

\copy players_pitching FROM '/Users/brianmcneil/Library/Containers/com.ootpdevelopments.ootp26macqlm/Data/Application Support/Out of the Park Developments/OOTP Baseball 26/saved_games/WPOBL-test.lg/import_export/csv/players_pitching.csv' DELIMITER ',' NULL AS 'NULL' CSV HEADER encoding 'UTF-8';

DELETE FROM player.player_pitching WHERE player_id NOT IN (SELECT player_id FROM players_pitching);

INSERT INTO player.player_pitching (player_id, team_id, league_id, position_id, role_id, pr_overall_stuff, pr_overall_control, pr_overall_movement, pr_overall_hr_allowed, pr_overall_babip,pr_overall_balk, pr_overall_hp, pr_overall_wild_pitch, pr_vsr_stuff, pr_vsr_control, pr_vsr_movement, pr_vsr_hr_allowed, pr_vsr_babip, pr_vsr_balk, pr_vsr_hp, pr_vsr_wild_pitch, pr_vsl_stuff, pr_vsl_control, pr_vsl_movement, pr_vsl_hr_allowed, pr_vsl_babip, pr_vsl_balk, pr_vsl_hp, pr_vsl_wild_pitch, pr_talent_stuff, pr_talent_control, pr_talent_movement, pr_talent_hr_allowed, pr_talent_babip, pr_talent_balk, pr_talent_hp, pr_talent_wild_pitch, pr_pitches_fastball, pr_pitches_slider, pr_pitches_curve_ball, pr_pitches_screw_ball, pr_pitches_fork_ball, pr_pitches_change_up, pr_pitches_sinker, pr_pitches_splitter, pr_pitches_knuckle_ball, pr_pitches_cutter, pr_pitches_circle_change, pr_pitches_knuckle_curve, pr_pitches_talent_fastball, pr_pitches_talent_slider, pr_pitches_talent_curve_ball, pr_pitches_talent_screwball, pr_pitches_talent_fork_ball, pr_pitches_talent_change_up, pr_pitches_talent_sinker, pr_pitches_talent_splitter, pr_pitches_talent_knuckle_ball, pr_pitches_talent_cutter, pr_pitches_talent_circle_change, pr_pitches_talent_knuckle_curve, velocity_id, arm_slot_id, pr_misc_stamina, pr_misc_ground_fly, pr_misc_hold)
SELECT
    player_id,
    CASE WHEN team_id > 0 THEN team_id END,
    CASE WHEN league_id > 0 THEN league_id END,
    CASE WHEN position > 0 THEN position END,
    CASE WHEN role > 0 THEN role END,
    pitching_ratings_overall_stuff,
    pitching_ratings_overall_control,
    pitching_ratings_overall_movement,
    pitching_ratings_overall_hra,
    pitching_ratings_overall_pbabip,
    pitching_ratings_overall_balk,
    pitching_ratings_overall_hp,
    pitching_ratings_overall_wild_pitch,
    pitching_ratings_vsr_stuff,
    pitching_ratings_vsr_control,
    pitching_ratings_vsr_movement,
    pitching_ratings_vsr_hra,
    pitching_ratings_vsr_pbabip,
    pitching_ratings_vsr_balk,
    pitching_ratings_vsr_hp,
    pitching_ratings_vsr_wild_pitch,
    pitching_ratings_vsl_stuff,
    pitching_ratings_vsl_control,
    pitching_ratings_vsl_movement,
    pitching_ratings_vsl_hra,
    pitching_ratings_vsl_pbabip,
    pitching_ratings_vsl_balk,
    pitching_ratings_vsl_hp,
    pitching_ratings_vsl_wild_pitch,
    pitching_ratings_talent_stuff,
    pitching_ratings_talent_control,
    pitching_ratings_talent_movement,
    pitching_ratings_talent_hra,
    pitching_ratings_talent_pbabip,
    pitching_ratings_talent_balk,
    pitching_ratings_talent_hp,
    pitching_ratings_talent_wild_pitch,
    pitching_ratings_pitches_fastball,
    pitching_ratings_pitches_slider,
    pitching_ratings_pitches_curveball,
    pitching_ratings_pitches_screwball,
    pitching_ratings_pitches_forkball,
    pitching_ratings_pitches_changeup,
    pitching_ratings_pitches_sinker,
    pitching_ratings_pitches_splitter,
    pitching_ratings_pitches_knuckleball,
    pitching_ratings_pitches_cutter,
    pitching_ratings_pitches_circlechange,
    pitching_ratings_pitches_knucklecurve,
    pitching_ratings_pitches_talent_fastball,
    pitching_ratings_pitches_talent_slider,
    pitching_ratings_pitches_talent_curveball,
    pitching_ratings_pitches_talent_screwball,
    pitching_ratings_pitches_talent_forkball,
    pitching_ratings_pitches_talent_changeup,
    pitching_ratings_pitches_talent_sinker,
    pitching_ratings_pitches_talent_splitter,
    pitching_ratings_pitches_talent_knuckleball,
    pitching_ratings_pitches_talent_cutter,
    pitching_ratings_pitches_talent_circlechange,
    pitching_ratings_pitches_talent_knucklecurve,
    pitching_ratings_misc_velocity,
    pitching_ratings_misc_arm_slot,
    pitching_ratings_misc_stamina,
    pitching_ratings_misc_ground_fly,
    pitching_ratings_misc_hold
FROM players_pitching pp
WHERE pp.player_id IN (SELECT player_id FROM player.player)
EXCEPT SELECT player_id, team_id, league_id, position_id, role_id, pr_overall_stuff, pr_overall_control, pr_overall_movement, pr_overall_hr_allowed, pr_overall_babip,pr_overall_balk, pr_overall_hp, pr_overall_wild_pitch, pr_vsr_stuff, pr_vsr_control, pr_vsr_movement, pr_vsr_hr_allowed, pr_vsr_babip, pr_vsr_balk, pr_vsr_hp, pr_vsr_wild_pitch, pr_vsl_stuff, pr_vsl_control, pr_vsl_movement, pr_vsl_hr_allowed, pr_vsl_babip, pr_vsl_balk, pr_vsl_hp, pr_vsl_wild_pitch, pr_talent_stuff, pr_talent_control, pr_talent_movement, pr_talent_hr_allowed, pr_talent_babip, pr_talent_balk, pr_talent_hp, pr_talent_wild_pitch, pr_pitches_fastball, pr_pitches_slider, pr_pitches_curve_ball, pr_pitches_screw_ball, pr_pitches_fork_ball, pr_pitches_change_up, pr_pitches_sinker, pr_pitches_splitter, pr_pitches_knuckle_ball, pr_pitches_cutter, pr_pitches_circle_change, pr_pitches_knuckle_curve, pr_pitches_talent_fastball, pr_pitches_talent_slider, pr_pitches_talent_curve_ball, pr_pitches_talent_screwball, pr_pitches_talent_fork_ball, pr_pitches_talent_change_up, pr_pitches_talent_sinker, pr_pitches_talent_splitter, pr_pitches_talent_knuckle_ball, pr_pitches_talent_cutter, pr_pitches_talent_circle_change, pr_pitches_talent_knuckle_curve, velocity_id, arm_slot_id, pr_misc_stamina, pr_misc_ground_fly, pr_misc_hold
FROM player.player_pitching
ON CONFLICT (player_id) DO UPDATE
    SET
        team_id = EXCLUDED.team_id ,
        league_id = EXCLUDED.league_id ,
        position_id = EXCLUDED.position_id ,
        role_id = EXCLUDED.role_id ,
        pr_overall_stuff = EXCLUDED.pr_overall_stuff ,
        pr_overall_control = EXCLUDED.pr_overall_control ,
        pr_overall_movement = EXCLUDED.pr_overall_movement ,
        pr_overall_hr_allowed = EXCLUDED.pr_overall_hr_allowed ,
        pr_overall_babip = EXCLUDED.pr_overall_babip ,
        pr_overall_balk = EXCLUDED.pr_overall_balk ,
        pr_overall_hp = EXCLUDED.pr_overall_hp ,
        pr_overall_wild_pitch = EXCLUDED.pr_overall_wild_pitch ,
        pr_vsr_stuff = EXCLUDED.pr_vsr_stuff ,
        pr_vsr_control = EXCLUDED.pr_vsr_control ,
        pr_vsr_movement = EXCLUDED.pr_vsr_movement ,
        pr_vsr_hr_allowed = EXCLUDED.pr_vsr_hr_allowed ,
        pr_vsr_babip = EXCLUDED.pr_vsr_babip ,
        pr_vsr_balk = EXCLUDED.pr_vsr_balk ,
        pr_vsr_hp = EXCLUDED.pr_vsr_hp ,
        pr_vsr_wild_pitch = EXCLUDED.pr_vsr_wild_pitch ,
        pr_vsl_stuff = EXCLUDED.pr_vsl_stuff ,
        pr_vsl_control = EXCLUDED.pr_vsl_control ,
        pr_vsl_movement = EXCLUDED.pr_vsl_movement ,
        pr_vsl_hr_allowed = EXCLUDED.pr_vsl_hr_allowed ,
        pr_vsl_babip = EXCLUDED.pr_vsl_babip ,
        pr_vsl_balk = EXCLUDED.pr_vsl_balk ,
        pr_vsl_hp = EXCLUDED.pr_vsl_hp ,
        pr_vsl_wild_pitch = EXCLUDED.pr_vsl_wild_pitch ,
        pr_talent_stuff = EXCLUDED.pr_talent_stuff ,
        pr_talent_control = EXCLUDED.pr_talent_control ,
        pr_talent_movement = EXCLUDED.pr_talent_movement ,
        pr_talent_hr_allowed = EXCLUDED.pr_talent_hr_allowed ,
        pr_talent_babip = EXCLUDED.pr_talent_babip ,
        pr_talent_balk = EXCLUDED.pr_talent_balk ,
        pr_talent_hp = EXCLUDED.pr_talent_hp ,
        pr_talent_wild_pitch = EXCLUDED.pr_talent_wild_pitch ,
        pr_pitches_fastball = EXCLUDED.pr_pitches_fastball ,
        pr_pitches_slider = EXCLUDED.pr_pitches_slider ,
        pr_pitches_curve_ball = EXCLUDED.pr_pitches_curve_ball ,
        pr_pitches_screw_ball = EXCLUDED.pr_pitches_screw_ball ,
        pr_pitches_fork_ball = EXCLUDED.pr_pitches_fork_ball ,
        pr_pitches_change_up = EXCLUDED.pr_pitches_change_up ,
        pr_pitches_sinker = EXCLUDED.pr_pitches_sinker ,
        pr_pitches_splitter = EXCLUDED.pr_pitches_splitter ,
        pr_pitches_knuckle_ball = EXCLUDED.pr_pitches_knuckle_ball ,
        pr_pitches_cutter = EXCLUDED.pr_pitches_cutter ,
        pr_pitches_circle_change = EXCLUDED.pr_pitches_circle_change ,
        pr_pitches_knuckle_curve = EXCLUDED.pr_pitches_knuckle_curve ,
        pr_pitches_talent_fastball = EXCLUDED.pr_pitches_talent_fastball ,
        pr_pitches_talent_slider = EXCLUDED.pr_pitches_talent_slider ,
        pr_pitches_talent_curve_ball = EXCLUDED.pr_pitches_talent_curve_ball ,
        pr_pitches_talent_screwball = EXCLUDED.pr_pitches_talent_screwball ,
        pr_pitches_talent_fork_ball = EXCLUDED.pr_pitches_talent_fork_ball ,
        pr_pitches_talent_change_up = EXCLUDED.pr_pitches_talent_change_up ,
        pr_pitches_talent_sinker = EXCLUDED.pr_pitches_talent_sinker ,
        pr_pitches_talent_splitter = EXCLUDED.pr_pitches_talent_splitter ,
        pr_pitches_talent_knuckle_ball = EXCLUDED.pr_pitches_talent_knuckle_ball ,
        pr_pitches_talent_cutter = EXCLUDED.pr_pitches_talent_cutter ,
        pr_pitches_talent_circle_change = EXCLUDED.pr_pitches_talent_circle_change ,
        pr_pitches_talent_knuckle_curve = EXCLUDED.pr_pitches_talent_knuckle_curve ,
        velocity_id = EXCLUDED.velocity_id ,
        arm_slot_id = EXCLUDED.arm_slot_id ,
        pr_misc_stamina = EXCLUDED.pr_misc_stamina ,
        pr_misc_ground_fly = EXCLUDED.pr_misc_ground_fly ,
        pr_misc_hold = EXCLUDED.pr_misc_hold,
        modified_by = CURRENT_USER,
        modified_ts = now()
    ;

create temporary table players_awards
(
    player_id     integer,
    league_id     integer,
    team_id       integer,
    sub_league_id integer,
    award_id      integer,
    year          integer,
    season        integer,
    position      integer,
    day           integer,
    month         integer,
    finish        integer
);

\copy players_awards FROM '/Users/brianmcneil/Library/Containers/com.ootpdevelopments.ootp26macqlm/Data/Application Support/Out of the Park Developments/OOTP Baseball 26/saved_games/WPOBL-test.lg/import_export/csv/players_awards.csv' DELIMITER ',' NULL AS 'NULL' CSV HEADER encoding 'UTF-8';

INSERT INTO player.player_award_season (player_id, league_id, team_id, sub_league_id, award_id, season, position_id, award_date, finish_order)
SELECT
    player_id,
    pa.league_id,
    CASE WHEN team_id > 0 THEN team_id END,
    sub_league_id,
    CASE WHEN award_id = 9 and team_id = 0 and l.league_id = 203 then 99 else award_id end,
    season,
    position,
    to_date(concat_ws('-',day,month,year),'DD-MM-YYYY'),
    finish
FROM players_awards pa JOIN leagues l on pa.league_id = l.league_id and pa.season = l.season_year
EXCEPT
SELECT player_id, pah.league_id, team_id, sub_league_id, award_id, season, position_id, award_date, finish_order
FROM player.player_award_season pah JOIN leagues l on pah.league_id = l.league_id and pah.season = l.season_year
ON CONFLICT (player_id, league_id, sub_league_id, award_id, season, award_date, position_id) DO UPDATE
    SET
        finish_order = EXCLUDED.finish_order,
        modified_by = CURRENT_USER,
        modified_ts = NOW()
    ;
    
create temporary table players_scouted_ratings
(
    player_id                                    integer,
    team_id                                      integer,
    league_id                                    integer,
    position                                     integer,
    role                                         integer,
    scouting_coach_id                            integer,
    scouting_team_id                             integer,
    running_ratings_speed                        integer,
    running_ratings_stealing_rate                integer,
    running_ratings_stealing                     integer,
    running_ratings_baserunning                  integer,
    batting_ratings_overall_contact              integer,
    batting_ratings_overall_gap                  integer,
    batting_ratings_overall_eye                  integer,
    batting_ratings_overall_strikeouts           integer,
    batting_ratings_overall_hp                   integer,
    batting_ratings_overall_power                integer,
    batting_ratings_overall_babip                integer,
    batting_ratings_vsr_contact                  integer,
    batting_ratings_vsr_gap                      integer,
    batting_ratings_vsr_eye                      integer,
    batting_ratings_vsr_strikeouts               integer,
    batting_ratings_vsr_hp                       integer,
    batting_ratings_vsr_power                    integer,
    batting_ratings_vsr_babip                    integer,
    batting_ratings_vsl_contact                  integer,
    batting_ratings_vsl_gap                      integer,
    batting_ratings_vsl_eye                      integer,
    batting_ratings_vsl_strikeouts               integer,
    batting_ratings_vsl_hp                       integer,
    batting_ratings_vsl_power                    integer,
    batting_ratings_vsl_babip                    integer,
    batting_ratings_talent_contact               integer,
    batting_ratings_talent_gap                   integer,
    batting_ratings_talent_eye                   integer,
    batting_ratings_talent_strikeouts            integer,
    batting_ratings_talent_hp                    integer,
    batting_ratings_talent_power                 integer,
    batting_ratings_talent_babip                 integer,
    batting_ratings_misc_bunt                    integer,
    batting_ratings_misc_bunt_for_hit            integer,
    batting_ratings_misc_gb_hitter_type          integer,
    batting_ratings_misc_fb_hitter_type          integer,
    pitching_ratings_overall_stuff               integer,
    pitching_ratings_overall_movement            integer,
    pitching_ratings_overall_hra                 integer,
    pitching_ratings_overall_control             integer,
    pitching_ratings_overall_pbabip              integer,
    pitching_ratings_overall_balk                integer,
    pitching_ratings_overall_hp                  integer,
    pitching_ratings_overall_wild_pitch          integer,
    pitching_ratings_vsr_stuff                   integer,
    pitching_ratings_vsr_movement                integer,
    pitching_ratings_vsr_hra                     integer,
    pitching_ratings_vsr_control                 integer,
    pitching_ratings_vsr_pbabip                  integer,
    pitching_ratings_vsr_balk                    integer,
    pitching_ratings_vsr_hp                      integer,
    pitching_ratings_vsr_wild_pitch              integer,
    pitching_ratings_vsl_stuff                   integer,
    pitching_ratings_vsl_movement                integer,
    pitching_ratings_vsl_hra                     integer,
    pitching_ratings_vsl_control                 integer,
    pitching_ratings_vsl_pbabip                  integer,
    pitching_ratings_vsl_balk                    integer,
    pitching_ratings_vsl_hp                      integer,
    pitching_ratings_vsl_wild_pitch              integer,
    pitching_ratings_talent_stuff                integer,
    pitching_ratings_talent_movement             integer,
    pitching_ratings_talent_hra                  integer,
    pitching_ratings_talent_control              integer,
    pitching_ratings_talent_pbabip               integer,
    pitching_ratings_talent_balk                 integer,
    pitching_ratings_talent_hp                   integer,
    pitching_ratings_talent_wild_pitch           integer,
    pitching_ratings_pitches_fastball            integer,
    pitching_ratings_pitches_slider              integer,
    pitching_ratings_pitches_curveball           integer,
    pitching_ratings_pitches_screwball           integer,
    pitching_ratings_pitches_forkball            integer,
    pitching_ratings_pitches_changeup            integer,
    pitching_ratings_pitches_sinker              integer,
    pitching_ratings_pitches_splitter            integer,
    pitching_ratings_pitches_knuckleball         integer,
    pitching_ratings_pitches_cutter              integer,
    pitching_ratings_pitches_circlechange        integer,
    pitching_ratings_pitches_knucklecurve        integer,
    pitching_ratings_pitches_talent_fastball     integer,
    pitching_ratings_pitches_talent_slider       integer,
    pitching_ratings_pitches_talent_curveball    integer,
    pitching_ratings_pitches_talent_screwball    integer,
    pitching_ratings_pitches_talent_forkball     integer,
    pitching_ratings_pitches_talent_changeup     integer,
    pitching_ratings_pitches_talent_sinker       integer,
    pitching_ratings_pitches_talent_splitter     integer,
    pitching_ratings_pitches_talent_knuckleball  integer,
    pitching_ratings_pitches_talent_cutter       integer,
    pitching_ratings_pitches_talent_circlechange integer,
    pitching_ratings_pitches_talent_knucklecurve integer,
    pitching_ratings_misc_velocity               integer,
    pitching_ratings_misc_velocity_target        integer,
    pitching_ratings_misc_arm_slot               integer,
    pitching_ratings_misc_stamina                integer,
    pitching_ratings_misc_ground_fly             integer,
    pitching_ratings_misc_hold                   integer,
    pitching_ratings_babip                       integer,
    fielding_ratings_infield_range               integer,
    fielding_ratings_infield_arm                 integer,
    fielding_ratings_turn_doubleplay             integer,
    fielding_ratings_outfield_range              integer,
    fielding_ratings_outfield_arm                integer,
    fielding_ratings_catcher_arm                 integer,
    fielding_ratings_catcher_ability             integer,
    fielding_ratings_catcher_framing             integer,
    fielding_ratings_infield_error               integer,
    fielding_ratings_outfield_error              integer,
    fielding_rating_pos1                         integer,
    fielding_rating_pos2                         integer,
    fielding_rating_pos3                         integer,
    fielding_rating_pos4                         integer,
    fielding_rating_pos5                         integer,
    fielding_rating_pos6                         integer,
    fielding_rating_pos7                         integer,
    fielding_rating_pos8                         integer,
    fielding_rating_pos9                         integer,
    fielding_rating_pos1_pot                     integer,
    fielding_rating_pos2_pot                     integer,
    fielding_rating_pos3_pot                     integer,
    fielding_rating_pos4_pot                     integer,
    fielding_rating_pos5_pot                     integer,
    fielding_rating_pos6_pot                     integer,
    fielding_rating_pos7_pot                     integer,
    fielding_rating_pos8_pot                     integer,
    fielding_rating_pos9_pot                     integer,
    overall                                      integer,
    talent                                       integer,
    overall_rating                               integer,
    talent_rating                                integer,
    scouting_accuracy                            integer
);

\copy players_scouted_ratings FROM '/Users/brianmcneil/Library/Containers/com.ootpdevelopments.ootp26macqlm/Data/Application Support/Out of the Park Developments/OOTP Baseball 26/saved_games/WPOBL-test.lg/import_export/csv/players_scouted_ratings.csv' DELIMITER ',' NULL AS 'NULL' CSV HEADER encoding 'UTF-8';

DELETE FROM player.player_scouted_ratings WHERE (player_id,scouting_coach_id) NOT IN (SELECT DISTINCT player_id, scouting_coach_id FROM players_scouted_ratings);

INSERT INTO player.player_scouted_ratings(player_id, team_id, league_id, position_id, role_id, scouting_coach_id, scouting_team_id, rr_speed, rr_stealing_rate, rr_stealing, rr_base_running, br_overall_contact, br_overall_gap, br_overall_eye, br_overall_strikeouts, br_overall_hp, br_overall_power, br_overall_babip, br_vsr_contact, br_vsr_gap, br_vsr_eye, br_vsr_strikeouts, br_vsr_hp, br_vsr_power, br_vsr_babip, br_vsl_contact, br_vsl_gap, br_vsl_eye, br_vsl_strikeouts, br_vsl_hp, br_vsl_power, br_vsl_babip, br_talent_contact, br_talent_gap, br_talent_eye, br_talent_strikeouts, br_talent_hp, br_talent_power, br_talent_babip, br_misc_bunt, br_misc_bunt_for_hit, gb_hitter_type_id, fb_hitter_type_id, pr_overall_stuff, pr_overall_movement, pr_overall_hr_allowed, pr_overall_control, pr_overall_babip, pr_overall_balk, pr_overall_hp, pr_overall_wild_pitch, pr_vsr_stuff, pr_vsr_movement, pr_vsr_hr_allowed, pr_vsr_control, pr_vsr_babip, pr_vsr_balk, pr_vsr_hp, pr_vsr_wild_pitch, pr_vsl_stuff, pr_vsl_movement, pr_vsl_hr_allowed, pr_vsl_control, pr_vsl_babip, pr_vsl_balk, pr_vsl_hp, pr_vsl_wild_pitch, pr_talent_stuff, pr_talent_movement, pr_talent_hr_allowed, pr_talent_control, pr_talent_babip, pr_talent_balk, pr_talent_hp, pr_talent_wild_pitch, pr_pitches_fastball, pr_pitches_slider, pr_pitches_curve_ball, pr_pitches_screwball, pr_pitches_fork_ball, pr_pitches_change_up, pr_pitches_sinker, pr_pitches_splitter, pr_pitches_knuckle_ball, pr_pitches_cutter, pr_pitches_circle_change, pr_pitches_knuckle_curve, pr_pitches_talent_fastball, pr_pitches_talent_slider, pr_pitches_talent_curve_ball, pr_pitches_talent_screw_ball, pr_pitches_talent_fork_ball, pr_pitches_talent_change_up, pr_pitches_talent_sinker, pr_pitches_talent_splitter, pr_pitches_talent_knuckle_ball, pr_pitches_talent_cutter, pr_pitches_talent_circle_change, pr_pitches_talent_knuckle_curve, velocity_id, arm_slot_id, pr_misc_stamina, pr_misc_ground_fly, pr_misc_hold, fr_infield_range, fr_infield_arm, fr_turn_double_play, fr_outfield_range, fr_outfield_arm, fr_catcher_arm, fr_catcher_ability, fr_catcher_framing, fr_infield_error, fr_outfield_error, fielding_rating_pos, fielding_potential_pos, overall_rating, talent_rating, scouting_accuracy_id, overall, talent)
select psr.player_id,
    CASE WHEN psr.team_id >= 0 THEN psr.team_id END ,
    CASE WHEN psr.league_id > 0 THEN psr.league_id END,
    psr.position,
    CASE WHEN psr.role > 0 THEN psr.role END,
    scouting_coach_id,
    scouting_team_id,
    running_ratings_speed,
    running_ratings_stealing_rate,
    running_ratings_stealing,
    running_ratings_baserunning,
    batting_ratings_overall_contact,
    batting_ratings_overall_gap,
    batting_ratings_overall_eye,
    batting_ratings_overall_strikeouts,
    batting_ratings_overall_hp,
    batting_ratings_overall_power,
    batting_ratings_overall_babip,
    batting_ratings_vsr_contact,
    batting_ratings_vsr_gap,
    batting_ratings_vsr_eye,
    batting_ratings_vsr_strikeouts,
    batting_ratings_vsr_hp,
    batting_ratings_vsr_power,
    batting_ratings_vsr_babip,
    batting_ratings_vsl_contact,
    batting_ratings_vsl_gap,
    batting_ratings_vsl_eye,
    batting_ratings_vsl_strikeouts,
    batting_ratings_vsl_hp,
    batting_ratings_vsl_power,
    batting_ratings_vsl_babip,
    batting_ratings_talent_contact,
    batting_ratings_talent_gap,
    batting_ratings_talent_eye,
    batting_ratings_talent_strikeouts,
    batting_ratings_talent_hp,
    batting_ratings_talent_power,
    batting_ratings_talent_babip,
    batting_ratings_misc_bunt,
    batting_ratings_misc_bunt_for_hit,
    batting_ratings_misc_gb_hitter_type,
    batting_ratings_misc_fb_hitter_type,
    pitching_ratings_overall_stuff,
    pitching_ratings_overall_movement,
    pitching_ratings_overall_hra,
    pitching_ratings_overall_control,
    pitching_ratings_overall_pbabip,
    pitching_ratings_overall_balk,
    pitching_ratings_overall_hp,
    pitching_ratings_overall_wild_pitch,
    pitching_ratings_vsr_stuff,
    pitching_ratings_vsr_movement,
    pitching_ratings_vsr_hra,
    pitching_ratings_vsr_control,
    pitching_ratings_vsr_pbabip,
    pitching_ratings_vsr_balk,
    pitching_ratings_vsr_hp,
    pitching_ratings_vsr_wild_pitch,
    pitching_ratings_vsl_stuff,
    pitching_ratings_vsl_movement,
    pitching_ratings_vsl_hra,
    pitching_ratings_vsl_control,
    pitching_ratings_vsl_pbabip,
    pitching_ratings_vsl_balk,
    pitching_ratings_vsl_hp,
    pitching_ratings_vsl_wild_pitch,
    pitching_ratings_talent_stuff,
    pitching_ratings_talent_movement,
    pitching_ratings_talent_hra,
    pitching_ratings_talent_control,
    pitching_ratings_talent_pbabip,
    pitching_ratings_talent_balk,
    pitching_ratings_talent_hp,
    pitching_ratings_talent_wild_pitch,
    pitching_ratings_pitches_fastball,
    pitching_ratings_pitches_slider,
    pitching_ratings_pitches_curveball,
    pitching_ratings_pitches_screwball,
    pitching_ratings_pitches_forkball,
    pitching_ratings_pitches_changeup,
    pitching_ratings_pitches_sinker,
    pitching_ratings_pitches_splitter,
    pitching_ratings_pitches_knuckleball,
    pitching_ratings_pitches_cutter,
    pitching_ratings_pitches_circlechange,
    pitching_ratings_pitches_knucklecurve,
    pitching_ratings_pitches_talent_fastball,
    pitching_ratings_pitches_talent_slider,
    pitching_ratings_pitches_talent_curveball,
    pitching_ratings_pitches_talent_screwball,
    pitching_ratings_pitches_talent_forkball,
    pitching_ratings_pitches_talent_changeup,
    pitching_ratings_pitches_talent_sinker,
    pitching_ratings_pitches_talent_splitter,
    pitching_ratings_pitches_talent_knuckleball,
    pitching_ratings_pitches_talent_cutter,
    pitching_ratings_pitches_talent_circlechange,
    pitching_ratings_pitches_talent_knucklecurve,
    pitching_ratings_misc_velocity,
    pitching_ratings_misc_arm_slot,
    pitching_ratings_misc_stamina,
    pitching_ratings_misc_ground_fly,
    pitching_ratings_misc_hold,
--    pitching_ratings_babip,
    fielding_ratings_infield_range,
    fielding_ratings_infield_arm,
    fielding_ratings_turn_doubleplay,
    fielding_ratings_outfield_range,
    fielding_ratings_outfield_arm,
    fielding_ratings_catcher_arm,
    fielding_ratings_catcher_ability,
    fielding_ratings_catcher_framing,
    fielding_ratings_infield_error,
    fielding_ratings_outfield_error,
    ARRAY[fielding_rating_pos1,
        fielding_rating_pos2,
        fielding_rating_pos3,
        fielding_rating_pos4,
        fielding_rating_pos5,
        fielding_rating_pos6,
        fielding_rating_pos7,
        fielding_rating_pos8,
        fielding_rating_pos9],
    ARRAY[fielding_rating_pos1_pot,
        fielding_rating_pos2_pot,
        fielding_rating_pos3_pot,
        fielding_rating_pos4_pot,
        fielding_rating_pos5_pot,
        fielding_rating_pos6_pot,
        fielding_rating_pos7_pot,
        fielding_rating_pos8_pot,
        fielding_rating_pos9_pot],
    overall_rating,
    talent_rating,
    scouting_accuracy,
    psr.overall,
    psr.talent
FROM players_scouted_ratings psr JOIN players p ON psr.player_id = p.player_id
EXCEPT SELECT player_id, team_id, league_id, position_id, role_id, scouting_coach_id, scouting_team_id, rr_speed, rr_stealing_rate, rr_stealing, rr_base_running, br_overall_contact, br_overall_gap, br_overall_eye, br_overall_strikeouts, br_overall_hp, br_overall_power, br_overall_babip, br_vsr_contact, br_vsr_gap, br_vsr_eye, br_vsr_strikeouts, br_vsr_hp, br_vsr_power, br_vsr_babip, br_vsl_contact, br_vsl_gap, br_vsl_eye, br_vsl_strikeouts, br_vsl_hp, br_vsl_power, br_vsl_babip, br_talent_contact, br_talent_gap, br_talent_eye, br_talent_strikeouts, br_talent_hp, br_talent_power, br_talent_babip, br_misc_bunt, br_misc_bunt_for_hit, gb_hitter_type_id, fb_hitter_type_id, pr_overall_stuff, pr_overall_movement, pr_overall_hr_allowed, pr_overall_control, pr_overall_babip, pr_overall_balk, pr_overall_hp, pr_overall_wild_pitch, pr_vsr_stuff, pr_vsr_movement, pr_vsr_hr_allowed, pr_vsr_control, pr_vsr_babip, pr_vsr_balk, pr_vsr_hp, pr_vsr_wild_pitch, pr_vsl_stuff, pr_vsl_movement, pr_vsl_hr_allowed, pr_vsl_control, pr_vsl_babip, pr_vsl_balk, pr_vsl_hp, pr_vsl_wild_pitch, pr_talent_stuff, pr_talent_movement, pr_talent_hr_allowed, pr_talent_control, pr_talent_babip, pr_talent_balk, pr_talent_hp, pr_talent_wild_pitch, pr_pitches_fastball, pr_pitches_slider, pr_pitches_curve_ball, pr_pitches_screwball, pr_pitches_fork_ball, pr_pitches_change_up, pr_pitches_sinker, pr_pitches_splitter, pr_pitches_knuckle_ball, pr_pitches_cutter, pr_pitches_circle_change, pr_pitches_knuckle_curve, pr_pitches_talent_fastball, pr_pitches_talent_slider, pr_pitches_talent_curve_ball, pr_pitches_talent_screw_ball, pr_pitches_talent_fork_ball, pr_pitches_talent_change_up, pr_pitches_talent_sinker, pr_pitches_talent_splitter, pr_pitches_talent_knuckle_ball, pr_pitches_talent_cutter, pr_pitches_talent_circle_change, pr_pitches_talent_knuckle_curve, velocity_id, arm_slot_id, pr_misc_stamina, pr_misc_ground_fly, pr_misc_hold, fr_infield_range, fr_infield_arm, fr_turn_double_play, fr_outfield_range, fr_outfield_arm, fr_catcher_arm, fr_catcher_ability, fr_catcher_framing, fr_infield_error, fr_outfield_error, fielding_rating_pos, fielding_potential_pos, overall_rating, talent_rating, scouting_accuracy_id, overall, talent
FROM player.player_scouted_ratings
ON CONFLICT (player_id, scouting_coach_id, scouting_team_id) DO UPDATE
SET
team_id = EXCLUDED.team_id  ,
league_id = EXCLUDED.league_id  ,
position_id = EXCLUDED.position_id  ,
role_id = EXCLUDED.role_id  ,
rr_speed = EXCLUDED.rr_speed  ,
rr_stealing_rate = EXCLUDED.rr_stealing_rate  ,
rr_stealing = EXCLUDED.rr_stealing  ,
rr_base_running = EXCLUDED.rr_base_running  ,
br_overall_contact = EXCLUDED.br_overall_contact  ,
br_overall_gap = EXCLUDED.br_overall_gap  ,
br_overall_eye = EXCLUDED.br_overall_eye  ,
br_overall_strikeouts = EXCLUDED.br_overall_strikeouts  ,
br_overall_hp = EXCLUDED.br_overall_hp  ,
br_overall_power = EXCLUDED.br_overall_power  ,
br_overall_babip = EXCLUDED.br_overall_babip  ,
br_vsr_contact = EXCLUDED.br_vsr_contact  ,
br_vsr_gap = EXCLUDED.br_vsr_gap  ,
br_vsr_eye = EXCLUDED.br_vsr_eye  ,
br_vsr_strikeouts = EXCLUDED.br_vsr_strikeouts  ,
br_vsr_hp = EXCLUDED.br_vsr_hp  ,
br_vsr_power = EXCLUDED.br_vsr_power  ,
br_vsr_babip = EXCLUDED.br_vsr_babip  ,
br_vsl_contact = EXCLUDED.br_vsl_contact ,
br_vsl_gap = EXCLUDED.br_vsl_gap  ,
br_vsl_eye = EXCLUDED.br_vsl_eye  ,
br_vsl_strikeouts = EXCLUDED.br_vsl_strikeouts  ,
br_vsl_hp = EXCLUDED.br_vsl_hp  ,
br_vsl_power = EXCLUDED.br_vsl_power  ,
br_vsl_babip = EXCLUDED.br_vsl_babip  ,
br_talent_contact = EXCLUDED.br_talent_contact  ,
br_talent_gap = EXCLUDED.br_talent_gap  ,
br_talent_eye = EXCLUDED.br_talent_eye  ,
br_talent_strikeouts = EXCLUDED.br_talent_strikeouts  ,
br_talent_hp = EXCLUDED.br_talent_hp  ,
br_talent_power = EXCLUDED.br_talent_power  ,
br_talent_babip = EXCLUDED.br_talent_babip  ,
br_misc_bunt = EXCLUDED.br_misc_bunt  ,
br_misc_bunt_for_hit = EXCLUDED.br_misc_bunt_for_hit  ,
gb_hitter_type_id = EXCLUDED.gb_hitter_type_id  ,
fb_hitter_type_id = EXCLUDED.fb_hitter_type_id  ,
pr_overall_stuff = EXCLUDED.pr_overall_stuff  ,
pr_overall_control = EXCLUDED.pr_overall_control  ,
pr_overall_movement = EXCLUDED.pr_overall_movement  ,
pr_overall_balk = EXCLUDED.pr_overall_balk  ,
pr_overall_hp = EXCLUDED.pr_overall_hp ,
pr_overall_wild_pitch = EXCLUDED.pr_overall_wild_pitch  ,
pr_vsr_stuff = EXCLUDED.pr_vsr_stuff  ,
pr_vsr_control = EXCLUDED.pr_vsr_control  ,
pr_vsr_movement = EXCLUDED.pr_vsr_movement  ,
pr_vsr_balk = EXCLUDED.pr_vsr_balk  ,
pr_vsr_hp = EXCLUDED.pr_vsr_hp  ,
pr_vsr_wild_pitch = EXCLUDED.pr_vsr_wild_pitch  ,
pr_vsl_stuff = EXCLUDED.pr_vsl_stuff  ,
pr_vsl_control = EXCLUDED.pr_vsl_control  ,
pr_vsl_movement = EXCLUDED.pr_vsl_movement  ,
pr_vsl_balk = EXCLUDED.pr_vsl_balk  ,
pr_vsl_hp = EXCLUDED.pr_vsl_hp  ,
pr_vsl_wild_pitch = EXCLUDED.pr_vsl_wild_pitch  ,
pr_talent_stuff = EXCLUDED.pr_talent_stuff  ,
pr_talent_control = EXCLUDED.pr_talent_control  ,
pr_talent_movement = EXCLUDED.pr_talent_movement  ,
pr_talent_balk = EXCLUDED.pr_talent_balk  ,
pr_talent_hp = EXCLUDED.pr_talent_hp  ,
pr_talent_wild_pitch = EXCLUDED.pr_talent_wild_pitch  ,
pr_pitches_fastball = EXCLUDED.pr_pitches_fastball  ,
pr_pitches_slider = EXCLUDED.pr_pitches_slider  ,
pr_pitches_curve_ball = EXCLUDED.pr_pitches_curve_ball  ,
pr_pitches_screwball = EXCLUDED.pr_pitches_screwball  ,
pr_pitches_fork_ball = EXCLUDED.pr_pitches_fork_ball  ,
pr_pitches_change_up = EXCLUDED.pr_pitches_change_up  ,
pr_pitches_sinker = EXCLUDED.pr_pitches_sinker  ,
pr_pitches_splitter = EXCLUDED.pr_pitches_splitter  ,
pr_pitches_knuckle_ball = EXCLUDED.pr_pitches_knuckle_ball  ,
pr_pitches_cutter = EXCLUDED.pr_pitches_cutter  ,
pr_pitches_circle_change = EXCLUDED.pr_pitches_circle_change  ,
pr_pitches_knuckle_curve = EXCLUDED.pr_pitches_knuckle_curve  ,
pr_pitches_talent_fastball = EXCLUDED.pr_pitches_talent_fastball  ,
pr_pitches_talent_slider = EXCLUDED.pr_pitches_talent_slider  ,
pr_pitches_talent_curve_ball = EXCLUDED.pr_pitches_talent_curve_ball  ,
pr_pitches_talent_screw_ball = EXCLUDED.pr_pitches_talent_screw_ball  ,
pr_pitches_talent_fork_ball = EXCLUDED.pr_pitches_talent_fork_ball  ,
pr_pitches_talent_change_up = EXCLUDED.pr_pitches_talent_change_up  ,
pr_pitches_talent_sinker = EXCLUDED.pr_pitches_talent_sinker  ,
pr_pitches_talent_splitter = EXCLUDED.pr_pitches_talent_splitter  ,
pr_pitches_talent_knuckle_ball = EXCLUDED.pr_pitches_talent_knuckle_ball  ,
pr_pitches_talent_cutter = EXCLUDED.pr_pitches_talent_cutter  ,
pr_pitches_talent_circle_change = EXCLUDED.pr_pitches_talent_circle_change  ,
pr_pitches_talent_knuckle_curve = EXCLUDED.pr_pitches_talent_knuckle_curve  ,
velocity_id = EXCLUDED.velocity_id  ,
arm_slot_id = EXCLUDED.arm_slot_id  ,
pr_misc_stamina = EXCLUDED.pr_misc_stamina  ,
pr_misc_ground_fly = EXCLUDED.pr_misc_ground_fly  ,
pr_misc_hold = EXCLUDED.pr_misc_hold  ,
fr_infield_range = EXCLUDED.fr_infield_range  ,
fr_infield_arm = EXCLUDED.fr_infield_arm  ,
fr_turn_double_play = EXCLUDED.fr_turn_double_play  ,
fr_outfield_range = EXCLUDED.fr_outfield_range  ,
fr_outfield_arm = EXCLUDED.fr_outfield_arm  ,
fr_catcher_arm = EXCLUDED.fr_catcher_arm  ,
fr_catcher_ability = EXCLUDED.fr_catcher_ability  ,
fr_infield_error = EXCLUDED.fr_infield_error  ,
fr_outfield_error = EXCLUDED.fr_outfield_error  ,
fielding_rating_pos = EXCLUDED.fielding_rating_pos  ,
overall_rating = EXCLUDED.overall_rating  ,
talent_rating = EXCLUDED.talent_rating  ,
scouting_accuracy_id = EXCLUDED.scouting_accuracy_id,
modified_by = EXCLUDED.modified_by,
modified_ts = EXCLUDED.modified_ts,
pr_overall_babip = EXCLUDED.pr_overall_babip,
pr_vsr_babip = EXCLUDED.pr_vsr_babip,
pr_vsl_babip = EXCLUDED.pr_vsl_babip,
pr_talent_babip = EXCLUDED.pr_talent_babip,
pr_overall_hr_allowed = EXCLUDED.pr_overall_hr_allowed,
pr_vsr_hr_allowed = EXCLUDED.pr_vsr_hr_allowed,
pr_vsl_hr_allowed = EXCLUDED.pr_vsl_hr_allowed,
pr_talent_hr_allowed = EXCLUDED.pr_talent_hr_allowed,
fr_catcher_framing = EXCLUDED.fr_catcher_framing,
fielding_potential_pos = EXCLUDED.fielding_potential_pos,
overall = EXCLUDED.overall,
talent = EXCLUDED.talent
;

create temporary table players_injury_history
(
    player_id  integer,
    date       text,
    length     integer,
    setbacks   integer,
    day_to_day integer,
    effect     integer,
    body_part  integer
);

\copy players_injury_history FROM '/Users/brianmcneil/Library/Containers/com.ootpdevelopments.ootp26macqlm/Data/Application Support/Out of the Park Developments/OOTP Baseball 26/saved_games/WPOBL-test.lg/import_export/csv/players_injury_history.csv' DELIMITER ',' NULL AS 'NULL' CSV HEADER encoding 'UTF-8';

INSERT INTO player.player_injury_history (player_id, date, length, setbacks, day_to_day, effect_id, new_body_part_id)
SELECT DISTINCT player_id,
       date::date,
       length,
       setbacks,
       day_to_day::boolean,
       effect,
       body_part
FROM players_injury_history s
WHERE length != -1
ON CONFLICT (player_id, date,new_body_part_id, effect_id, length, day_to_day) DO UPDATE
    SET setbacks = excluded.setbacks,
        modified_ts = NOW(),
        modified_by = CURRENT_USER
    ;

create temporary table player_history
(
    history_id   integer,
    player_id    integer,
    history_date varchar(8),
    history_text text,
    season       integer
);

\copy player_history FROM '/Users/brianmcneil/Documents/Personal/ootp_stuff/ootp_sql/csv/ootp26_migrate/player_history.csv' DELIMITER ',' CSV HEADER encoding 'ISO-8859-1';

INSERT INTO player.player_note (note_date, player_id, note_type_id, note_text)
SELECT
    history_date,
    player_id,
    (SELECT note_type_id from lookup.note_type pht where pht.note_type_code = s.player_history_type_code) as player_history_type_id,
    history_text
FROM (SELECT DISTINCT
          ph.player_id,
          to_date(history_date,'yyyymmdd') as history_date,
          trim(split_part(history_text,']',1),'[') as player_history_type_code,
          split_part(history_text,']',2) as history_text
      FROM player_history ph
               JOIN players p on ph.player_id = p.player_id
               JOIN (select (l."current_date")::date as present_date FROM leagues l LIMIT 1) ll on 1=1
      where ph.history_date != ' Drafted'
        AND to_date(history_date,'yyyymmdd') >= ll.present_date - interval '1 month'
     ) s
WHERE history_text != ''
ON CONFLICT (player_id,note_date,note_text) DO NOTHING
;

insert into player.prospect_list (prospect_list_date, league_id)
select distinct note_date, (SELECT l.league_id FROM league.league l WHERE l.name_abbr = split_part(note_text,' in the ',2)) as league_id
from player.player_note n
where note_text like 'Named the #%'
except SELECT prospect_list_date, league_id from player.prospect_list
ON CONFLICT (prospect_list_date,league_id) DO NOTHING 

;

insert into player.prospect(prospect_list_id, player_id, prospect_rank)
select (select l.prospect_list_id from player.prospect_list l where l.prospect_list_date = n.note_date
                                                              AND l.league_id = (SELECT l.league_id FROM league.league l WHERE l.name_abbr = split_part(note_text,' in the ',2))),
       player_id,
       split_part(split_part(note_text,'#',2),' ',1)::smallint
from player.player_note n
where note_text like 'Named the #%'
except select prospect_list_id, player_id, prospect_rank
FROM player.prospect
ON CONFLICT (prospect_list_id,player_id) DO NOTHING
;

create temporary table players_salary_history
(
    player_id integer,
    team_id   integer,
    year      integer,
    salary    integer,
    uniform   text
);

\copy players_salary_history FROM '/Users/brianmcneil/Library/Containers/com.ootpdevelopments.ootp26macqlm/Data/Application Support/Out of the Park Developments/OOTP Baseball 26/saved_games/WPOBL-test.lg/import_export/csv/players_salary_history.csv' DELIMITER ',' NULL AS 'NULL' CSV HEADER encoding 'UTF-8';

INSERT INTO player.player_salary_history (player_id, team_id, season, salary)
SELECT player_id,
COALESCE(t.team_id,0) as team_id,
year,
salary
FROM players_salary_history h
LEFT JOIN team.team t ON h.team_id = t.team_id
WHERE h.salary > 0 AND year > 0
EXCEPT SELECT player_id, team_id, season, salary
FROM player.player_salary_history
ON CONFLICT (player_id, team_id, season) DO UPDATE
SET salary = excluded.salary
;

