create temporary table leagues
(
    league_id                              integer PRIMARY KEY,
    name                                   text,
    abbr                                   text,
    nation_id                              integer,
    language_id                            integer,
    gender                                 integer,
    historical_league                      integer,
    logo_file_name                         text,
    players_path                           text,
    start_date                             date,
    preferred_start_date                   date,
    pitcher_award_name                     text,
    mvp_award_name                         text,
    rookie_award_name                      text,
    defense_award_name                     text,
    fictional_players                      integer,
    start_fantasy_draft                    integer,
    trading_deadline                       integer,
    winter_meetings                        integer,
    arbitration_offering                   integer,
    show_draft_pool                        integer,
    rosters_expanded                       integer,
    draft_date                             date,
    rule_5_draft_date                      date,
    international_fa_date                  date,
    roster_expand_date                     date,
    trade_deadline_date                    date,
    allstar_date                           date,
    days_until_deadline                    integer,
    next_draft_type                        integer,
    parent_league_id                       integer,
    league_state                           integer,
    season_year                            integer,
    historical_year                        integer,
    league_level                           integer,
    stats_detail                           integer,
    historical_import_path                 text,
    foreigner_percentage                   integer,
    was_ootp6                              integer,
    was_65                                 integer,
    allstar_game                           integer,
    auto_schedule_allstar                  integer,
    allstar_team_id0                       integer,
    allstar_team_id1                       integer,
    schedule_file_1                        text,
    schedule_file_2                        text,
    rules_rule_5                           integer,
    rules_minor_league_options             integer,
    rules_trading                          integer,
    rules_trading_deadline_events          integer,
    rules_draft_pick_trading               integer,
    rules_financials                       integer,
    rules_amateur_draft                    integer,
    rules_fa_compensation                  integer,
    rules_schedule_balanced                integer,
    rules_schedule_inter_league            integer,
    rules_schedule_force_start_day         integer,
    rules_trades_other_leagues             integer,
    rules_free_agents_from_other_leagues   integer,
    rules_free_agents_leave_other_leagues  integer,
    rules_allstar_game                     integer,
    rules_spring_training                  integer,
    rules_active_roster_limit              integer,
    rules_secondary_roster_limit           integer,
    rules_expanded_roster_limit            integer,
    rules_min_service_days                 integer,
    rules_waiver_period_length             integer,
    rules_dfa_period_length                integer,
    rules_fa_minimum_years                 integer,
    rules_salary_arbitration_minimum_years integer,
    rules_minor_league_fa_minimum_years    integer,
    rules_foreigner_limit                  integer,
    rules_foreigner_pitcher_limit          integer,
    rules_foreigner_hitter_limit           integer,
    rules_schedule_games_per_team          integer,
    rules_schedule_typical_series          integer,
    rules_schedule_game_times              integer,
    rules_schedule_preferred_start_day     integer,
    rules_amateur_draft_rounds             integer,
    rules_minimum_salary                   integer,
    rules_salary_cap                       integer,
    rules_player_salary0                   integer,
    rules_player_salary1                   integer,
    rules_player_salary2                   integer,
    rules_player_salary3                   integer,
    rules_player_salary4                   integer,
    rules_player_salary5                   integer,
    rules_player_salary6                   integer,
    rules_player_salary7                   integer,
    rules_average_coach_salary             integer,
    rules_average_attendance               integer,
    rules_average_national_media_contract  integer,
    rules_cash_maximum                     integer,
    rules_average_ticket_price             double precision,
    rules_luxury_sharing                   integer,
    rules_revenue_sharing                  integer,
    rules_revenue_sharing_tax              integer,
    rules_luxury_sharing_cap               integer,
    rules_luxury_tax                       integer,
    rules_national_media_contract_fixed    integer,
    rules_owner_decides_budget             integer,
    rules_schedule_auto_adjust_dates       integer,
    rules_historical_import_rookies        integer,
    avg_rating_contact                     integer,
    avg_rating_gap                         integer,
    avg_rating_power                       integer,
    avg_rating_eye                         integer,
    avg_rating_strikeouts                  integer,
    avg_rating_stuff                       integer,
    avg_rating_movement                    integer,
    avg_rating_control                     integer,
    avg_rating_fielding0                   integer,
    avg_rating_fielding1                   integer,
    avg_rating_fielding2                   integer,
    avg_rating_fielding3                   integer,
    avg_rating_fielding4                   integer,
    avg_rating_fielding5                   integer,
    avg_rating_fielding6                   integer,
    avg_rating_fielding7                   integer,
    avg_rating_fielding8                   integer,
    avg_rating_fielding9                   integer,
    avg_rating_overall                     integer,
    avg_rating_age                         double precision,
    league_totals_ab                       integer,
    league_totals_h                        integer,
    league_totals_d                        integer,
    league_totals_t                        integer,
    league_totals_hr                       integer,
    league_totals_bb                       integer,
    league_totals_hp                       integer,
    league_totals_k                        integer,
    league_totals_pa                       integer,
    league_totals_babip                    double precision,
    league_totals_mod_h                    double precision,
    league_totals_mod_d                    double precision,
    league_totals_mod_t                    double precision,
    league_totals_mod_hr                   double precision,
    league_totals_mod_bb                   double precision,
    league_totals_mod_hp                   double precision,
    league_totals_mod_k                    double precision,
    league_totals_mod_babip                double precision,
    ml_equivalencies_avg                   double precision,
    ml_equivalencies_hr                    double precision,
    ml_equivalencies_eb                    double precision,
    ml_equivalencies_bb                    double precision,
    ml_equivalencies_k                     double precision,
    ml_equivalencies_hp                    double precision,
    player_creation_modifier_contact       double precision,
    player_creation_modifier_gap           double precision,
    player_creation_modifier_power         double precision,
    player_creation_modifier_eye           double precision,
    player_creation_modifier_strikeouts    double precision,
    player_creation_modifier_stuff         double precision,
    player_creation_modifier_movement      double precision,
    player_creation_modifier_control       double precision,
    player_creation_modifier_speed         double precision,
    player_creation_modifier_fielding      double precision,
    financial_coefficient                  double precision,
    world_start_year                       integer,
    league_current_date                    date,
    background_color_id                    text,
    text_color_id                          text,
    scouting_coach_id                      integer
);

\copy leagues FROM '/Users/brianmcneil/Library/Containers/com.ootpdevelopments.ootp26macqlm/Data/Application Support/Out of the Park Developments/OOTP Baseball 26/saved_games/mlb-take-two.lg/import_export/csv/leagues.csv' DELIMITER ',' NULL AS 'NULL' CSV HEADER encoding 'UTF-8';

create temporary table teams
(
    team_id                     integer PRIMARY KEY,
    name                        text,
    abbr                        text,
    nickname                    text,
    logo_file_name              text,
    city_id                     integer,
    park_id                     integer,
    league_id                   integer,
    sub_league_id               integer,
    division_id                 integer,
    nation_id                   integer,
    parent_team_id              integer,
    level                       integer,
    prevent_any_moves           integer,
    human_team                  integer,
    human_id                    integer,
    gender                      integer,
    background_color_id         text,
    text_color_id               text,
    ballcaps_main_color_id      text,
    ballcaps_visor_color_id     text,
    jersey_main_color_id        text,
    jersey_away_color_id        text,
    jersey_secondary_color_id   text,
    jersey_pin_stripes_color_id text,
    allstar_team                integer,
    historical_id               text
);

\copy teams FROM '/Users/brianmcneil/Library/Containers/com.ootpdevelopments.ootp26macqlm/Data/Application Support/Out of the Park Developments/OOTP Baseball 26/saved_games/mlb-take-two.lg/import_export/csv/teams.csv' DELIMITER ',' NULL AS 'NULL' CSV HEADER encoding 'UTF-8';

create temporary table players
(
    player_id                   integer PRIMARY KEY,
    team_id                     integer,
    league_id                   integer,
    position                    integer,
    role                        integer,
    first_name                  text,
    last_name                   text,
    nick_name                   text,
    age                         integer,
    date_of_birth               text,
    city_of_birth_id            integer,
    nation_id                   integer,
    second_nation_id            integer,
    weight                      integer,
    height                      integer,
    retired                     integer,
    free_agent                  integer,
    last_league_id              integer,
    last_team_id                integer,
    organization_id             integer,
    last_organization_id        integer,
    language_ids0               integer,
    language_ids1               integer,
    uniform_number              integer,
    experience                  integer,
    person_type                 integer,
    bats                        integer,
    throws                      integer,
    personality_greed           integer,
    personality_loyalty         integer,
    personality_play_for_winner integer,
    personality_work_ethic      integer,
    personality_intelligence    integer,
    personality_leader          integer,
    historical_id               text,
    historical_team_id          text,
    best_contract_offer_id      integer,
    injury_is_injured           integer,
    injury_dtd_injury           integer,
    injury_career_ending        integer,
    injury_dl_left              integer,
    injury_dl_playoff_round     integer,
    injury_left                 integer,
    dtd_injury_effect           integer,
    dtd_injury_effect_hit       integer,
    dtd_injury_effect_throw     integer,
    dtd_injury_effect_run       integer,
    injury_id                   integer,
    injury_id2                  integer,
    injury_dtd_injury2          integer,
    injury_left2                integer,
    dtd_injury_effect2          integer,
    dtd_injury_effect_hit2      integer,
    dtd_injury_effect_throw2    integer,
    dtd_injury_effect_run2      integer,
    prone_overall               integer,
    prone_leg                   integer,
    prone_back                  integer,
    prone_arm                   integer,
    fatigue_pitches0            integer,
    fatigue_pitches1            integer,
    fatigue_pitches2            integer,
    fatigue_pitches3            integer,
    fatigue_pitches4            integer,
    fatigue_pitches5            integer,
    fatigue_points              integer,
    fatigue_played_today        integer,
    college                     integer,
    acquired                    integer,
    acquired_date               date,
    draft_year                  integer,
    draft_round                 integer,
    draft_supplemental          integer,
    draft_pick                  integer,
    draft_overall_pick          integer,
    draft_eligible              integer,
    hsc_status                  integer,
    redshirt                    integer,
    picked_in_draft             integer,
    school                      integer,
    commit_school               integer,
    hidden                      integer,
    draft_league_id             integer,
    draft_team_id               integer,
    turned_coach                integer,
    hall_of_fame                integer,
    rust                        integer,
    inducted                    integer,
    strategy_override_team      integer,
    strategy_stealing           integer,
    strategy_running            integer,
    strategy_bunt_for_hit       integer,
    strategy_sac_bunt           integer,
    strategy_hit_run            integer,
    strategy_hook_start         integer,
    strategy_hook_relief        integer,
    strategy_pitch_count        integer,
    strategy_pitch_around       integer,
    strategy_never_pinch_hit    integer,
    strategy_defensive_sub      integer,
    strategy_dtd_sit_min        integer,
    strategy_dtd_allow_ph       integer,
    local_pop                   integer,
    national_pop                integer,
    draft_protected             integer,
    morale                      integer,
    morale_mod                  integer,
    morale_player_performance   integer,
    morale_team_performance     integer,
    morale_team_transactions    integer,
    morale_team_chemistry       integer,
    morale_player_role          integer,
    expectation                 integer,
    on_loan                     integer,
    loan_league_id              integer,
    loan_team_id                integer
);

\copy players FROM '/Users/brianmcneil/Library/Containers/com.ootpdevelopments.ootp26macqlm/Data/Application Support/Out of the Park Developments/OOTP Baseball 26/saved_games/mlb-take-two.lg/import_export/csv/players.csv' DELIMITER ',' NULL AS 'NULL' CSV HEADER encoding 'UTF-8';

INSERT INTO league.league(league_id,
name_text,
name_abbr,
nation_id,
language_id,
gender_id,
historical_league_status,
logo_file_name,
player_path,
start_date,
preferred_start_date,
pitcher_award_name,
mvp_award_name,
rookie_award_name,
defense_award_name,
fictional_player_status,
start_fantasy_draft_status,
trading_deadline_status,
winter_meetings_status,
arbitration_offering_status,
show_draft_pool_status,
rosters_expanded_status,
draft_date,
rule_5_draft_date,
international_fa_date,
roster_expand_date,
trade_deadline_date,
all_star_date,
days_until_deadline,
next_draft_type_id,
parent_league_id,
league_state_id,
season_year,
historical_season,
league_level_id,
stats_detail_id,
historical_import_path,
foreigner_percentage,
was_ootp6_status,
was_65_status,
all_star_game_status,
auto_schedule_all_star_status,
all_star_team_id,
schedule_file,
rules_rule_5,
rules_minor_league_options,
rules_trading,
rules_trading_deadline_events,
rules_draft_pick_trading,
rules_financials,
rules_amateur_draft,
rules_fa_compensation,
rules_schedule_balanced,
rules_schedule_inter_league,
rules_schedule_force_start_day,
rules_trades_other_leagues,
rules_free_agents_from_other_leagues,
rules_free_agents_leave_other_leagues,
rules_all_star_game,
rules_spring_training,
rules_active_roster_limit,
rules_secondary_roster_limit,
rules_expanded_roster_limit,
rules_min_service_days,
rules_waiver_period_length,
rules_dfa_period_length,
rules_fa_minimum_seasons,
rules_salary_arbitration_minimum_seasons,
rules_minor_league_fa_minimum_seasons,
rules_foreigner_limit,
rules_foreigner_pitcher_limit,
rules_foreigner_hitter_limit,
rules_schedule_games_per_team,
rules_schedule_typical_series,
rules_schedule_game_times,
rules_schedule_preferred_start_day,
rules_amateur_draft_rounds,
rules_minimum_salary,
rules_salary_cap,
rules_player_salary,
rules_average_coach_salary,
rules_average_attendance,
rules_average_national_media_contract,
rules_cash_maximum,
rules_average_ticket_price,
rules_revenue_sharing,
rules_luxury_sharing,
rules_revenue_sharing_tax,
rules_luxury_sharing_cap,
rules_luxury_tax,
rules_national_media_contract_fixed,
rules_owner_decides_budget,
rules_schedule_auto_adjust_dates,
rules_historical_import_rookies,
avg_rating_contact,
avg_rating_gap,
avg_rating_power,
avg_rating_eye,
avg_rating_strikeouts,
avg_rating_stuff,
avg_rating_movement,
avg_rating_control,
avg_rating_fielding,
avg_rating_overall,
avg_rating_age,
league_totals_ab,
league_totals_h,
league_totals_d,
league_totals_t,
league_totals_hr,
league_totals_bb,
league_totals_hp,
league_totals_k,
league_totals_pa,
league_totals_babip,
league_totals_mod_h,
league_totals_mod_d,
league_totals_mod_t,
league_totals_mod_hr,
league_totals_mod_bb,
league_totals_mod_hp,
league_totals_mod_k,
league_totals_mod_babip,
ml_equivalencies_avg,
ml_equivalencies_hr,
ml_equivalencies_eb,
ml_equivalencies_bb,
ml_equivalencies_k,
ml_equivalencies_hp,
player_creation_modifier_contact,
player_creation_modifier_gap,
player_creation_modifier_power,
player_creation_modifier_eye,
player_creation_modifier_strikeouts,
player_creation_modifier_stuff,
player_creation_modifier_movement,
player_creation_modifier_control,
player_creation_modifier_speed,
player_creation_modifier_fielding,
financial_coefficient,
world_start_season,
present_date,
background_color_id,
text_color_id,
scouting_coach_id)
SELECT league_id,
       name,
       abbr,
       nation_id,
       language_id,
       gender,
       historical_league::boolean,
       logo_file_name,
       players_path,
       start_date,
       preferred_start_date,
       pitcher_award_name,
       mvp_award_name,
       rookie_award_name,
       defense_award_name,
       fictional_players::boolean,
       start_fantasy_draft::boolean,
       trading_deadline::boolean,
       winter_meetings::boolean,
       arbitration_offering::boolean,
       show_draft_pool::boolean,
       rosters_expanded::boolean,
       draft_date,
       rule_5_draft_date,
       l.international_fa_date ,
       roster_expand_date,
       trade_deadline_date,
       allstar_date,
       days_until_deadline,
       CASE WHEN next_draft_type != 0 THEN next_draft_type END,
       league_id,
       league_state,
       season_year,
       historical_year,
       league_level,
       stats_detail,
       historical_import_path,
       foreigner_percentage,
       was_ootp6::boolean,
       was_65::boolean,
       allstar_game::boolean,
       auto_schedule_allstar::boolean,
       ARRAY[allstar_team_id0,allstar_team_id1],
       ARRAY[schedule_file_1,schedule_file_2],
       rules_rule_5::boolean,
       rules_minor_league_options::boolean,
       rules_trading::boolean,
       rules_trading_deadline_events,
       rules_draft_pick_trading::boolean,
       rules_financials::boolean,
       rules_amateur_draft::boolean,
       rules_fa_compensation::boolean,
       rules_schedule_balanced::boolean,
       rules_schedule_inter_league::boolean,
       rules_schedule_force_start_day::boolean,
       rules_trades_other_leagues::boolean,
       rules_free_agents_from_other_leagues::boolean,
       rules_free_agents_leave_other_leagues::boolean,
       rules_allstar_game::boolean,
       rules_spring_training::boolean,
       rules_active_roster_limit,
       rules_secondary_roster_limit,
       rules_expanded_roster_limit,
       rules_min_service_days,
       rules_waiver_period_length,
       rules_dfa_period_length,
       rules_fa_minimum_years,
       rules_salary_arbitration_minimum_years,
       rules_minor_league_fa_minimum_years,
       rules_foreigner_limit,
       rules_foreigner_pitcher_limit,
       rules_foreigner_hitter_limit,
       rules_schedule_games_per_team,
       rules_schedule_typical_series,
       rules_schedule_game_times,
       rules_schedule_preferred_start_day,
       rules_amateur_draft_rounds,
       rules_minimum_salary,
       rules_salary_cap::boolean,
       ARRAY[rules_player_salary0::integer,
           rules_player_salary1::integer,
           rules_player_salary2::integer,
           rules_player_salary3::integer,
           rules_player_salary4::integer,
           rules_player_salary5::integer,
           rules_player_salary6::integer,
           rules_player_salary7::integer],
       rules_average_coach_salary,
       rules_average_attendance,
       rules_average_national_media_contract,
       rules_cash_maximum,
       rules_average_ticket_price,
       rules_revenue_sharing::boolean,
       l.rules_luxury_sharing::boolean ,
       l.rules_revenue_sharing_tax,
       l.rules_luxury_sharing_cap ,
       l.rules_luxury_tax,
       rules_national_media_contract_fixed::boolean,
       rules_owner_decides_budget::boolean,
       rules_schedule_auto_adjust_dates::boolean,
       rules_historical_import_rookies::boolean,
       avg_rating_contact,
       avg_rating_gap,
       avg_rating_power,
       avg_rating_eye,
       avg_rating_strikeouts,
       avg_rating_stuff,
       avg_rating_movement,
       avg_rating_control,
       ARRAY[avg_rating_fielding0,
           avg_rating_fielding1,
           avg_rating_fielding2,
           avg_rating_fielding3,
           avg_rating_fielding4,
           avg_rating_fielding5,
           avg_rating_fielding6,
           avg_rating_fielding7,
           avg_rating_fielding8,
           avg_rating_fielding9],
       avg_rating_overall,
       avg_rating_age,
       league_totals_ab,
       league_totals_h,
       league_totals_d,
       league_totals_t,
       league_totals_hr,
       league_totals_bb,
       league_totals_hp,
       league_totals_k,
       league_totals_pa,
       league_totals_babip,
       league_totals_mod_h,
       league_totals_mod_d,
       league_totals_mod_t,
       league_totals_mod_hr,
       league_totals_mod_bb,
       league_totals_mod_hp,
       league_totals_mod_k,
       league_totals_mod_babip,
       ml_equivalencies_avg,
       ml_equivalencies_hr,
       ml_equivalencies_eb,
       ml_equivalencies_bb,
       ml_equivalencies_k,
       ml_equivalencies_hp,
       player_creation_modifier_contact,
       player_creation_modifier_gap,
       player_creation_modifier_power,
       player_creation_modifier_eye,
       player_creation_modifier_strikeouts,
       player_creation_modifier_stuff,
       player_creation_modifier_movement,
       player_creation_modifier_control,
       player_creation_modifier_speed,
       player_creation_modifier_fielding,
       financial_coefficient,
       world_start_year,
       league_current_date,
       background_color_id,
       text_color_id,
       CASE WHEN scouting_coach_id != -1 then scouting_coach_id END
FROM leagues l
EXCEPT SELECT
    league_id,
    name_text,
    name_abbr,
    nation_id,
    language_id,
    gender_id,
    historical_league_status,
    logo_file_name,
    player_path,
    start_date,
    preferred_start_date,
    pitcher_award_name,
    mvp_award_name,
    rookie_award_name,
    defense_award_name,
    fictional_player_status,
    start_fantasy_draft_status,
    trading_deadline_status,
    winter_meetings_status,
    arbitration_offering_status,
    show_draft_pool_status,
    rosters_expanded_status,
    draft_date,
    rule_5_draft_date,
    international_fa_date,
    roster_expand_date,
    trade_deadline_date,
    all_star_date,
    days_until_deadline,
    next_draft_type_id,
    parent_league_id,
    league_state_id,
    season_year,
    historical_season,
    league_level_id,
    stats_detail_id,
    historical_import_path,
    foreigner_percentage,
    was_ootp6_status,
    was_65_status,
    all_star_game_status,
    auto_schedule_all_star_status,
    all_star_team_id,
    schedule_file,
    rules_rule_5,
    rules_minor_league_options,
    rules_trading,
    rules_trading_deadline_events,
    rules_draft_pick_trading,
    rules_financials,
    rules_amateur_draft,
    rules_fa_compensation,
    rules_schedule_balanced,
    rules_schedule_inter_league,
    rules_schedule_force_start_day,
    rules_trades_other_leagues,
    rules_free_agents_from_other_leagues,
    rules_free_agents_leave_other_leagues,
    rules_all_star_game,
    rules_spring_training,
    rules_active_roster_limit,
    rules_secondary_roster_limit,
    rules_expanded_roster_limit,
    rules_min_service_days,
    rules_waiver_period_length,
    rules_dfa_period_length,
    rules_fa_minimum_seasons,
    rules_salary_arbitration_minimum_seasons,
    rules_minor_league_fa_minimum_seasons,
    rules_foreigner_limit,
    rules_foreigner_pitcher_limit,
    rules_foreigner_hitter_limit,
    rules_schedule_games_per_team,
    rules_schedule_typical_series,
    rules_schedule_game_times,
    rules_schedule_preferred_start_day,
    rules_amateur_draft_rounds,
    rules_minimum_salary,
    rules_salary_cap,
    rules_player_salary,
    rules_average_coach_salary,
    rules_average_attendance,
    rules_average_national_media_contract,
    rules_cash_maximum,
    rules_average_ticket_price,
    rules_revenue_sharing,
    rules_luxury_sharing,
    rules_revenue_sharing_tax,
    rules_luxury_sharing_cap,
    rules_luxury_tax,
    rules_national_media_contract_fixed,
    rules_owner_decides_budget,
    rules_schedule_auto_adjust_dates,
    rules_historical_import_rookies,
    avg_rating_contact,
    avg_rating_gap,
    avg_rating_power,
    avg_rating_eye,
    avg_rating_strikeouts,
    avg_rating_stuff,
    avg_rating_movement,
    avg_rating_control,
    avg_rating_fielding,
    avg_rating_overall,
    avg_rating_age,
    league_totals_ab,
    league_totals_h,
    league_totals_d,
    league_totals_t,
    league_totals_hr,
    league_totals_bb,
    league_totals_hp,
    league_totals_k,
    league_totals_pa,
    league_totals_babip,
    league_totals_mod_h,
    league_totals_mod_d,
    league_totals_mod_t,
    league_totals_mod_hr,
    league_totals_mod_bb,
    league_totals_mod_hp,
    league_totals_mod_k,
    league_totals_mod_babip,
    ml_equivalencies_avg,
    ml_equivalencies_hr,
    ml_equivalencies_eb,
    ml_equivalencies_bb,
    ml_equivalencies_k,
    ml_equivalencies_hp,
    player_creation_modifier_contact,
    player_creation_modifier_gap,
    player_creation_modifier_power,
    player_creation_modifier_eye,
    player_creation_modifier_strikeouts,
    player_creation_modifier_stuff,
    player_creation_modifier_movement,
    player_creation_modifier_control,
    player_creation_modifier_speed,
    player_creation_modifier_fielding,
    financial_coefficient,
    world_start_season,
    present_date,
    background_color_id,
    text_color_id,
    scouting_coach_id
FROM league.league
ON CONFLICT (league_id) DO UPDATE
    SET
        name_text = EXCLUDED.name_text ,
        name_abbr = EXCLUDED.name_abbr ,
        nation_id = EXCLUDED.nation_id ,
        language_id = EXCLUDED.language_id ,
        gender_id = EXCLUDED.gender_id ,
        historical_league_status = EXCLUDED.historical_league_status ,
        logo_file_name = EXCLUDED.logo_file_name ,
        player_path = EXCLUDED.player_path ,
        start_date = COALESCE(league.start_date,EXCLUDED.start_date) ,
        preferred_start_date = COALESCE(league.preferred_start_date,EXCLUDED.preferred_start_date) ,
        pitcher_award_name = EXCLUDED.pitcher_award_name ,
        mvp_award_name = EXCLUDED.mvp_award_name ,
        rookie_award_name = EXCLUDED.rookie_award_name ,
        defense_award_name = EXCLUDED.defense_award_name ,
        fictional_player_status = EXCLUDED.fictional_player_status ,
        start_fantasy_draft_status = EXCLUDED.start_fantasy_draft_status ,
        trading_deadline_status = EXCLUDED.trading_deadline_status ,
        winter_meetings_status = EXCLUDED.winter_meetings_status ,
        arbitration_offering_status = EXCLUDED.arbitration_offering_status ,
        show_draft_pool_status = EXCLUDED.show_draft_pool_status ,
        rosters_expanded_status = EXCLUDED.rosters_expanded_status ,
        draft_date = COALESCE(league.draft_date,EXCLUDED.draft_date) ,
        rule_5_draft_date = COALESCE(league.rule_5_draft_date,EXCLUDED.rule_5_draft_date) ,
        international_fa_date = COALESCE(league.international_fa_date,EXCLUDED.international_fa_date) ,
        roster_expand_date = COALESCE(league.roster_expand_date,EXCLUDED.roster_expand_date) ,
        trade_deadline_date = COALESCE(league.trade_deadline_date,EXCLUDED.trade_deadline_date) ,
        all_star_date = COALESCE(league.all_star_date,EXCLUDED.all_star_date) ,
        days_until_deadline = EXCLUDED.days_until_deadline ,
        next_draft_type_id = EXCLUDED.next_draft_type_id ,
        parent_league_id = EXCLUDED.parent_league_id ,
        league_state_id = EXCLUDED.league_state_id ,
        season_year = EXCLUDED.season_year ,
        historical_season = EXCLUDED.historical_season ,
        league_level_id = CASE WHEN league.league_level_id = 9 THEN league.league_level_id ELSE EXCLUDED.league_level_id END  ,
        stats_detail_id = EXCLUDED.stats_detail_id ,
        historical_import_path = EXCLUDED.historical_import_path ,
        foreigner_percentage = EXCLUDED.foreigner_percentage ,
        was_ootp6_status = EXCLUDED.was_ootp6_status ,
        was_65_status = EXCLUDED.was_65_status ,
        all_star_game_status = EXCLUDED.all_star_game_status ,
        auto_schedule_all_star_status = EXCLUDED.auto_schedule_all_star_status ,
        all_star_team_id = EXCLUDED.all_star_team_id ,
        schedule_file = EXCLUDED.schedule_file ,
        rules_rule_5 = EXCLUDED.rules_rule_5 ,
        rules_minor_league_options = EXCLUDED.rules_minor_league_options ,
        rules_trading = EXCLUDED.rules_trading ,
        rules_trading_deadline_events = EXCLUDED.rules_trading_deadline_events ,
        rules_draft_pick_trading = EXCLUDED.rules_draft_pick_trading ,
        rules_financials = EXCLUDED.rules_financials ,
        rules_amateur_draft = EXCLUDED.rules_amateur_draft ,
        rules_fa_compensation = EXCLUDED.rules_fa_compensation ,
        rules_schedule_balanced = EXCLUDED.rules_schedule_balanced ,
        rules_schedule_inter_league = EXCLUDED.rules_schedule_inter_league ,
        rules_schedule_force_start_day = EXCLUDED.rules_schedule_force_start_day ,
        rules_trades_other_leagues = EXCLUDED.rules_trades_other_leagues ,
        rules_free_agents_from_other_leagues = EXCLUDED.rules_free_agents_from_other_leagues ,
        rules_free_agents_leave_other_leagues = EXCLUDED.rules_free_agents_leave_other_leagues ,
        rules_all_star_game = EXCLUDED.rules_all_star_game ,
        rules_spring_training = EXCLUDED.rules_spring_training ,
        rules_active_roster_limit = EXCLUDED.rules_active_roster_limit ,
        rules_secondary_roster_limit = EXCLUDED.rules_secondary_roster_limit ,
        rules_expanded_roster_limit = EXCLUDED.rules_expanded_roster_limit ,
        rules_min_service_days = EXCLUDED.rules_min_service_days ,
        rules_waiver_period_length = EXCLUDED.rules_waiver_period_length ,
        rules_dfa_period_length = EXCLUDED.rules_dfa_period_length ,
        rules_fa_minimum_seasons = EXCLUDED.rules_fa_minimum_seasons ,
        rules_salary_arbitration_minimum_seasons = EXCLUDED.rules_salary_arbitration_minimum_seasons ,
        rules_minor_league_fa_minimum_seasons = EXCLUDED.rules_minor_league_fa_minimum_seasons ,
        rules_foreigner_limit = EXCLUDED.rules_foreigner_limit ,
        rules_foreigner_pitcher_limit = EXCLUDED.rules_foreigner_pitcher_limit ,
        rules_foreigner_hitter_limit = EXCLUDED.rules_foreigner_hitter_limit ,
        rules_schedule_games_per_team = EXCLUDED.rules_schedule_games_per_team ,
        rules_schedule_typical_series = EXCLUDED.rules_schedule_typical_series ,
        rules_schedule_game_times = excluded.rules_schedule_game_times,
        rules_schedule_preferred_start_day = EXCLUDED.rules_schedule_preferred_start_day ,
        rules_amateur_draft_rounds = EXCLUDED.rules_amateur_draft_rounds ,
        rules_minimum_salary = EXCLUDED.rules_minimum_salary ,
        rules_salary_cap = EXCLUDED.rules_salary_cap ,
        rules_player_salary = EXCLUDED.rules_player_salary ,
        rules_average_coach_salary = EXCLUDED.rules_average_coach_salary ,
        rules_average_attendance = EXCLUDED.rules_average_attendance ,
        rules_average_national_media_contract = EXCLUDED.rules_average_national_media_contract ,
        rules_cash_maximum = EXCLUDED.rules_cash_maximum ,
        rules_average_ticket_price = EXCLUDED.rules_average_ticket_price ,
        rules_luxury_sharing = EXCLUDED.rules_luxury_sharing ,
        rules_revenue_sharing = EXCLUDED.rules_revenue_sharing ,
        rules_luxury_sharing_cap = EXCLUDED.rules_luxury_sharing_cap ,
        rules_revenue_sharing_tax = EXCLUDED.rules_revenue_sharing_tax ,
        rules_luxury_tax = EXCLUDED.rules_luxury_tax ,
        rules_national_media_contract_fixed = EXCLUDED.rules_national_media_contract_fixed ,
        rules_owner_decides_budget = EXCLUDED.rules_owner_decides_budget ,
        rules_schedule_auto_adjust_dates = EXCLUDED.rules_schedule_auto_adjust_dates ,
        rules_historical_import_rookies = EXCLUDED.rules_historical_import_rookies ,
        avg_rating_contact = EXCLUDED.avg_rating_contact ,
        avg_rating_gap = EXCLUDED.avg_rating_gap ,
        avg_rating_power = EXCLUDED.avg_rating_power ,
        avg_rating_eye = EXCLUDED.avg_rating_eye ,
        avg_rating_strikeouts = EXCLUDED.avg_rating_strikeouts ,
        avg_rating_stuff = EXCLUDED.avg_rating_stuff ,
        avg_rating_movement = EXCLUDED.avg_rating_movement ,
        avg_rating_control = EXCLUDED.avg_rating_control ,
        avg_rating_fielding = EXCLUDED.avg_rating_fielding ,
        avg_rating_overall = EXCLUDED.avg_rating_overall ,
        avg_rating_age = EXCLUDED.avg_rating_age ,
        league_totals_ab = EXCLUDED.league_totals_ab ,
        league_totals_h = EXCLUDED.league_totals_h ,
        league_totals_d = EXCLUDED.league_totals_d ,
        league_totals_t = EXCLUDED.league_totals_t ,
        league_totals_hr = EXCLUDED.league_totals_hr ,
        league_totals_bb = EXCLUDED.league_totals_bb ,
        league_totals_hp = EXCLUDED.league_totals_hp ,
        league_totals_k = EXCLUDED.league_totals_k ,
        league_totals_pa = EXCLUDED.league_totals_pa ,
        league_totals_babip = EXCLUDED.league_totals_babip ,
        league_totals_mod_h = EXCLUDED.league_totals_mod_h ,
        league_totals_mod_d = EXCLUDED.league_totals_mod_d ,
        league_totals_mod_t = EXCLUDED.league_totals_mod_t ,
        league_totals_mod_hr = EXCLUDED.league_totals_mod_hr ,
        league_totals_mod_bb = EXCLUDED.league_totals_mod_bb ,
        league_totals_mod_hp = EXCLUDED.league_totals_mod_hp ,
        league_totals_mod_k = EXCLUDED.league_totals_mod_k ,
        league_totals_mod_babip = EXCLUDED.league_totals_mod_babip ,
        ml_equivalencies_avg = EXCLUDED.ml_equivalencies_avg ,
        ml_equivalencies_hr = EXCLUDED.ml_equivalencies_hr ,
        ml_equivalencies_eb = EXCLUDED.ml_equivalencies_eb ,
        ml_equivalencies_bb = EXCLUDED.ml_equivalencies_bb ,
        ml_equivalencies_k = EXCLUDED.ml_equivalencies_k ,
        ml_equivalencies_hp = EXCLUDED.ml_equivalencies_hp ,
        player_creation_modifier_contact = EXCLUDED.player_creation_modifier_contact ,
        player_creation_modifier_gap = EXCLUDED.player_creation_modifier_gap ,
        player_creation_modifier_power = EXCLUDED.player_creation_modifier_power ,
        player_creation_modifier_eye = EXCLUDED.player_creation_modifier_eye ,
        player_creation_modifier_strikeouts = EXCLUDED.player_creation_modifier_strikeouts ,
        player_creation_modifier_stuff = EXCLUDED.player_creation_modifier_stuff ,
        player_creation_modifier_movement = EXCLUDED.player_creation_modifier_movement ,
        player_creation_modifier_control = EXCLUDED.player_creation_modifier_control ,
        player_creation_modifier_speed = EXCLUDED.player_creation_modifier_speed ,
        player_creation_modifier_fielding = EXCLUDED.player_creation_modifier_fielding ,
        financial_coefficient = EXCLUDED.financial_coefficient ,
        world_start_season = EXCLUDED.world_start_season ,
        present_date = EXCLUDED.present_date ,
        background_color_id = EXCLUDED.background_color_id ,
        text_color_id = EXCLUDED.text_color_id ,
        scouting_coach_id = excluded.scouting_coach_id,
        modified_by = CURRENT_USER,
        modified_ts = now()
    ;

create temporary table divisions
(
    league_id     integer,
    sub_league_id integer,
    division_id   integer,
    name          text,
    gender        integer,
    PRIMARY KEY (league_id, sub_league_id, division_id)
);

\copy divisions FROM '/Users/brianmcneil/Library/Containers/com.ootpdevelopments.ootp26macqlm/Data/Application Support/Out of the Park Developments/OOTP Baseball 26/saved_games/mlb-take-two.lg/import_export/csv/divisions.csv' DELIMITER ',' NULL AS 'NULL' CSV HEADER encoding 'UTF-8';

INSERT INTO league.league (league_id)
select DISTINCT t.league_id
from teams t
LEFT JOIN divisions d ON t.division_id = d.division_id and t.sub_league_id = d.sub_league_id and t.league_id = d.league_id
WHERE d.division_id IS NULL
EXCEPT SELECT league_id
FROM league.league
;

INSERT INTO league.league (league_id)
select DISTINCT t.draft_league_id
from players t
EXCEPT SELECT league_id
FROM league.league
;

INSERT INTO league.league (league_id)
select DISTINCT t.loan_league_id
from players t
EXCEPT SELECT league_id
FROM league.league
;

create temporary table sub_leagues
(
    league_id         integer,
    sub_league_id     integer,
    name              text,
    abbr              text,
    gender            integer,
    designated_hitter integer,
    PRIMARY KEY (league_id, sub_league_id)
);

\copy sub_leagues FROM '/Users/brianmcneil/Library/Containers/com.ootpdevelopments.ootp26macqlm/Data/Application Support/Out of the Park Developments/OOTP Baseball 26/saved_games/mlb-take-two.lg/import_export/csv/sub_leagues.csv' DELIMITER ',' NULL AS 'NULL' CSV HEADER encoding 'UTF-8';

INSERT INTO league.sub_league (league_id, sub_league_id, name_text, name_abbr, gender_id, designated_hitter_status)
SELECT sl.league_id,
       sub_league_id,
       CASE WHEN name != '' THEN name END,
       CASE WHEN abbr != '' THEN abbr END,
       gender,
       designated_hitter::boolean
FROM sub_leagues sl
EXCEPT SELECT league_id, sub_league_id, name_text, name_abbr, gender_id, designated_hitter_status
FROM league.sub_league
ON CONFLICT (league_id,sub_league_id) DO UPDATE
    SET
        name_text = excluded.name_text,
        name_abbr = excluded.name_abbr,
        gender_id = excluded.gender_id,
        designated_hitter_status = excluded.designated_hitter_status,
        modified_by = CURRENT_USER,
        modified_ts = now()
    ;

INSERT INTO league.sub_league (league_id,sub_league_id)
select DISTINCT t.league_id, t.sub_league_id
from teams t
LEFT JOIN divisions d ON t.division_id = d.division_id and t.sub_league_id = d.sub_league_id and t.league_id = d.league_id
WHERE d.division_id IS NULL
EXCEPT SELECT league_id,sub_league_id
FROM league.sub_league
;

INSERT INTO league.division (league_id, sub_league_id, division_id, name_text, gender_id)
SELECT
    d.league_id,
    sub_league_id,
    division_id,
    CASE WHEN name != '' THEN name END,
    gender
FROM divisions d
EXCEPT SELECT league_id, sub_league_id, division_id, name_text, gender_id
       FROM league.division
ON CONFLICT (league_id, sub_league_id, division_id) DO UPDATE
    SET
        gender_id = excluded.gender_id,
        modified_by = CURRENT_USER,
        modified_ts = now()
    ;

INSERT INTO league.division (league_id,sub_league_id,division_id)
select DISTINCT t.league_id, t.sub_league_id, t.division_id
from teams t
LEFT JOIN divisions d ON t.division_id = d.division_id and t.sub_league_id = d.sub_league_id and t.league_id = d.league_id
WHERE d.division_id IS NULL
EXCEPT SELECT league_id,sub_league_id,division_id
FROM league.division
;

create temporary table parks
(
    park_id                           integer PRIMARY KEY,
    dimensions_x                      integer,
    dimensions_y                      integer,
    batter_left_x                     integer,
    batter_left_y                     integer,
    batter_right_x                    integer,
    batter_right_y                    integer,
    bases_x0                          integer,
    bases_x1                          integer,
    bases_x2                          integer,
    bases_y0                          integer,
    bases_y1                          integer,
    bases_y2                          integer,
    positions_x0                      integer,
    positions_x1                      integer,
    positions_x2                      integer,
    positions_x3                      integer,
    positions_x4                      integer,
    positions_x5                      integer,
    positions_x6                      integer,
    positions_x7                      integer,
    positions_x8                      integer,
    positions_x9                      integer,
    positions_y0                      integer,
    positions_y1                      integer,
    positions_y2                      integer,
    positions_y3                      integer,
    positions_y4                      integer,
    positions_y5                      integer,
    positions_y6                      integer,
    positions_y7                      integer,
    positions_y8                      integer,
    positions_y9                      integer,
    avg                               double precision,
    avg_l                             double precision,
    avg_r                             double precision,
    d                                 double precision,
    t                                 double precision,
    hr                                double precision,
    hr_r                              double precision,
    hr_l                              double precision,
    temperature0                      integer,
    temperature1                      integer,
    temperature2                      integer,
    temperature3                      integer,
    temperature4                      integer,
    temperature5                      integer,
    temperature6                      integer,
    temperature7                      integer,
    temperature8                      integer,
    temperature9                      integer,
    temperature10                     integer,
    temperature11                     integer,
    rain0                             integer,
    rain1                             integer,
    rain2                             integer,
    rain3                             integer,
    rain4                             integer,
    rain5                             integer,
    rain6                             integer,
    rain7                             integer,
    rain8                             integer,
    rain9                             integer,
    rain10                            integer,
    rain11                            integer,
    wind                              integer,
    wind_direction                    integer,
    distances0                        integer,
    distances1                        integer,
    distances2                        integer,
    distances3                        integer,
    distances4                        integer,
    distances5                        integer,
    distances6                        integer,
    wall_heights0                     integer,
    wall_heights1                     integer,
    wall_heights2                     integer,
    wall_heights3                     integer,
    wall_heights4                     integer,
    wall_heights5                     integer,
    wall_heights6                     integer,
    name                              text,
    picture                           text,
    picture_night                     text,
    nation_id                         integer,
    capacity                          integer,
    type                              integer,
    foul_ground                       integer,
    turf                              integer,
    gender                            integer,
    model_folder                      text,
    file_name_3d_model                text,
    home_team_dugout_is_at_first_base integer
);

\copy parks FROM '/Users/brianmcneil/Library/Containers/com.ootpdevelopments.ootp26macqlm/Data/Application Support/Out of the Park Developments/OOTP Baseball 26/saved_games/mlb-take-two.lg/import_export/csv/parks.csv' DELIMITER ',' NULL AS 'NULL' CSV HEADER encoding 'UTF-8';

INSERT INTO team.venue (venue_id, v_dimensions_x, v_dimensions_y, v_batter_left_x, v_batter_left_y, v_batter_right_x, v_batter_right_y, v_bases_x, v_bases_y, v_positions_x, v_positions_y, v_batting_average, v_batting_average_l, v_batting_average_r, v_double, v_triple, v_home_run, v_home_run_r, v_home_run_l, v_temperature, v_rain, v_wind, v_wind_direction,
                        v_distances, v_wall_heights, name_text, v_picture, v_picture_night, nation_id, v_capacity, venue_type_id, v_foul_ground, turf_id, gender_id, v_model_folder, v_file_name_3d_model, home_team_dugout_is_at_first_base_status)
SELECT
    park_id,
    dimensions_x,
    dimensions_y,
    batter_left_x,
    batter_left_y,
    batter_right_x,
    batter_right_y,
    ARRAY[bases_x0,
        bases_x1,
        bases_x2],
    ARRAY[bases_y0,
        bases_y1,
        bases_y2],
    ARRAY[positions_x0,
        positions_x1,
        positions_x2,
        positions_x3,
        positions_x4,
        positions_x5,
        positions_x6,
        positions_x7,
        positions_x8,
        positions_x9],
    ARRAY[positions_y0,
        positions_y1,
        positions_y2,
        positions_y3,
        positions_y4,
        positions_y5,
        positions_y6,
        positions_y7,
        positions_y8,
        positions_y9],
    avg,
    avg_l,
    avg_r,
    d,
    t,
    hr,
    hr_r,
    hr_l,
    ARRAY[temperature0,
        temperature1,
        temperature2,
        temperature3,
        temperature4,
        temperature5,
        temperature6,
        temperature7,
        temperature8,
        temperature9,
        temperature10,
        temperature11],
    ARRAY[rain0,
        rain1,
        rain2,
        rain3,
        rain4,
        rain5,
        rain6,
        rain7,
        rain8,
        rain9,
        rain10,
        rain11],
    wind,
    wind_direction,
    ARRAY[distances0,
        distances1,
        distances2,
        distances3,
        distances4,
        distances5,
        distances6],
    ARRAY[wall_heights0,
        wall_heights1,
        wall_heights2,
        wall_heights3,
        wall_heights4,
        wall_heights5,
        wall_heights6],
    CASE WHEN name != '' THEN name END,
    picture,
    picture_night,
    CASE WHEN nation_id != 0 THEN nation_id END,
    capacity,
    type,
    foul_ground,
    turf,
    gender,
    CASE WHEN model_folder != '' THEN model_folder END,
    CASE WHEN file_name_3d_model != '' THEN file_name_3d_model END,
    home_team_dugout_is_at_first_base::boolean
FROM parks p
EXCEPT SELECT venue_id, v_dimensions_x, v_dimensions_y, v_batter_left_x, v_batter_left_y, v_batter_right_x, v_batter_right_y, v_bases_x, v_bases_y, v_positions_x, v_positions_y, v_batting_average, v_batting_average_l, v_batting_average_r, v_double, v_triple, v_home_run, v_home_run_r, v_home_run_l, v_temperature, v_rain, v_wind, v_wind_direction,
                        v_distances, v_wall_heights, name_text, v_picture, v_picture_night, nation_id, v_capacity, venue_type_id, v_foul_ground, turf_id, gender_id, v_model_folder, v_file_name_3d_model, home_team_dugout_is_at_first_base_status
       FROM team.venue
ON CONFLICT (venue_id) DO UPDATE
    SET
        v_dimensions_x = EXCLUDED.v_dimensions_x ,
        v_dimensions_y = EXCLUDED.v_dimensions_y ,
        v_batter_left_x = EXCLUDED.v_batter_left_x ,
        v_batter_left_y = EXCLUDED.v_batter_left_y ,
        v_batter_right_x = EXCLUDED.v_batter_right_x ,
        v_batter_right_y = EXCLUDED.v_batter_right_y ,
        v_bases_x = EXCLUDED.v_bases_x ,
        v_bases_y = EXCLUDED.v_bases_y ,
        v_positions_x = EXCLUDED.v_positions_x ,
        v_positions_y = EXCLUDED.v_positions_y ,
        v_batting_average = EXCLUDED.v_batting_average ,
        v_batting_average_l = EXCLUDED.v_batting_average_l ,
        v_batting_average_r = EXCLUDED.v_batting_average_r ,
        v_double = EXCLUDED.v_double ,
        v_triple = EXCLUDED.v_triple ,
        v_home_run = EXCLUDED.v_home_run ,
        v_home_run_r = EXCLUDED.v_home_run_r ,
        v_home_run_l                             = EXCLUDED.v_home_run_l ,
        v_temperature                            = EXCLUDED.v_temperature ,
        v_rain                                   = EXCLUDED.v_rain ,
        v_wind                                   = EXCLUDED.v_wind ,
        v_wind_direction                         = EXCLUDED.v_wind_direction ,
        v_distances                              = EXCLUDED.v_distances ,
        v_wall_heights                           = EXCLUDED.v_wall_heights ,
        name_text                                = EXCLUDED.name_text ,
        v_picture                                = EXCLUDED.v_picture ,
        v_picture_night                          = EXCLUDED.v_picture_night ,
        nation_id                                = EXCLUDED.nation_id ,
        v_capacity                               = EXCLUDED.v_capacity ,
        venue_type_id                            = EXCLUDED.venue_type_id ,
        v_foul_ground                            = EXCLUDED.v_foul_ground ,
        turf_id                                  = EXCLUDED.turf_id ,
        gender_id                                = EXCLUDED.gender_id ,
        v_model_folder                 = EXCLUDED.v_model_folder ,
        v_file_name_3d_model                     = EXCLUDED.v_file_name_3d_model ,
        home_team_dugout_is_at_first_base_status = EXCLUDED.home_team_dugout_is_at_first_base_status,
        modified_by                              = CURRENT_USER,
        modified_ts                              = now()
    ;

INSERT INTO team.team (team_id,name_abbr,name_text,nickname)
VALUES (0,'UNK','Unknown','Team')
ON CONFLICT (team_id) DO NOTHING;

INSERT INTO team.team (team_id, name_text, name_abbr, nickname, logo_file_name, city_id, venue_id, league_id, sub_league_id, division_id, nation_id, parent_team_id, league_level_id, prevent_any_moves_status, human_team_status, human_manager_id, gender_id, background_color, text_color, ball_caps_main_color, ball_caps_visor_color, jersey_main_color, jersey_away_color, jersey_secondary_color, jersey_pin_stripes_color, all_star_team_status, historical_id,season)
SELECT
    team_id,
    t.name,
    t.abbr,
    CASE WHEN nickname != '' THEN nickname END,
    CASE WHEN t.logo_file_name != '' THEN t.logo_file_name END,
    CASE WHEN city_id != 0 then city_id END,
    park_id,
    t.league_id,
    sub_league_id,
    division_id,
    CASE WHEN t.nation_id != 0 THEN t.nation_id END,
    CASE WHEN parent_team_id != 0 THEN parent_team_id ELSE team_id END,
    level,
    prevent_any_moves::boolean,
    human_team::boolean,
    CASE WHEN human_id != 0 THEN human_id END,
    t.gender,
    t.background_color_id,
    t.text_color_id,
    ballcaps_main_color_id,
    ballcaps_visor_color_id,
    jersey_main_color_id,
    jersey_away_color_id,
    jersey_secondary_color_id,
    jersey_pin_stripes_color_id,
    allstar_team::boolean,
    CASE WHEN historical_id != '' THEN historical_id END,
    (SELECT l.season_year FROM leagues l WHERE l.league_id = t.league_id) as season_year
FROM teams t
EXCEPT SELECT team_id, name_text, name_abbr, nickname, logo_file_name, city_id, venue_id, league_id, sub_league_id, division_id, nation_id, parent_team_id, league_level_id, prevent_any_moves_status, human_team_status, human_manager_id, gender_id, background_color, text_color, ball_caps_main_color, ball_caps_visor_color, jersey_main_color, jersey_away_color, jersey_secondary_color, jersey_pin_stripes_color, all_star_team_status, historical_id,season
       FROM team.team
ON CONFLICT (team_id) DO UPDATE
    SET
        name_text = EXCLUDED.name_text ,
        name_abbr = EXCLUDED.name_abbr ,
        nickname = EXCLUDED.nickname ,
        logo_file_name = EXCLUDED.logo_file_name ,
        city_id = EXCLUDED.city_id ,
        venue_id = EXCLUDED.venue_id ,
        league_id = EXCLUDED.league_id ,
        sub_league_id = EXCLUDED.sub_league_id ,
        division_id = EXCLUDED.division_id ,
        nation_id = EXCLUDED.nation_id ,
        parent_team_id = EXCLUDED.parent_team_id ,
        league_level_id = EXCLUDED.league_level_id ,
        prevent_any_moves_status = EXCLUDED.prevent_any_moves_status ,
        human_team_status = EXCLUDED.human_team_status ,
        human_manager_id = EXCLUDED.human_manager_id ,
        gender_id = EXCLUDED.gender_id ,
        background_color = EXCLUDED.background_color ,
        text_color = EXCLUDED.text_color ,
        ball_caps_main_color = EXCLUDED.ball_caps_main_color ,
        ball_caps_visor_color = EXCLUDED.ball_caps_visor_color ,
        jersey_main_color = EXCLUDED.jersey_main_color ,
        jersey_away_color = EXCLUDED.jersey_away_color ,
        jersey_secondary_color = EXCLUDED.jersey_secondary_color ,
        jersey_pin_stripes_color = EXCLUDED.jersey_pin_stripes_color ,
        all_star_team_status = EXCLUDED.all_star_team_status ,
        historical_id = excluded.historical_id,
        season = excluded.season,
        modified_by = CURRENT_USER,
        modified_ts = now()
    ;

INSERT INTO player.player as p2 (player_id, team_id, league_id, position_id, role_id, first_name, last_name, nick_name, date_of_birth, city_of_birth_id, nation_id, second_nation_id, weight, height, retired_status, free_agent_status, last_league_id, last_team_id, organization_id, last_organization_id, language_id, uniform_number, experience, bats_id, throws_id, personality_greed, personality_loyalty, personality_play_for_winner, personality_work_ethic, personality_intelligence, personality_leader, historical_team_id, best_contract_offer_id, is_injured_status, dtd_injury_status, career_ending_injury_status, injury_il_left, injury_il_playoff_round, injury_left, dtd_injury_effect, dtd_injury_effect_hit, dtd_injury_effect_throw, dtd_injury_effect_run, injury_id, prone_overall, prone_leg, prone_back, prone_arm, fatigue_pitches, fatigue_points, fatigue_played_today,
                          college_status, acquired_id, acquired_date, draft_season, draft_round, draft_supplemental, draft_pick, draft_overall_pick, draft_eligible_status, hsc_status, red_shirt_status, picked_in_draft_status, school_id, commit_school_id, hidden_status, draft_league_id, draft_team_id, turned_coach_status, hall_of_fame_status, rust, inducted_season, strategy_override_team, strategy_stealing, strategy_running, strategy_bunt_for_hit, strategy_sac_bunt, strategy_hit_run, strategy_hook_start,
                          strategy_hook_relief, strategy_pitch_count, strategy_pitch_around, strategy_never_pinch_hit, strategy_defensive_sub, strategy_dtd_sit_min, strategy_dtd_allow_ph, local_popularity_id, national_popularity_id, draft_protected_status,
                          morale, morale_mod, morale_player_performance, morale_team_performance, morale_team_transactions, expectation_id, morale_player_role, on_loan_status, loan_league_id, loan_team_id)
SELECT
    player_id,
    CASE WHEN team_id > 0 THEN team_id END,
    CASE WHEN league_id > 0 THEN league_id END,
    CASE WHEN position > 0 THEN position END,
    CASE WHEN role > 0 THEN role END,
    first_name,
    last_name,
    CASE WHEN nick_name != '' THEN nick_name WHEN nick_name != '' THEN nick_name END,
    date_of_birth::date,
    CASE WHEN city_of_birth_id > 0 THEN city_of_birth_id END,
    nation_id,
    CASE WHEN second_nation_id > 0 THEN second_nation_id END,
    weight,
    height,
    retired::boolean,
    free_agent::boolean,
    CASE WHEN last_league_id > 0 THEN last_league_id END,
    CASE WHEN last_team_id > 0 THEN last_team_id END,
    CASE WHEN organization_id > 0 THEN organization_id END,
    CASE WHEN last_organization_id > 0 THEN last_organization_id END,
    array_remove(ARRAY[language_ids0,
                     language_ids1],-1)    ,
    uniform_number,
    experience,
    bats,
    throws,
    personality_greed,
    personality_loyalty,
    personality_play_for_winner,
    personality_work_ethic,
    personality_intelligence,
    personality_leader,
    CASE WHEN historical_team_id != '' THEN historical_team_id END,
    CASE WHEN best_contract_offer_id > 0 THEN best_contract_offer_id END,
    injury_is_injured::boolean,
    ARRAY[injury_dtd_injury::boolean,
        injury_dtd_injury2::boolean],
    injury_career_ending::boolean,
    injury_dl_left,
    injury_dl_playoff_round,
    ARRAY[injury_left,
        injury_left2],
    ARRAY[dtd_injury_effect,
        dtd_injury_effect2],
    ARRAY[dtd_injury_effect_hit,
        dtd_injury_effect_hit2],
    ARRAY[dtd_injury_effect_throw,
        dtd_injury_effect_throw2],
    ARRAY[dtd_injury_effect_run,
        dtd_injury_effect_run2],
    ARRAY[injury_id,
        injury_id2],
    prone_overall,
    prone_leg,
    prone_back,
    prone_arm,
    ARRAY[fatigue_pitches0,
        fatigue_pitches1,
        fatigue_pitches2,
        fatigue_pitches3,
        fatigue_pitches4,
        fatigue_pitches5],
    fatigue_points,
    fatigue_played_today,
    college::boolean,
    CASE WHEN acquired != -1 THEN acquired END,
    CASE WHEN acquired_date IS NOT NULL THEN acquired_date::date END,
    draft_year,
    draft_round,
    draft_supplemental,
    draft_pick,
    draft_overall_pick,
    draft_eligible::boolean,
    hsc_status::boolean,
    redshirt::boolean,
    picked_in_draft::boolean,
    CASE WHEN school > 0 THEN school END,
    CASE WHEN commit_school > 0 THEN commit_school END,
    hidden::boolean,
    draft_league_id,
    CASE WHEN draft_team_id > 0 AND (draft_team_id IN (SELECT league_id FROM league.league)) THEN draft_team_id END,
    turned_coach::boolean,
    hall_of_fame::boolean,
    rust,
    inducted,
    strategy_override_team,
    strategy_stealing,
    strategy_running,
    strategy_bunt_for_hit,
    strategy_sac_bunt,
    strategy_hit_run,
    strategy_hook_start,
    strategy_hook_relief,
    strategy_pitch_count,
    strategy_pitch_around,
    strategy_never_pinch_hit,
    CASE WHEN strategy_defensive_sub IS NOT NULL THEN strategy_defensive_sub::smallint END,
    strategy_dtd_sit_min,
    strategy_dtd_allow_ph,
    local_pop,
    national_pop,
    draft_protected::boolean,
    morale,
    morale_mod,
    morale_player_performance,
    morale_team_performance,
    morale_team_transactions,
    CASE WHEN expectation > 0 then expectation END,
    morale_player_role,
    on_loan::boolean,
    CASE WHEN loan_league_id > 0 THEN loan_league_id END,
    CASE WHEN loan_team_id > 0 THEN loan_team_id END
FROM players p
WHERE age < 1000
EXCEPT SELECT player_id, team_id, league_id, position_id, role_id, first_name, last_name, nick_name, date_of_birth, city_of_birth_id, nation_id, second_nation_id, weight, height, retired_status, free_agent_status, last_league_id, last_team_id, organization_id, last_organization_id, language_id, uniform_number, experience, bats_id, throws_id, personality_greed, personality_loyalty, personality_play_for_winner, personality_work_ethic, personality_intelligence, personality_leader, historical_team_id, best_contract_offer_id, is_injured_status, dtd_injury_status, career_ending_injury_status, injury_il_left, injury_il_playoff_round, injury_left, dtd_injury_effect, dtd_injury_effect_hit, dtd_injury_effect_throw, dtd_injury_effect_run, injury_id, prone_overall, prone_leg, prone_back, prone_arm, fatigue_pitches, fatigue_points, fatigue_played_today, college_status, acquired_id, acquired_date, draft_season, draft_round, draft_supplemental, draft_pick, draft_overall_pick, draft_eligible_status, hsc_status, red_shirt_status, picked_in_draft_status, school_id, commit_school_id, hidden_status, draft_league_id, draft_team_id, turned_coach_status, hall_of_fame_status, rust, inducted_season, strategy_override_team, strategy_stealing, strategy_running, strategy_bunt_for_hit, strategy_sac_bunt, strategy_hit_run, strategy_hook_start, strategy_hook_relief, strategy_pitch_count, strategy_pitch_around, strategy_never_pinch_hit, strategy_defensive_sub, strategy_dtd_sit_min, strategy_dtd_allow_ph, local_popularity_id, national_popularity_id, draft_protected_status, morale, morale_mod, morale_player_performance, morale_team_performance, morale_team_transactions, expectation_id, morale_player_role, on_loan_status, loan_league_id, loan_team_id
       FROM player.player
ON CONFLICT (player_id) DO UPDATE
    SET
        team_id = EXCLUDED.team_id ,
        league_id = EXCLUDED.league_id ,
        position_id = EXCLUDED.position_id ,
        role_id = EXCLUDED.role_id ,
        first_name = EXCLUDED.first_name ,
        last_name = EXCLUDED.last_name ,
        nick_name = COALESCE(EXCLUDED.nick_name,p2.nick_name) ,
        date_of_birth = EXCLUDED.date_of_birth ,
        city_of_birth_id = EXCLUDED.city_of_birth_id ,
        nation_id = EXCLUDED.nation_id ,
        second_nation_id = EXCLUDED.second_nation_id ,
        weight = EXCLUDED.weight ,
        height = EXCLUDED.height ,
        retired_status = EXCLUDED.retired_status ,
        free_agent_status = EXCLUDED.free_agent_status ,
        last_league_id = EXCLUDED.last_league_id ,
        last_team_id = EXCLUDED.last_team_id ,
        organization_id = EXCLUDED.organization_id ,
        last_organization_id = EXCLUDED.last_organization_id ,
        language_id = EXCLUDED.language_id ,
        uniform_number = EXCLUDED.uniform_number ,
        experience = EXCLUDED.experience ,
        bats_id = EXCLUDED.bats_id ,
        throws_id = EXCLUDED.throws_id ,
        personality_greed = EXCLUDED.personality_greed ,
        personality_loyalty = EXCLUDED.personality_loyalty ,
        personality_play_for_winner = EXCLUDED.personality_play_for_winner ,
        personality_work_ethic = EXCLUDED.personality_work_ethic ,
        personality_intelligence = EXCLUDED.personality_intelligence ,
        personality_leader = EXCLUDED.personality_leader ,
        historical_team_id = EXCLUDED.historical_team_id ,
        best_contract_offer_id = EXCLUDED.best_contract_offer_id ,
        is_injured_status = EXCLUDED.is_injured_status ,
        dtd_injury_status = EXCLUDED.dtd_injury_status ,
        career_ending_injury_status = EXCLUDED.career_ending_injury_status ,
        injury_il_left = EXCLUDED.injury_il_left ,
        injury_il_playoff_round = EXCLUDED.injury_il_playoff_round ,
        injury_left = EXCLUDED.injury_left ,
        dtd_injury_effect = EXCLUDED.dtd_injury_effect ,
        dtd_injury_effect_hit = EXCLUDED.dtd_injury_effect_hit ,
        dtd_injury_effect_throw = EXCLUDED.dtd_injury_effect_throw ,
        dtd_injury_effect_run = EXCLUDED.dtd_injury_effect_run ,
        injury_id = EXCLUDED.injury_id ,
        prone_overall = EXCLUDED.prone_overall ,
        prone_leg = EXCLUDED.prone_leg ,
        prone_back = EXCLUDED.prone_back ,
        prone_arm = EXCLUDED.prone_arm ,
        fatigue_pitches = EXCLUDED.fatigue_pitches ,
        fatigue_points = EXCLUDED.fatigue_points ,
        fatigue_played_today = EXCLUDED.fatigue_played_today ,
        college_status = EXCLUDED.college_status ,
        acquired_id = EXCLUDED.acquired_id ,
        acquired_date = EXCLUDED.acquired_date ,
        draft_season = EXCLUDED.draft_season ,
        draft_round = EXCLUDED.draft_round ,
        draft_supplemental = EXCLUDED.draft_supplemental ,
        draft_pick = EXCLUDED.draft_pick ,
        draft_overall_pick = EXCLUDED.draft_overall_pick ,
        draft_eligible_status = EXCLUDED.draft_eligible_status ,
        hsc_status = EXCLUDED.hsc_status ,
        red_shirt_status = EXCLUDED.red_shirt_status ,
        picked_in_draft_status = EXCLUDED.picked_in_draft_status ,
        school_id = EXCLUDED.school_id ,
        commit_school_id = EXCLUDED.commit_school_id ,
        hidden_status = EXCLUDED.hidden_status ,
        draft_league_id = EXCLUDED.draft_league_id ,
        draft_team_id = EXCLUDED.draft_team_id ,
        turned_coach_status = EXCLUDED.turned_coach_status ,
        hall_of_fame_status = EXCLUDED.hall_of_fame_status ,
        rust = EXCLUDED.rust ,
        inducted_season = EXCLUDED.inducted_season ,
        strategy_override_team = EXCLUDED.strategy_override_team ,
        strategy_stealing = EXCLUDED.strategy_stealing ,
        strategy_running = EXCLUDED.strategy_running ,
        strategy_bunt_for_hit = EXCLUDED.strategy_bunt_for_hit ,
        strategy_sac_bunt = EXCLUDED.strategy_sac_bunt ,
        strategy_hit_run = EXCLUDED.strategy_hit_run ,
        strategy_hook_start = EXCLUDED.strategy_hook_start ,
        strategy_hook_relief = EXCLUDED.strategy_hook_relief ,
        strategy_pitch_count = EXCLUDED.strategy_pitch_count ,
        strategy_pitch_around = EXCLUDED.strategy_pitch_around ,
        strategy_never_pinch_hit = EXCLUDED.strategy_never_pinch_hit ,
        strategy_defensive_sub = EXCLUDED.strategy_defensive_sub ,
        strategy_dtd_sit_min = EXCLUDED.strategy_dtd_sit_min ,
        strategy_dtd_allow_ph = EXCLUDED.strategy_dtd_allow_ph ,
        local_popularity_id = EXCLUDED.local_popularity_id ,
        national_popularity_id = EXCLUDED.national_popularity_id ,
        draft_protected_status = EXCLUDED.draft_protected_status ,
        morale = EXCLUDED.morale ,
        morale_mod = EXCLUDED.morale_mod,
        morale_player_performance = EXCLUDED.morale_player_performance ,
        morale_team_performance = EXCLUDED.morale_team_performance ,
        morale_team_transactions = EXCLUDED.morale_team_transactions ,
        expectation_id = EXCLUDED.expectation_id ,
        morale_player_role = EXCLUDED.morale_player_role ,
        on_loan_status = EXCLUDED.on_loan_status ,
        loan_league_id = EXCLUDED.loan_league_id ,
        loan_team_id = EXCLUDED.loan_team_id,
        modified_by = CURRENT_USER,
        modified_ts = now()
    ;

insert into player.coach (coach_id, first_name, last_name)
values (-1, 'OSA','Scout')
ON CONFLICT (coach_id) DO NOTHING;

create temporary table coaches
(
    coach_id                    integer PRIMARY KEY,
    first_name                  text,
    last_name                   text,
    nick_name                   text,
    age                         integer,
    date_of_birth               date,
    city_of_birth_id            integer,
    nation_id                   integer,
    weight                      integer,
    height                      integer,
    position                    integer,
    experience                  integer,
    occupation                  integer,
    team_id                     integer,
    former_player_id            integer,
    contract_salary             integer,
    contract_years              integer,
    contract_extension_salary   integer,
    contract_extension_years    integer,
    scout_major                 integer,
    scout_minor                 integer,
    scout_international         integer,
    scout_amateur               integer,
    scout_amateur_preference    integer,
    teach_hitting               integer,
    teach_pitching              integer,
    teach_c                     integer,
    teach_if                    integer,
    teach_of                    integer,
    handle_veterans             integer,
    handle_rookies              integer,
    handle_players              integer,
    heal_legs                   integer,
    heal_arms                   integer,
    heal_back                   integer,
    heal_other                  integer,
    heal_rest                   integer,
    management_style            integer,
    personality                 integer,
    hitting_focus               integer,
    pitching_focus              integer,
    training_focus              integer,
    teach_running               integer,
    prevent_legs                integer,
    prevent_arms                integer,
    prevent_back                integer,
    prevent_other               integer,
    stealing                    integer,
    running                     integer,
    pinchrun                    integer,
    pinchhit_pos                integer,
    pinchhit_pitch              integer,
    hook_start                  integer,
    hook_relief                 integer,
    closer                      integer,
    lr_matchup                  integer,
    bunt_hit                    integer,
    bunt                        integer,
    hit_run                     integer,
    run_hit                     integer,
    squeeze                     integer,
    pitch_around                integer,
    intentional_walk            integer,
    hold_runner                 integer,
    guard_lines                 integer,
    infield_in                  integer,
    outfield_in                 integer,
    corners_in                  integer,
    shift_if                    integer,
    shift_of                    integer,
    opener                      integer,
    num_pitchers                integer,
    num_hitters                 integer,
    favor_speed_to_power        integer,
    favor_avg_to_obp            integer,
    favor_defense_to_offense    integer,
    favor_pitching_to_hitting   integer,
    favor_veterans_to_prospects integer,
    trade_aggressiveness        integer,
    player_loyalty              integer,
    trade_frequency             integer,
    trade_preference            integer,
    value_stats                 integer,
    value_this_year             integer,
    value_last_year             integer,
    value_two_years             integer,
    draft_value                 integer,
    intl_fa_value               integer,
    develop_value               integer,
    ratings_value               integer,
    manager_value               integer,
    pitching_coach_value        integer,
    hitting_coach_value         integer,
    scout_value                 integer,
    doctor_value                integer,
    basecoach_value             integer,
    positive_relation           integer,
    negative_relation           integer
);

\copy coaches FROM '/Users/brianmcneil/Library/Containers/com.ootpdevelopments.ootp26macqlm/Data/Application Support/Out of the Park Developments/OOTP Baseball 26/saved_games/mlb-take-two.lg/import_export/csv/coaches.csv' DELIMITER ',' NULL AS 'NULL' CSV HEADER encoding 'UTF-8';

INSERT INTO player.coach(
    coach_id,
    first_name,
    last_name,
    nickname,
    date_of_birth,
    city_of_birth_id,
    nation_id,
    weight,
    height,
    position_id,
    experience,
    occupation_id,
    team_id,
    former_player_id,
    contract_salary,
    contract_seasons,
    contract_extension_salary,
    contract_extension_seasons,
    scout_major,
    scout_minor,
    scout_international,
    scout_amateur,
    scout_amateur_preference_id,
    teach_hitting,
    teach_pitching,
    teach_c,
    teach_if,
    teach_of,
    handle_veterans,
    handle_rookies,
    handle_players,
    heal_legs,
    heal_arms,
    heal_back,
    heal_other,
    heal_rest,
    management_style_id,
    personality_id,
    hitting_focus_id,
    pitching_focus_id,
    training_focus_id,
    teach_running,
    prevent_legs,
    prevent_arms,
    prevent_back,
    prevent_other,
    stealing,
    running,
    pinch_run,
    pinch_hit_pos,
    pinch_hit_pitch,
    hook_start,
    hook_relief,
    closer,
    lr_match_up,
    bunt_hit,
    bunt,
    hit_run,
    run_hit,
    squeeze,
    pitch_around,
    intentional_walk,
    hold_runner,
    guard_lines,
    infield_in,
    outfield_in,
    corners_in,
    shift_if,
    shift_of,
    opener,
    num_pitchers,
    num_hitters,
    favor_speed_to_power,
    favor_avg_to_obp,
    favor_defense_to_offense,
    favor_pitching_to_hitting,
    favor_veterans_to_prospects,
    trade_aggressiveness,
    player_loyalty,
    trade_frequency,
    trade_preference,
    value_stats,
    value_this_season,
    value_last_season,
    value_two_seasons,
    draft_value,
    international_fa_value,
    develop_value,
    ratings_value,
    manager_value,
    pitching_coach_value,
    hitting_coach_value,
    scout_value,
    doctor_value,
    base_coach_value,
    positive_relation_id,
    negative_relation_id)
SELECT
    coach_id,
    first_name,
    last_name,
    CASE WHEN nick_name != '' THEN nick_name END,
    date_of_birth,
    case when city_of_birth_id > 0 then city_of_birth_id end,
    nation_id,
    weight,
    height,
    position,
    experience,
    CASE WHEN occupation > 0 then occupation END,
    CASE WHEN team_id > 0 THEN team_id END,
    CASE WHEN former_player_id IN (SELECT player_id FROM player.player) THEN former_player_id END,
    contract_salary,
    contract_years,
    contract_extension_salary,
    contract_extension_years,
    scout_major,
    scout_minor,
    scout_international,
    scout_amateur,
    scout_amateur_preference,
    teach_hitting,
    teach_pitching,
    teach_c,
    teach_if,
    teach_of,
    handle_veterans,
    handle_rookies,
    handle_players,
    heal_legs,
    heal_arms,
    heal_back,
    heal_other,
    heal_rest,
    management_style,
    personality,
    hitting_focus,
    pitching_focus,
    training_focus,
    teach_running,
    prevent_legs,
    prevent_arms,
    prevent_back,
    prevent_other,
    stealing,
    running,
    pinchrun,
    pinchhit_pos,
    pinchhit_pitch,
    hook_start,
    hook_relief,
    closer,
    lr_matchup,
    bunt_hit,
    bunt,
    hit_run,
    run_hit,
    squeeze,
    pitch_around,
    intentional_walk,
    hold_runner,
    guard_lines,
    infield_in,
    outfield_in,
    corners_in,
    shift_if,
    shift_of,
    opener,
    num_pitchers,
    num_hitters,
    favor_speed_to_power,
    favor_avg_to_obp,
    favor_defense_to_offense,
    favor_pitching_to_hitting,
    favor_veterans_to_prospects,
    trade_aggressiveness,
    player_loyalty,
    trade_frequency,
    trade_preference,
    value_stats,
    value_this_year,
    value_last_year,
    value_two_years,
    draft_value,
    intl_fa_value,
    develop_value,
    ratings_value,
    manager_value,
    pitching_coach_value,
    hitting_coach_value,
    scout_value,
    doctor_value,
    basecoach_value,
    positive_relation,
    negative_relation
FROM coaches c
EXCEPT SELECT
    coach_id,
    first_name,
    last_name,
    nickname,
    date_of_birth,
    city_of_birth_id,
    nation_id,
    weight,
    height,
    position_id,
    experience,
    occupation_id,
    team_id,
    former_player_id,
    contract_salary,
    contract_seasons,
    contract_extension_salary,
    contract_extension_seasons,
    scout_major,
    scout_minor,
    scout_international,
    scout_amateur,
    scout_amateur_preference_id,
    teach_hitting,
    teach_pitching,
    teach_c,
    teach_if,
    teach_of,
    handle_veterans,
    handle_rookies,
    handle_players,
    heal_legs,
    heal_arms,
    heal_back,
    heal_other,
    heal_rest,
    management_style_id,
    personality_id,
    hitting_focus_id,
    pitching_focus_id,
    training_focus_id,
    teach_running,
    prevent_legs,
    prevent_arms,
    prevent_back,
    prevent_other,
    stealing,
    running,
    pinch_run,
    pinch_hit_pos,
    pinch_hit_pitch,
    hook_start,
    hook_relief,
    closer,
    lr_match_up,
    bunt_hit,
    bunt,
    hit_run,
    run_hit,
    squeeze,
    pitch_around,
    intentional_walk,
    hold_runner,
    guard_lines,
    infield_in,
    outfield_in,
    corners_in,
    shift_if,
    shift_of,
    opener,
    num_pitchers,
    num_hitters,
    favor_speed_to_power,
    favor_avg_to_obp,
    favor_defense_to_offense,
    favor_pitching_to_hitting,
    favor_veterans_to_prospects,
    trade_aggressiveness,
    player_loyalty,
    trade_frequency,
    trade_preference,
    value_stats,
    value_this_season,
    value_last_season,
    value_two_seasons,
    draft_value,
    international_fa_value,
    develop_value,
    ratings_value,
    manager_value,
    pitching_coach_value,
    hitting_coach_value,
    scout_value,
    doctor_value,
    base_coach_value,
    positive_relation_id,
    negative_relation_id
FROM player.coach
ON CONFLICT (coach_id) DO UPDATE
    SET
        first_name = excluded.first_name ,
        last_name = excluded.last_name ,
        nickname = excluded.nickname ,
        date_of_birth = excluded.date_of_birth ,
        city_of_birth_id = excluded.city_of_birth_id ,
        nation_id = excluded.nation_id ,
        weight = excluded.weight ,
        height = excluded.height ,
        position_id = excluded.position_id ,
        experience = excluded.experience ,
        occupation_id = excluded.occupation_id ,
        team_id = excluded.team_id ,
        former_player_id = excluded.former_player_id ,
        contract_salary = excluded.contract_salary ,
        contract_seasons = excluded.contract_seasons ,
        contract_extension_salary = excluded.contract_extension_salary ,
        contract_extension_seasons = excluded.contract_extension_seasons ,
        scout_major = excluded.scout_major ,
        scout_minor = excluded.scout_minor ,
        scout_international = excluded.scout_international ,
        scout_amateur = excluded.scout_amateur ,
        scout_amateur_preference_id = excluded.scout_amateur_preference_id ,
        teach_hitting = excluded.teach_hitting ,
        teach_pitching = excluded.teach_pitching ,
        teach_c = excluded.teach_c ,
        teach_if = excluded.teach_if ,
        teach_of = excluded.teach_of ,
        handle_veterans = excluded.handle_veterans ,
        handle_rookies = excluded.handle_rookies ,
        handle_players = excluded.handle_players ,
        heal_legs = excluded.heal_legs ,
        heal_arms = excluded.heal_arms ,
        heal_back = excluded.heal_back ,
        heal_other = excluded.heal_other ,
        heal_rest = excluded.heal_rest ,
        management_style_id = excluded.management_style_id ,
        personality_id = excluded.personality_id ,
        hitting_focus_id = excluded.hitting_focus_id ,
        pitching_focus_id = excluded.pitching_focus_id ,
        training_focus_id = excluded.training_focus_id ,
        teach_running = excluded.teach_running ,
        prevent_legs = excluded.prevent_legs ,
        prevent_arms = excluded.prevent_arms ,
        prevent_back = excluded.prevent_back ,
        prevent_other = excluded.prevent_other ,
        stealing = excluded.stealing ,
        running = excluded.running ,
        pinch_run = excluded.pinch_run ,
        pinch_hit_pos = excluded.pinch_hit_pos ,
        pinch_hit_pitch = excluded.pinch_hit_pitch ,
        hook_start = excluded.hook_start ,
        hook_relief = excluded.hook_relief ,
        closer = excluded.closer ,
        lr_match_up = excluded.lr_match_up ,
        bunt_hit = excluded.bunt_hit ,
        bunt = excluded.bunt ,
        hit_run = excluded.hit_run ,
        run_hit = excluded.run_hit ,
        squeeze = excluded.squeeze ,
        pitch_around = excluded.pitch_around ,
        intentional_walk = excluded.intentional_walk ,
        hold_runner = excluded.hold_runner ,
        guard_lines = excluded.guard_lines ,
        infield_in = excluded.infield_in ,
        outfield_in = excluded.outfield_in ,
        corners_in = excluded.corners_in ,
        shift_if = excluded.shift_if ,
        shift_of = excluded.shift_of ,
        opener = excluded.opener ,
        num_pitchers = excluded.num_pitchers ,
        num_hitters = excluded.num_hitters ,
        favor_speed_to_power = excluded.favor_speed_to_power ,
        favor_avg_to_obp = excluded.favor_avg_to_obp ,
        favor_defense_to_offense = excluded.favor_defense_to_offense ,
        favor_pitching_to_hitting = excluded.favor_pitching_to_hitting ,
        favor_veterans_to_prospects = excluded.favor_veterans_to_prospects ,
        trade_aggressiveness = excluded.trade_aggressiveness ,
        player_loyalty = excluded.player_loyalty ,
        trade_frequency = excluded.trade_frequency ,
        trade_preference = excluded.trade_preference ,
        value_stats = excluded.value_stats ,
        value_this_season = excluded.value_this_season ,
        value_last_season = excluded.value_last_season ,
        value_two_seasons = excluded.value_two_seasons ,
        draft_value = excluded.draft_value ,
        international_fa_value = excluded.international_fa_value ,
        develop_value = excluded.develop_value ,
        ratings_value = excluded.ratings_value ,
        manager_value = excluded.manager_value ,
        pitching_coach_value = excluded.pitching_coach_value ,
        hitting_coach_value = excluded.hitting_coach_value ,
        scout_value = excluded.scout_value ,
        doctor_value = excluded.doctor_value ,
        base_coach_value = excluded.base_coach_value ,
        positive_relation_id = excluded.positive_relation_id ,
        negative_relation_id = excluded.negative_relation_id,
        modified_by = current_user,
        modified_ts = now()
    ;


