create temporary table leagues
(
    league_id                              integer,
    name                                   text,
    abbr                                   text,
    nation_id                              integer,
    language_id                            integer,
    gender                                 integer,
    historical_league                      integer,
    logo_file_name                         text,
    players_path                           text,
    start_date                             text,
    preferred_start_date                   text,
    pitcher_award_name                     text,
    mvp_award_name                         text,
    rookie_award_name                      text,
    defense_award_name                     text,
    fictional_players                      integer,
    start_fantasy_draft                    integer,
    trading_deadline                       integer,
    winter_meetings                        integer,
    arbitration_offering                   integer,
    show_draft_pool                        integer,
    rosters_expanded                       integer,
    draft_date                             text,
    rule_5_draft_date                      text,
    international_fa_date                  text,
    roster_expand_date                     text,
    trade_deadline_date                    text,
    allstar_date                           text,
    days_until_deadline                    integer,
    next_draft_type                        integer,
    parent_league_id                       integer,
    league_state                           integer,
    season_year                            integer,
    historical_year                        integer,
    league_level                           integer,
    stats_detail                           integer,
    historical_import_path                 text,
    foreigner_percentage                   integer,
    was_ootp6                              integer,
    was_65                                 integer,
    allstar_game                           integer,
    auto_schedule_allstar                  integer,
    allstar_team_id0                       integer,
    allstar_team_id1                       integer,
    schedule_file_1                        text,
    schedule_file_2                        text,
    rules_rule_5                           integer,
    rules_minor_league_options             integer,
    rules_trading                          integer,
    rules_trading_deadline_events          integer,
    rules_draft_pick_trading               integer,
    rules_financials                       integer,
    rules_amateur_draft                    integer,
    rules_fa_compensation                  integer,
    rules_schedule_balanced                integer,
    rules_schedule_inter_league            integer,
    rules_schedule_force_start_day         integer,
    rules_trades_other_leagues             integer,
    rules_free_agents_from_other_leagues   integer,
    rules_free_agents_leave_other_leagues  integer,
    rules_allstar_game                     integer,
    rules_spring_training                  integer,
    rules_active_roster_limit              integer,
    rules_secondary_roster_limit           integer,
    rules_expanded_roster_limit            integer,
    rules_min_service_days                 integer,
    rules_waiver_period_length             integer,
    rules_dfa_period_length                integer,
    rules_fa_minimum_years                 integer,
    rules_salary_arbitration_minimum_years integer,
    rules_minor_league_fa_minimum_years    integer,
    rules_foreigner_limit                  integer,
    rules_foreigner_pitcher_limit          integer,
    rules_foreigner_hitter_limit           integer,
    rules_schedule_games_per_team          integer,
    rules_schedule_typical_series          integer,
    rules_schedule_game_times              integer,
    rules_schedule_preferred_start_day     integer,
    rules_amateur_draft_rounds             integer,
    rules_minimum_salary                   integer,
    rules_salary_cap                       integer,
    rules_player_salary0                   integer,
    rules_player_salary1                   integer,
    rules_player_salary2                   integer,
    rules_player_salary3                   integer,
    rules_player_salary4                   integer,
    rules_player_salary5                   integer,
    rules_player_salary6                   integer,
    rules_player_salary7                   integer,
    rules_average_coach_salary             integer,
    rules_average_attendance               integer,
    rules_average_national_media_contract  integer,
    rules_cash_maximum                     integer,
    rules_average_ticket_price             double precision,
    rules_luxury_sharing                   integer,
    rules_revenue_sharing                  integer,
    rules_revenue_sharing_tax              integer,
    rules_luxury_sharing_cap               integer,
    rules_luxury_tax                       integer,
    rules_national_media_contract_fixed    integer,
    rules_owner_decides_budget             integer,
    rules_schedule_auto_adjust_dates       integer,
    rules_historical_import_rookies        integer,
    avg_rating_contact                     integer,
    avg_rating_gap                         integer,
    avg_rating_power                       integer,
    avg_rating_eye                         integer,
    avg_rating_strikeouts                  integer,
    avg_rating_stuff                       integer,
    avg_rating_movement                    integer,
    avg_rating_control                     integer,
    avg_rating_fielding0                   integer,
    avg_rating_fielding1                   integer,
    avg_rating_fielding2                   integer,
    avg_rating_fielding3                   integer,
    avg_rating_fielding4                   integer,
    avg_rating_fielding5                   integer,
    avg_rating_fielding6                   integer,
    avg_rating_fielding7                   integer,
    avg_rating_fielding8                   integer,
    avg_rating_fielding9                   integer,
    avg_rating_overall                     integer,
    avg_rating_age                         double precision,
    league_totals_ab                       integer,
    league_totals_h                        integer,
    league_totals_d                        integer,
    league_totals_t                        integer,
    league_totals_hr                       integer,
    league_totals_bb                       integer,
    league_totals_hp                       integer,
    league_totals_k                        integer,
    league_totals_pa                       integer,
    league_totals_babip                    double precision,
    league_totals_mod_h                    double precision,
    league_totals_mod_d                    double precision,
    league_totals_mod_t                    double precision,
    league_totals_mod_hr                   double precision,
    league_totals_mod_bb                   double precision,
    league_totals_mod_hp                   double precision,
    league_totals_mod_k                    double precision,
    league_totals_mod_babip                double precision,
    ml_equivalencies_avg                   double precision,
    ml_equivalencies_hr                    double precision,
    ml_equivalencies_eb                    double precision,
    ml_equivalencies_bb                    double precision,
    ml_equivalencies_k                     double precision,
    ml_equivalencies_hp                    double precision,
    player_creation_modifier_contact       double precision,
    player_creation_modifier_gap           double precision,
    player_creation_modifier_power         double precision,
    player_creation_modifier_eye           double precision,
    player_creation_modifier_strikeouts    double precision,
    player_creation_modifier_stuff         double precision,
    player_creation_modifier_movement      double precision,
    player_creation_modifier_control       double precision,
    player_creation_modifier_speed         double precision,
    player_creation_modifier_fielding      double precision,
    financial_coefficient                  double precision,
    world_start_year                       integer,
    "current_date"                         text,
    background_color_id                    text,
    text_color_id                          text,
    scouting_coach_id                      integer
);

\copy leagues FROM '/Users/brianmcneil/Library/Containers/com.ootpdevelopments.ootp26macqlm/Data/Application Support/Out of the Park Developments/OOTP Baseball 26/saved_games/WPOBL-test.lg/import_export/csv/leagues.csv' DELIMITER ',' NULL AS 'NULL' CSV HEADER encoding 'UTF-8';

INSERT INTO league.league(league_id,
name_text,
name_abbr,
nation_id,
language_id,
gender_id,
historical_league_status,
logo_file_name,
player_path,
start_date,
preferred_start_date,
pitcher_award_name,
mvp_award_name,
rookie_award_name,
defense_award_name,
fictional_player_status,
start_fantasy_draft_status,
trading_deadline_status,
winter_meetings_status,
arbitration_offering_status,
show_draft_pool_status,
rosters_expanded_status,
draft_date,
rule_5_draft_date,
international_fa_date,
roster_expand_date,
trade_deadline_date,
all_star_date,
days_until_deadline,
next_draft_type_id,
parent_league_id,
league_state_id,
season_year,
historical_season,
league_level_id,
stats_detail_id,
historical_import_path,
foreigner_percentage,
was_ootp6_status,
was_65_status,
all_star_game_status,
auto_schedule_all_star_status,
all_star_team_id,
schedule_file,
rules_rule_5,
rules_minor_league_options,
rules_trading,
rules_trading_deadline_events,
rules_draft_pick_trading,
rules_financials,
rules_amateur_draft,
rules_fa_compensation,
rules_schedule_balanced,
rules_schedule_inter_league,
rules_schedule_force_start_day,
rules_trades_other_leagues,
rules_free_agents_from_other_leagues,
rules_free_agents_leave_other_leagues,
rules_all_star_game,
rules_spring_training,
rules_active_roster_limit,
rules_secondary_roster_limit,
rules_expanded_roster_limit,
rules_min_service_days,
rules_waiver_period_length,
rules_dfa_period_length,
rules_fa_minimum_seasons,
rules_salary_arbitration_minimum_seasons,
rules_minor_league_fa_minimum_seasons,
rules_foreigner_limit,
rules_foreigner_pitcher_limit,
rules_foreigner_hitter_limit,
rules_schedule_games_per_team,
rules_schedule_typical_series,
rules_schedule_game_times,
rules_schedule_preferred_start_day,
rules_amateur_draft_rounds,
rules_minimum_salary,
rules_salary_cap,
rules_player_salary,
rules_average_coach_salary,
rules_average_attendance,
rules_average_national_media_contract,
rules_cash_maximum,
rules_average_ticket_price,
rules_revenue_sharing,
rules_luxury_sharing,
rules_revenue_sharing_tax,
rules_luxury_sharing_cap,
rules_luxury_tax,
rules_national_media_contract_fixed,
rules_owner_decides_budget,
rules_schedule_auto_adjust_dates,
rules_historical_import_rookies,
avg_rating_contact,
avg_rating_gap,
avg_rating_power,
avg_rating_eye,
avg_rating_strikeouts,
avg_rating_stuff,
avg_rating_movement,
avg_rating_control,
avg_rating_fielding,
avg_rating_overall,
avg_rating_age,
league_totals_ab,
league_totals_h,
league_totals_d,
league_totals_t,
league_totals_hr,
league_totals_bb,
league_totals_hp,
league_totals_k,
league_totals_pa,
league_totals_babip,
league_totals_mod_h,
league_totals_mod_d,
league_totals_mod_t,
league_totals_mod_hr,
league_totals_mod_bb,
league_totals_mod_hp,
league_totals_mod_k,
league_totals_mod_babip,
ml_equivalencies_avg,
ml_equivalencies_hr,
ml_equivalencies_eb,
ml_equivalencies_bb,
ml_equivalencies_k,
ml_equivalencies_hp,
player_creation_modifier_contact,
player_creation_modifier_gap,
player_creation_modifier_power,
player_creation_modifier_eye,
player_creation_modifier_strikeouts,
player_creation_modifier_stuff,
player_creation_modifier_movement,
player_creation_modifier_control,
player_creation_modifier_speed,
player_creation_modifier_fielding,
financial_coefficient,
world_start_season,
present_date,
background_color_id,
text_color_id,
scouting_coach_id)
SELECT league_id,
       name,
       abbr,
       nation_id,
       language_id,
       gender,
       historical_league::boolean,
       logo_file_name,
       players_path,
       start_date::date,
       preferred_start_date::date,
       pitcher_award_name,
       mvp_award_name,
       rookie_award_name,
       defense_award_name,
       fictional_players::boolean,
       start_fantasy_draft::boolean,
       trading_deadline::boolean,
       winter_meetings::boolean,
       arbitration_offering::boolean,
       show_draft_pool::boolean,
       rosters_expanded::boolean,
       draft_date::date,
       rule_5_draft_date::date,
       l.international_fa_date::date ,
       roster_expand_date::date,
       trade_deadline_date::date,
       allstar_date::date,
       days_until_deadline,
       CASE WHEN next_draft_type != 0 THEN next_draft_type END,
       league_id,
       league_state,
       season_year,
       historical_year,
       league_level,
       stats_detail,
       historical_import_path,
       foreigner_percentage,
       was_ootp6::boolean,
       was_65::boolean,
       allstar_game::boolean,
       auto_schedule_allstar::boolean,
       ARRAY[allstar_team_id0,allstar_team_id1],
       ARRAY[schedule_file_1,schedule_file_2],
       rules_rule_5::boolean,
       rules_minor_league_options::boolean,
       rules_trading::boolean,
       rules_trading_deadline_events,
       rules_draft_pick_trading::boolean,
       rules_financials::boolean,
       rules_amateur_draft::boolean,
       rules_fa_compensation::boolean,
       rules_schedule_balanced::boolean,
       rules_schedule_inter_league::boolean,
       rules_schedule_force_start_day::boolean,
       rules_trades_other_leagues::boolean,
       rules_free_agents_from_other_leagues::boolean,
       rules_free_agents_leave_other_leagues::boolean,
       rules_allstar_game::boolean,
       rules_spring_training::boolean,
       rules_active_roster_limit,
       rules_secondary_roster_limit,
       rules_expanded_roster_limit,
       rules_min_service_days,
       rules_waiver_period_length,
       rules_dfa_period_length,
       rules_fa_minimum_years,
       rules_salary_arbitration_minimum_years,
       rules_minor_league_fa_minimum_years,
       rules_foreigner_limit,
       rules_foreigner_pitcher_limit,
       rules_foreigner_hitter_limit,
       rules_schedule_games_per_team,
       rules_schedule_typical_series,
       rules_schedule_game_times,
       rules_schedule_preferred_start_day,
       rules_amateur_draft_rounds,
       rules_minimum_salary,
       rules_salary_cap::boolean,
       ARRAY[rules_player_salary0::integer,
           rules_player_salary1::integer,
           rules_player_salary2::integer,
           rules_player_salary3::integer,
           rules_player_salary4::integer,
           rules_player_salary5::integer,
           rules_player_salary6::integer,
           rules_player_salary7::integer],
       rules_average_coach_salary,
       rules_average_attendance,
       rules_average_national_media_contract,
       rules_cash_maximum,
       rules_average_ticket_price,
       rules_revenue_sharing::boolean,
       l.rules_luxury_sharing::boolean ,
       l.rules_revenue_sharing_tax,
       l.rules_luxury_sharing_cap ,
       l.rules_luxury_tax,
       rules_national_media_contract_fixed::boolean,
       rules_owner_decides_budget::boolean,
       rules_schedule_auto_adjust_dates::boolean,
       rules_historical_import_rookies::boolean,
       avg_rating_contact,
       avg_rating_gap,
       avg_rating_power,
       avg_rating_eye,
       avg_rating_strikeouts,
       avg_rating_stuff,
       avg_rating_movement,
       avg_rating_control,
       ARRAY[avg_rating_fielding0,
           avg_rating_fielding1,
           avg_rating_fielding2,
           avg_rating_fielding3,
           avg_rating_fielding4,
           avg_rating_fielding5,
           avg_rating_fielding6,
           avg_rating_fielding7,
           avg_rating_fielding8,
           avg_rating_fielding9],
       avg_rating_overall,
       avg_rating_age,
       league_totals_ab,
       league_totals_h,
       league_totals_d,
       league_totals_t,
       league_totals_hr,
       league_totals_bb,
       league_totals_hp,
       league_totals_k,
       league_totals_pa,
       league_totals_babip,
       league_totals_mod_h,
       league_totals_mod_d,
       league_totals_mod_t,
       league_totals_mod_hr,
       league_totals_mod_bb,
       league_totals_mod_hp,
       league_totals_mod_k,
       league_totals_mod_babip,
       ml_equivalencies_avg,
       ml_equivalencies_hr,
       ml_equivalencies_eb,
       ml_equivalencies_bb,
       ml_equivalencies_k,
       ml_equivalencies_hp,
       player_creation_modifier_contact,
       player_creation_modifier_gap,
       player_creation_modifier_power,
       player_creation_modifier_eye,
       player_creation_modifier_strikeouts,
       player_creation_modifier_stuff,
       player_creation_modifier_movement,
       player_creation_modifier_control,
       player_creation_modifier_speed,
       player_creation_modifier_fielding,
       financial_coefficient,
       world_start_year,
       "current_date"::date,
       background_color_id,
       text_color_id,
       CASE WHEN scouting_coach_id != -1 then scouting_coach_id END
FROM leagues l
EXCEPT SELECT
    league_id,
    name_text,
    name_abbr,
    nation_id,
    language_id,
    gender_id,
    historical_league_status,
    logo_file_name,
    player_path,
    start_date,
    preferred_start_date,
    pitcher_award_name,
    mvp_award_name,
    rookie_award_name,
    defense_award_name,
    fictional_player_status,
    start_fantasy_draft_status,
    trading_deadline_status,
    winter_meetings_status,
    arbitration_offering_status,
    show_draft_pool_status,
    rosters_expanded_status,
    draft_date,
    rule_5_draft_date,
    international_fa_date,
    roster_expand_date,
    trade_deadline_date,
    all_star_date,
    days_until_deadline,
    next_draft_type_id,
    parent_league_id,
    league_state_id,
    season_year,
    historical_season,
    league_level_id,
    stats_detail_id,
    historical_import_path,
    foreigner_percentage,
    was_ootp6_status,
    was_65_status,
    all_star_game_status,
    auto_schedule_all_star_status,
    all_star_team_id,
    schedule_file,
    rules_rule_5,
    rules_minor_league_options,
    rules_trading,
    rules_trading_deadline_events,
    rules_draft_pick_trading,
    rules_financials,
    rules_amateur_draft,
    rules_fa_compensation,
    rules_schedule_balanced,
    rules_schedule_inter_league,
    rules_schedule_force_start_day,
    rules_trades_other_leagues,
    rules_free_agents_from_other_leagues,
    rules_free_agents_leave_other_leagues,
    rules_all_star_game,
    rules_spring_training,
    rules_active_roster_limit,
    rules_secondary_roster_limit,
    rules_expanded_roster_limit,
    rules_min_service_days,
    rules_waiver_period_length,
    rules_dfa_period_length,
    rules_fa_minimum_seasons,
    rules_salary_arbitration_minimum_seasons,
    rules_minor_league_fa_minimum_seasons,
    rules_foreigner_limit,
    rules_foreigner_pitcher_limit,
    rules_foreigner_hitter_limit,
    rules_schedule_games_per_team,
    rules_schedule_typical_series,
    rules_schedule_game_times,
    rules_schedule_preferred_start_day,
    rules_amateur_draft_rounds,
    rules_minimum_salary,
    rules_salary_cap,
    rules_player_salary,
    rules_average_coach_salary,
    rules_average_attendance,
    rules_average_national_media_contract,
    rules_cash_maximum,
    rules_average_ticket_price,
    rules_revenue_sharing,
    rules_luxury_sharing,
    rules_revenue_sharing_tax,
    rules_luxury_sharing_cap,
    rules_luxury_tax,
    rules_national_media_contract_fixed,
    rules_owner_decides_budget,
    rules_schedule_auto_adjust_dates,
    rules_historical_import_rookies,
    avg_rating_contact,
    avg_rating_gap,
    avg_rating_power,
    avg_rating_eye,
    avg_rating_strikeouts,
    avg_rating_stuff,
    avg_rating_movement,
    avg_rating_control,
    avg_rating_fielding,
    avg_rating_overall,
    avg_rating_age,
    league_totals_ab,
    league_totals_h,
    league_totals_d,
    league_totals_t,
    league_totals_hr,
    league_totals_bb,
    league_totals_hp,
    league_totals_k,
    league_totals_pa,
    league_totals_babip,
    league_totals_mod_h,
    league_totals_mod_d,
    league_totals_mod_t,
    league_totals_mod_hr,
    league_totals_mod_bb,
    league_totals_mod_hp,
    league_totals_mod_k,
    league_totals_mod_babip,
    ml_equivalencies_avg,
    ml_equivalencies_hr,
    ml_equivalencies_eb,
    ml_equivalencies_bb,
    ml_equivalencies_k,
    ml_equivalencies_hp,
    player_creation_modifier_contact,
    player_creation_modifier_gap,
    player_creation_modifier_power,
    player_creation_modifier_eye,
    player_creation_modifier_strikeouts,
    player_creation_modifier_stuff,
    player_creation_modifier_movement,
    player_creation_modifier_control,
    player_creation_modifier_speed,
    player_creation_modifier_fielding,
    financial_coefficient,
    world_start_season,
    present_date,
    background_color_id,
    text_color_id,
    scouting_coach_id
FROM league.league
ON CONFLICT (league_id) DO UPDATE
    SET
        name_text = EXCLUDED.name_text ,
        name_abbr = EXCLUDED.name_abbr ,
        nation_id = EXCLUDED.nation_id ,
        language_id = EXCLUDED.language_id ,
        gender_id = EXCLUDED.gender_id ,
        historical_league_status = EXCLUDED.historical_league_status ,
        logo_file_name = EXCLUDED.logo_file_name ,
        player_path = EXCLUDED.player_path ,
        start_date = COALESCE(league.start_date,EXCLUDED.start_date) ,
        preferred_start_date = COALESCE(league.preferred_start_date,EXCLUDED.preferred_start_date) ,
        pitcher_award_name = EXCLUDED.pitcher_award_name ,
        mvp_award_name = EXCLUDED.mvp_award_name ,
        rookie_award_name = EXCLUDED.rookie_award_name ,
        defense_award_name = EXCLUDED.defense_award_name ,
        fictional_player_status = EXCLUDED.fictional_player_status ,
        start_fantasy_draft_status = EXCLUDED.start_fantasy_draft_status ,
        trading_deadline_status = EXCLUDED.trading_deadline_status ,
        winter_meetings_status = EXCLUDED.winter_meetings_status ,
        arbitration_offering_status = EXCLUDED.arbitration_offering_status ,
        show_draft_pool_status = EXCLUDED.show_draft_pool_status ,
        rosters_expanded_status = EXCLUDED.rosters_expanded_status ,
        draft_date = COALESCE(league.draft_date,EXCLUDED.draft_date) ,
        rule_5_draft_date = COALESCE(league.rule_5_draft_date,EXCLUDED.rule_5_draft_date) ,
        international_fa_date = COALESCE(league.international_fa_date,EXCLUDED.international_fa_date) ,
        roster_expand_date = COALESCE(league.roster_expand_date,EXCLUDED.roster_expand_date) ,
        trade_deadline_date = COALESCE(league.trade_deadline_date,EXCLUDED.trade_deadline_date) ,
        all_star_date = COALESCE(league.all_star_date,EXCLUDED.all_star_date) ,
        days_until_deadline = EXCLUDED.days_until_deadline ,
        next_draft_type_id = EXCLUDED.next_draft_type_id ,
        parent_league_id = EXCLUDED.parent_league_id ,
        league_state_id = EXCLUDED.league_state_id ,
        season_year = EXCLUDED.season_year ,
        historical_season = EXCLUDED.historical_season ,
        league_level_id = CASE WHEN league.league_level_id = 9 THEN league.league_level_id ELSE EXCLUDED.league_level_id END  ,
        stats_detail_id = EXCLUDED.stats_detail_id ,
        historical_import_path = EXCLUDED.historical_import_path ,
        foreigner_percentage = EXCLUDED.foreigner_percentage ,
        was_ootp6_status = EXCLUDED.was_ootp6_status ,
        was_65_status = EXCLUDED.was_65_status ,
        all_star_game_status = EXCLUDED.all_star_game_status ,
        auto_schedule_all_star_status = EXCLUDED.auto_schedule_all_star_status ,
        all_star_team_id = EXCLUDED.all_star_team_id ,
        schedule_file = EXCLUDED.schedule_file ,
        rules_rule_5 = EXCLUDED.rules_rule_5 ,
        rules_minor_league_options = EXCLUDED.rules_minor_league_options ,
        rules_trading = EXCLUDED.rules_trading ,
        rules_trading_deadline_events = EXCLUDED.rules_trading_deadline_events ,
        rules_draft_pick_trading = EXCLUDED.rules_draft_pick_trading ,
        rules_financials = EXCLUDED.rules_financials ,
        rules_amateur_draft = EXCLUDED.rules_amateur_draft ,
        rules_fa_compensation = EXCLUDED.rules_fa_compensation ,
        rules_schedule_balanced = EXCLUDED.rules_schedule_balanced ,
        rules_schedule_inter_league = EXCLUDED.rules_schedule_inter_league ,
        rules_schedule_force_start_day = EXCLUDED.rules_schedule_force_start_day ,
        rules_trades_other_leagues = EXCLUDED.rules_trades_other_leagues ,
        rules_free_agents_from_other_leagues = EXCLUDED.rules_free_agents_from_other_leagues ,
        rules_free_agents_leave_other_leagues = EXCLUDED.rules_free_agents_leave_other_leagues ,
        rules_all_star_game = EXCLUDED.rules_all_star_game ,
        rules_spring_training = EXCLUDED.rules_spring_training ,
        rules_active_roster_limit = EXCLUDED.rules_active_roster_limit ,
        rules_secondary_roster_limit = EXCLUDED.rules_secondary_roster_limit ,
        rules_expanded_roster_limit = EXCLUDED.rules_expanded_roster_limit ,
        rules_min_service_days = EXCLUDED.rules_min_service_days ,
        rules_waiver_period_length = EXCLUDED.rules_waiver_period_length ,
        rules_dfa_period_length = EXCLUDED.rules_dfa_period_length ,
        rules_fa_minimum_seasons = EXCLUDED.rules_fa_minimum_seasons ,
        rules_salary_arbitration_minimum_seasons = EXCLUDED.rules_salary_arbitration_minimum_seasons ,
        rules_minor_league_fa_minimum_seasons = EXCLUDED.rules_minor_league_fa_minimum_seasons ,
        rules_foreigner_limit = EXCLUDED.rules_foreigner_limit ,
        rules_foreigner_pitcher_limit = EXCLUDED.rules_foreigner_pitcher_limit ,
        rules_foreigner_hitter_limit = EXCLUDED.rules_foreigner_hitter_limit ,
        rules_schedule_games_per_team = EXCLUDED.rules_schedule_games_per_team ,
        rules_schedule_typical_series = EXCLUDED.rules_schedule_typical_series ,
        rules_schedule_game_times = excluded.rules_schedule_game_times,
        rules_schedule_preferred_start_day = EXCLUDED.rules_schedule_preferred_start_day ,
        rules_amateur_draft_rounds = EXCLUDED.rules_amateur_draft_rounds ,
        rules_minimum_salary = EXCLUDED.rules_minimum_salary ,
        rules_salary_cap = EXCLUDED.rules_salary_cap ,
        rules_player_salary = EXCLUDED.rules_player_salary ,
        rules_average_coach_salary = EXCLUDED.rules_average_coach_salary ,
        rules_average_attendance = EXCLUDED.rules_average_attendance ,
        rules_average_national_media_contract = EXCLUDED.rules_average_national_media_contract ,
        rules_cash_maximum = EXCLUDED.rules_cash_maximum ,
        rules_average_ticket_price = EXCLUDED.rules_average_ticket_price ,
        rules_luxury_sharing = EXCLUDED.rules_luxury_sharing ,
        rules_revenue_sharing = EXCLUDED.rules_revenue_sharing ,
        rules_luxury_sharing_cap = EXCLUDED.rules_luxury_sharing_cap ,
        rules_revenue_sharing_tax = EXCLUDED.rules_revenue_sharing_tax ,
        rules_luxury_tax = EXCLUDED.rules_luxury_tax ,
        rules_national_media_contract_fixed = EXCLUDED.rules_national_media_contract_fixed ,
        rules_owner_decides_budget = EXCLUDED.rules_owner_decides_budget ,
        rules_schedule_auto_adjust_dates = EXCLUDED.rules_schedule_auto_adjust_dates ,
        rules_historical_import_rookies = EXCLUDED.rules_historical_import_rookies ,
        avg_rating_contact = EXCLUDED.avg_rating_contact ,
        avg_rating_gap = EXCLUDED.avg_rating_gap ,
        avg_rating_power = EXCLUDED.avg_rating_power ,
        avg_rating_eye = EXCLUDED.avg_rating_eye ,
        avg_rating_strikeouts = EXCLUDED.avg_rating_strikeouts ,
        avg_rating_stuff = EXCLUDED.avg_rating_stuff ,
        avg_rating_movement = EXCLUDED.avg_rating_movement ,
        avg_rating_control = EXCLUDED.avg_rating_control ,
        avg_rating_fielding = EXCLUDED.avg_rating_fielding ,
        avg_rating_overall = EXCLUDED.avg_rating_overall ,
        avg_rating_age = EXCLUDED.avg_rating_age ,
        league_totals_ab = EXCLUDED.league_totals_ab ,
        league_totals_h = EXCLUDED.league_totals_h ,
        league_totals_d = EXCLUDED.league_totals_d ,
        league_totals_t = EXCLUDED.league_totals_t ,
        league_totals_hr = EXCLUDED.league_totals_hr ,
        league_totals_bb = EXCLUDED.league_totals_bb ,
        league_totals_hp = EXCLUDED.league_totals_hp ,
        league_totals_k = EXCLUDED.league_totals_k ,
        league_totals_pa = EXCLUDED.league_totals_pa ,
        league_totals_babip = EXCLUDED.league_totals_babip ,
        league_totals_mod_h = EXCLUDED.league_totals_mod_h ,
        league_totals_mod_d = EXCLUDED.league_totals_mod_d ,
        league_totals_mod_t = EXCLUDED.league_totals_mod_t ,
        league_totals_mod_hr = EXCLUDED.league_totals_mod_hr ,
        league_totals_mod_bb = EXCLUDED.league_totals_mod_bb ,
        league_totals_mod_hp = EXCLUDED.league_totals_mod_hp ,
        league_totals_mod_k = EXCLUDED.league_totals_mod_k ,
        league_totals_mod_babip = EXCLUDED.league_totals_mod_babip ,
        ml_equivalencies_avg = EXCLUDED.ml_equivalencies_avg ,
        ml_equivalencies_hr = EXCLUDED.ml_equivalencies_hr ,
        ml_equivalencies_eb = EXCLUDED.ml_equivalencies_eb ,
        ml_equivalencies_bb = EXCLUDED.ml_equivalencies_bb ,
        ml_equivalencies_k = EXCLUDED.ml_equivalencies_k ,
        ml_equivalencies_hp = EXCLUDED.ml_equivalencies_hp ,
        player_creation_modifier_contact = EXCLUDED.player_creation_modifier_contact ,
        player_creation_modifier_gap = EXCLUDED.player_creation_modifier_gap ,
        player_creation_modifier_power = EXCLUDED.player_creation_modifier_power ,
        player_creation_modifier_eye = EXCLUDED.player_creation_modifier_eye ,
        player_creation_modifier_strikeouts = EXCLUDED.player_creation_modifier_strikeouts ,
        player_creation_modifier_stuff = EXCLUDED.player_creation_modifier_stuff ,
        player_creation_modifier_movement = EXCLUDED.player_creation_modifier_movement ,
        player_creation_modifier_control = EXCLUDED.player_creation_modifier_control ,
        player_creation_modifier_speed = EXCLUDED.player_creation_modifier_speed ,
        player_creation_modifier_fielding = EXCLUDED.player_creation_modifier_fielding ,
        financial_coefficient = EXCLUDED.financial_coefficient ,
        world_start_season = EXCLUDED.world_start_season ,
        present_date = EXCLUDED.present_date ,
        background_color_id = EXCLUDED.background_color_id ,
        text_color_id = EXCLUDED.text_color_id ,
        scouting_coach_id = excluded.scouting_coach_id,
        modified_by = CURRENT_USER,
        modified_ts = now()
    ;
