truncate stats_csv.allstarfull;
\copy stats_csv.allstarfull FROM 'Documents/Personal/ootp_stuff/databaseConverter/stats_csv/AllstarFull.csv' DELIMITER ',' NULL AS '' CSV HEADER encoding 'UTF-8';
truncate stats_csv.awardsmanagers;
\copy stats_csv.awardsmanagers FROM 'Documents/Personal/ootp_stuff/databaseConverter/stats_csv/awardsmanagers.csv' DELIMITER ',' NULL AS '' CSV HEADER encoding 'UTF-8';
truncate stats_csv.awardsplayers;
\copy stats_csv.awardsplayers FROM 'Documents/Personal/ootp_stuff/databaseConverter/stats_csv/awardsplayers.csv' DELIMITER ',' NULL AS '' CSV HEADER encoding 'UTF-8';
truncate stats_csv.batting;
\copy stats_csv.batting FROM 'Documents/Personal/ootp_stuff/databaseConverter/stats_csv/batting.csv' DELIMITER ',' NULL AS '' CSV HEADER encoding 'UTF-8';
truncate stats_csv.batting2;
\copy stats_csv.batting2 FROM 'Documents/Personal/ootp_stuff/databaseConverter/stats_csv/batting2.csv' DELIMITER ',' NULL AS '' CSV HEADER encoding 'UTF-8';
truncate stats_csv.battingpost;
\copy stats_csv.battingpost FROM 'Documents/Personal/ootp_stuff/databaseConverter/stats_csv/battingpost.csv' DELIMITER ',' NULL AS '' CSV HEADER encoding 'UTF-8';
truncate stats_csv.battingsplits;
\copy stats_csv.battingsplits FROM 'Documents/Personal/ootp_stuff/databaseConverter/stats_csv/battingsplits.csv' DELIMITER ',' NULL AS '' CSV HEADER encoding 'UTF-8';
truncate stats_csv.eosrosters;
\copy stats_csv.eosrosters FROM 'Documents/Personal/ootp_stuff/databaseConverter/stats_csv/eosrosters.csv' DELIMITER ',' NULL AS '' CSV encoding 'UTF-8';
truncate stats_csv.fielding;
\copy stats_csv.fielding FROM 'Documents/Personal/ootp_stuff/databaseConverter/stats_csv/fielding.csv' DELIMITER ',' NULL AS '' CSV HEADER encoding 'UTF-8';
truncate stats_csv.fieldingof;
\copy stats_csv.fieldingof FROM 'Documents/Personal/ootp_stuff/databaseConverter/stats_csv/fieldingof.csv' DELIMITER ',' NULL AS '' CSV HEADER encoding 'UTF-8';
truncate stats_csv.fieldingpost;
\copy stats_csv.fieldingpost FROM 'Documents/Personal/ootp_stuff/databaseConverter/stats_csv/fieldingpost.csv' DELIMITER ',' NULL AS '' CSV HEADER encoding 'UTF-8';
truncate stats_csv.fieldingratings;
\copy stats_csv.fieldingratings FROM 'Documents/Personal/ootp_stuff/databaseConverter/stats_csv/fieldingratings.csv' DELIMITER ',' NULL AS '' CSV HEADER encoding 'UTF-8';
truncate stats_csv.halloffame;
\copy stats_csv.halloffame FROM 'Documents/Personal/ootp_stuff/databaseConverter/stats_csv/halloffame.csv' DELIMITER ',' NULL AS '' CSV HEADER encoding 'UTF-8';
truncate stats_csv.lineups;
--\copy stats_csv.lineups FROM 'Documents/Personal/ootp_stuff/databaseConverter/stats_csv/lineups.csv' DELIMITER ',' NULL AS '' CSV encoding 'UTF-8';
truncate stats_csv.managers;
\copy stats_csv.managers FROM 'Documents/Personal/ootp_stuff/databaseConverter/stats_csv/managers.csv' DELIMITER ',' NULL AS '' CSV HEADER encoding 'UTF-8';
truncate stats_csv.master;
\copy stats_csv.master FROM 'Documents/Personal/ootp_stuff/databaseConverter/stats_csv/master.csv' DELIMITER ',' NULL AS '' CSV HEADER encoding 'UTF-8';
truncate stats_csv.milbbatting;
--\copy stats_csv.milbbatting FROM 'Documents/Personal/ootp_stuff/databaseConverter/stats_csv/milbbatting.csv' DELIMITER ',' NULL AS '' CSV HEADER encoding 'UTF-8';
truncate stats_csv.milbfielding;
--\copy stats_csv.milbfielding FROM 'Documents/Personal/ootp_stuff/databaseConverter/stats_csv/milbfielding.csv' DELIMITER ',' NULL AS '' CSV HEADER encoding 'UTF-8';
truncate stats_csv.milbleagues;
--\copy stats_csv.milbleagues FROM 'Documents/Personal/ootp_stuff/databaseConverter/stats_csv/milbleagues.csv' DELIMITER ',' NULL AS '' CSV HEADER encoding 'UTF-8';
truncate stats_csv.milbmaster;
--\copy stats_csv.milbmaster FROM 'Documents/Personal/ootp_stuff/databaseConverter/stats_csv/milbmaster.csv' DELIMITER ',' NULL AS '' CSV HEADER encoding 'UTF-8';
truncate stats_csv.milbpitching;
--\copy stats_csv.milbpitching FROM 'Documents/Personal/ootp_stuff/databaseConverter/stats_csv/milbpitching.csv' DELIMITER ',' NULL AS '' CSV HEADER encoding 'UTF-8';
truncate stats_csv.milbteams;
\copy stats_csv.milbteams FROM 'Documents/Personal/ootp_stuff/databaseConverter/stats_csv/milbteams.csv' DELIMITER ',' NULL AS '' CSV HEADER encoding 'UTF-8';
truncate stats_csv.negroleaguebatting;
--\copy stats_csv.negroleaguebatting FROM 'Documents/Personal/ootp_stuff/databaseConverter/stats_csv/negroleaguebatting.csv' DELIMITER ',' NULL AS '' CSV HEADER encoding 'UTF-8';
truncate stats_csv.negroleaguefielding;
--\copy stats_csv.negroleaguefielding FROM 'Documents/Personal/ootp_stuff/databaseConverter/stats_csv/negroleaguefielding.csv' DELIMITER ',' NULL AS '' CSV HEADER encoding 'UTF-8';
truncate stats_csv.negroleaguepitching;
--\copy stats_csv.negroleaguepitching FROM 'Documents/Personal/ootp_stuff/databaseConverter/stats_csv/negroleaguepitching.csv' DELIMITER ',' NULL AS '' CSV HEADER encoding 'UTF-8';
truncate stats_csv.odrosters;
\copy stats_csv.odrosters FROM 'Documents/Personal/ootp_stuff/databaseConverter/stats_csv/odrosters.csv' DELIMITER ',' NULL AS '' CSV encoding 'UTF-8';
truncate stats_csv.pitching;
\copy stats_csv.pitching FROM 'Documents/Personal/ootp_stuff/databaseConverter/stats_csv/pitching.csv' DELIMITER ',' NULL AS '' CSV HEADER encoding 'UTF-8';
truncate stats_csv.pitching2;
\copy stats_csv.pitching2 FROM 'Documents/Personal/ootp_stuff/databaseConverter/stats_csv/pitching2.csv' DELIMITER ',' NULL AS '' CSV HEADER encoding 'UTF-8';
truncate stats_csv.pitchingratings;
\copy stats_csv.pitchingratings FROM 'Documents/Personal/ootp_stuff/databaseConverter/stats_csv/pitchingratings.csv' DELIMITER ',' NULL AS '' CSV HEADER encoding 'UTF-8';
truncate stats_csv.pitchingsplits;
\copy stats_csv.pitchingsplits FROM 'Documents/Personal/ootp_stuff/databaseConverter/stats_csv/pitchingsplits.csv' DELIMITER ',' NULL AS '' CSV HEADER encoding 'UTF-8';
truncate stats_csv.recordssinglegame;
--\copy stats_csv.recordssinglegame FROM 'Documents/Personal/ootp_stuff/databaseConverter/stats_csv/recordssinglegame.csv' DELIMITER ',' NULL AS '' CSV HEADER encoding 'UTF-8';
truncate stats_csv.teamfranchises;
\copy stats_csv.teamfranchises FROM 'Documents/Personal/ootp_stuff/databaseConverter/stats_csv/teamfranchises.csv' DELIMITER ',' NULL AS '' CSV HEADER encoding 'UTF-8';
truncate stats_csv.teams;
\copy stats_csv.teams FROM 'Documents/Personal/ootp_stuff/databaseConverter/stats_csv/teams.csv' DELIMITER ',' NULL AS '' CSV HEADER encoding 'UTF-8';
truncate stats_csv.transactions;
--\copy stats_csv.transactions FROM 'Documents/Personal/ootp_stuff/databaseConverter/stats_csv/transactions.csv' DELIMITER ',' NULL AS '' CSV encoding 'UTF-8';
truncate stats_csv.uninumbers;
\copy stats_csv.uninumbers FROM 'Documents/Personal/ootp_stuff/databaseConverter/stats_csv/uninumbers.csv' DELIMITER ',' NULL AS '' CSV HEADER encoding 'UTF-8';

